### ISSUE TITLE
['Редагувати профіль' page] 'Національність' and 'Віровизнання' and 'Громадська, політична діяльність' fields could be edited and saved using forbidden symbols

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1006]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: medium
**Severity**: low
**Build found**:

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log into the system using your credentials
3. By default, you would be directed on 'Персональні дані' insert and your name and surname would be the same as you have entered during your registration session

**Steps to reproduce**
Click on 'Редагувати профіль' tab on the right upper corner on the page
Enter in your 'Національність' field 'українка `.' (using {`} and {.} symbols) and into 'Віровизнання' field 'християнка `.' (using {`} and {.} symbols) and into 'Громадська, політична діяльність' field 'активістка `.' (using {`} and {.} symbols) (see attached screen)
Click on 'Підтвердити' button

**Actual result**
Your 'Національність' and 'Віровизнання' and 'Громадська, політична діяльність' fields have been filled in
You have been directed on 'Персональні дані' insert

**Expected result**
The error message should appear 'Поле повинно містити тільки літери'

**User story and test case links**
"User story #699 
![Screenshot at Mar 09 08-03-48](https://user-images.githubusercontent.com/79641118/110426005-ff8c1480-80ad-11eb-8978-9c5cb82637a3.png)

**Comment by IvMariana** [comment]
The error message appear 'Поле повинно містити тільки літери'
