### ISSUE TITLE
['Редагувати профіль' page] 'Національність' and 'Віровизнання' fields can not be edited and saved using {()} symbol

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1008]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: medium
**Severity**: low
**Build found**:

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log into the system using your credentials
3. By default, you would be directed on 'Персональні дані' insert and your name and surname would be the same as you have entered during your registration session

**Steps to reproduce**
Click on 'Редагувати профіль' tab on the right upper corner on the page
Enter in your 'Національність' field 'українка ()' (using {()} symbol) and into 'Віровизнання' field 'християнка ()' (using {()}  symbol) (see attached screen)
Click on 'Підтвердити' button

**Actual result**
The error message appears 'Поле повинно містити тільки літери'

**Expected result**
This symbol {()} is allowed according to user story #699 so no error message should appear and a user should successfully edit and save info in these fields using {()} symbol

**User story and test case links**
"User story #699 
![Screenshot at Mar 09 09-25-26](https://user-images.githubusercontent.com/79641118/110433869-ba6ddf80-80b9-11eb-84ba-fe63e896a5f3.png)

**Comment by IvMariana** [comment]
Cannot add symbol {()} to 'Національність' and 'Віровизнання' fields 
After clicking on 'Підтвердити' button  appears pop-up window 'Щось пішло не так. Спробуйте ще раз.'

![pop-up](https://user-images.githubusercontent.com/81759772/113824355-5b6abb80-9788-11eb-8018-f2c8865bdce8.png)

![pop-up  console](https://user-images.githubusercontent.com/81759772/113824830-e946a680-9788-11eb-96a8-e1d2b3259443.png)
