### ISSUE TITLE
['Редагувати профіль' page] 'Національність' and 'Віровизнання' and 'Громадська, політична діяльність' fields can be edited and saved using records with CAPS LOCK in 

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1009]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: medium
**Severity**: low
**Build found**:

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log into the system using your credentials
3. By default, you would be directed on 'Персональні дані' insert and your name and surname would be the same as you have entered during your registration session

**Steps to reproduce**
Click on 'Редагувати профіль' tab on the right upper corner on the page
Enter in your 'Національність' field 'УКРАЇНКА' and into 'Віровизнання' field 'ХРИСТИЯНКА' and into 'Громадська, політична діяльність' field 'АКТИВІСТКА' (see attached screen)
Click on 'Підтвердити' button

**Actual result**
Your 'Національність' and 'Віровизнання' and 'Громадська, політична діяльність' fields have been filled in
You have been directed on 'Персональні дані' insert

**Expected result**
Only the first letter of each word could be uppercase

**User story and test case links**
"User story #699 
![Screenshot at Mar 09 09-40-55](https://user-images.githubusercontent.com/79641118/110435333-901d2180-80bb-11eb-866c-d5509a415f3a.png)

**Comment by IvMariana** [comment]
Only the first letter of each word is uppercase
