### ISSUE TITLE
[Annual reports] Textboxes are not aligned in one row when 2 error messages are shown at once on "Подати річний звіт станиці" page

### ISSUE THREAD

**Issue by BohdanKachmar** [ita-social-projects/EPlast#1019]
Environment:
Windows 10 build 19041.804 64bit, Firefox v86.0, Google Chrome v88.0.4324.190

Reproducible:
always

Build found:
commit 6bf189b

Preconditions:
Create/have a user with 'Станиці' admin or 'Super admin' rights

Test Steps:

1. Go to https://eplast.westeurope.cloudapp.azure.com/signin
2. Login as an admin of 'Округи'
3. Click on 'Звітування та Статистика' > 'Річні звіти'
4. Click on 'Подати річний звіт станиці'
5. Select from the dropdown list "Станицю" that doesn't have report yet
6. Click on any textbox field (e.g. "Кількість гніздечок пташат")
7. Enter value that will cause 2 error messages at once (e.g. "ssssss" )

Actual result
Textboxes are not aligned in one row

Expected result
Textboxes should be aligned in one row

Priority
Low

Severity
Trivial
![Annual report alignment bug](https://user-images.githubusercontent.com/62644817/110607663-16a53200-8194-11eb-8a6d-7c7b6ce48c6a.PNG)

**Comment by ohumenchuk** [comment]
verified as field does not allow any other input except (API tested)
