### ISSUE TITLE
[Personal profile] [Edit profile] Missing error message for a single character in the text fields

### ISSUE THREAD

**Issue by IvMariana** [ita-social-projects/EPlast#1098]
**Environment:** Windows 10 version 2004, Google Chrome Version 89.0.4389.114
**Reproducible:** always
**Priority:** medium
**Severity:** low
**Build found:** ae0cbb7

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com/signin
2. Login as ‘Прихильник’ user

**Steps to reproduce**
1. Go to ' Персональні дані'
2. Click on 'Редагувати профіль'
3. Set value ‘A' in 'Ім'я' field
4. Set value ‘A' in 'Прізвище' field
5. Set value ‘A' in 'По-батькові' field
6. Set value ‘A’ in ‘Псевдо’ field

**Actual result**
Error messages "Мінімальна довжина - 2 символи." doesn't display under fields

**Expected result**
Error messages "Мінімальна довжина - 2 символи." should display under fields
**Note:** When you set two characters 'Aa' and delete the second character error message will appear

**User story and test case links**
E.g.: "User story #699

![Missing error message for a single character in the text fields](https://user-images.githubusercontent.com/81759772/113700663-c90edd00-96df-11eb-860b-c2d4ce00afaf.png)

**Comment by Vinnytile** [comment]
This is due to the use of the function to replace the first letter with a capital letter. Unfortunately, at the moment it is impossible to get rid of it. If you click the button Підтвердити, a length message will still appear. That's why this thing remains.
