### ISSUE TITLE
['Редагувати профіль'] maximum symbols amount in 'Навчальний ступінь' field is 30 instead of 50

### ISSUE THREAD

**Issue by ohumenchuk** [ita-social-projects/EPlast#1099]
**Environment:** Windows 8.1 Enterprise, Chrome Version 89.0.4389.114 (Official Build) (64-bit);
**Reproducible:** always;
**Build found:** commit ae0cbb7

**Preconditions:**
Go to https://eplast.westeurope.cloudapp.azure.com and log into the system using your credentials. You are directed by default to ‘Персональні дані’ tab and your name and surname are the same as you entered during registration.

**Steps to reproduce:**
1) Press on ‘Редагувати профіль’ tab;
2) Enter into 'Навчальний ступінь' more than 30 allowed symbols, for example: ‘Магістр з прикладної лінгвістики 1-і категорії ’.

**Actual result:**
 A validation message ‘Максимальна довжина - 30 символів’ appears.

**Expected result:**
According to User Story #699, maximum length should be 50 symbols.

**User story and test case links:**
User Story #699

![PP3](https://user-images.githubusercontent.com/81754181/113715633-6410b280-96f2-11eb-9089-37c05dee62d6.PNG)

**Comment by skshetska** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/81754156/119264170-b0547b00-bbea-11eb-8801-414462e9777e.png)
