### ISSUE TITLE
['Редагувати профіль']  ‘Спеціальність’, ‘Навчальний ступінь’, ‘Посада’ cannot contain special symbols

### ISSUE THREAD

**Issue by ohumenchuk** [ita-social-projects/EPlast#1100]
**Environment:** Windows 8.1 Enterprise, Chrome Version 89.0.4389.114 (Official Build) (64-bit);
**Reproducible:** always;
**Build found:** commit ae0cbb7.

**Preconditions:**
Go to https://eplast.westeurope.cloudapp.azure.com and log into the system using your credentials. You are directed by default to ‘Персональні дані’ tab and your name and surname are the same as you entered during registration.

**Steps to reproduce:**
1) Press on ‘Редагувати профіль’ tab;
2) Enter into ‘Спеціальність’ tab data containing special symbols (except dot (‘.’), left an right parenthesises ‘()’, quotes (' " '), hyphen (‘-’), space (' '), apostrophe (''')), for example: 
‘Спеціальність’ text box -  'Інженер Розряду №1';
‘Навчальний ступінь’ text box – ‘Магістр  # 1 категорії’;
‘Посада’ text box – ‘С++ програміст‘ (please see attachment).

**Actual result:**
Validation message ‘Поле повинно містити тільки літери’  appears.

**Expected result:**
According to User Story #699, **any** special symbols should be allowed into ‘Спеціальність’, ‘Навчальний ступінь’, ‘Посада’ text boxes. No validation message should appear.

**User story and test case links:**
User story #699
![PP1](https://user-images.githubusercontent.com/81754181/113728534-dd160700-96fe-11eb-83a3-89fa8f68e687.PNG)

**Comment by skshetska** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/81754156/119264292-31137700-bbeb-11eb-8025-6095bf9002d1.png)

**Comment by skshetska** [comment]
![1](https://user-images.githubusercontent.com/81754156/119264300-42f51a00-bbeb-11eb-9827-0a5e785b6272.png)
