### ISSUE TITLE
['Редагувати профіль'] Error message "Неправильний формат посилання" is not displayed after entering to the 'Посилання на Facebook', 'Посилання на Twitter', 'Посилання на Instagram' fields  invalid value

### ISSUE THREAD

**Issue by skshetska** [ita-social-projects/EPlast#1103]
**Environment:** Windows 10x64, Opera 74.0.3911.218 .
**Reproducible:** always
**Build found:** commit ae0cbb7

**Preconditions**
Log into https://eplast.westeurope.cloudapp.azure.com using user's credentials. Be sure user is on ‘Персональні дані’ tab.

**Steps to reproduce**
1. Click on 'Редагувати профіль' tab
2. Scroll down to  'Посилання на Facebook'
3. Enter to the **'Посилання на Facebook', 'Посилання на Twitter', 'Посилання на Instagram'** fields invalid value "MichaelSапроhchur"
4. Click on the 'Посилання на Instagram' button
5. Pay attention to the fields content.

**Actual result**
Error message "Неправильний формат посилання" is not displayed after entering to the 'Посилання на Facebook', 'Посилання на Twitter', 'Посилання на Instagram' fields  invalid value

**Expected result**
Error message "Неправильний формат посилання" is displayed after entering to the fields  invalid value. According to User Story #699,the value in the fields should be filled in the following format: start with "http" and finish with ".com". After being saved, the value is displayed in the following format: {username}/

**User story link**
User story #699

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")
![1](https://user-images.githubusercontent.com/81754156/113849053-c1b00800-97a1-11eb-95b7-6b76bd3d23f3.jpg)

**Comment by IrynaZavushchak** [comment]
Not a bug
