### ISSUE TITLE
[Personal profile] Resizing screen suggestion

### ISSUE THREAD

**Issue by IvMariana** [ita-social-projects/EPlast#1112]
According to the requirements (User Story #699), the "Редагувати профіль" tab consists of 2 sections, but when the User resizes the page, the text fields overlaps. 

When the User crosses near 50% of the Full-screen size, all text fields align 1 column. Please take a look at the attached screenshots with examples.

So my suggestion is to align text fields in a 1 column after the User goes out from Full-screen. It will help the User to see the page more clearly and aesthetic. 

![full_small screen](https://user-images.githubusercontent.com/81759772/114031401-044a1100-9884-11eb-96a8-5c72148dfba5.png)
![resizing](https://user-images.githubusercontent.com/81759772/114031664-41160800-9884-11eb-87ba-b252e7aeb555.png)

**Comment by christykobyletska** [comment]
already fixed.
