### ISSUE TITLE
[Кадра виховників][Short profile] Failed to open with 403 error 

### ISSUE THREAD

**Issue by IvMariana** [ita-social-projects/EPlast#1132]
Environment: Windows 10 version 2004, Version 89.0.4389.114
Reproducible: always
Priority: high
Severity: major
Build found: ae0cbb7

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com/signin
2. Login as ‘Прихильник’ user.

**Steps to reproduce**
1. Go to 'Кадра виховників’
2. Click on any  'Користувач' (e.g. ID 13)
3. Press on 'Переглянути профіль' button
**Note:** issue also reproducible if a User is login as 'Дійсний член організації' 

**Actual result**
Failed to open with 403 error.

**Expected result**
View a short profile of other ePlast users.

**User story and test case links**
E.g.: "User story  #955

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by skshetska** [comment]
Please,  add City Hovel Country admins to the note
