### ISSUE TITLE
['Річні звіти','Курені'] incorrect length validation in DB for 'Географія куреня'/'Побажання до КБ УСП' fields

### ISSUE THREAD

**Issue by ohumenchuk** [ita-social-projects/EPlast#1153]
**Environment:** Windows 8.1 Enterprise, Chrome Version 89.0.4389.114 (Official Build) (64-bit);
**Reproducible:** always;
**Build found:** 13eb975;
**Priority:** medium;
**Severity:** low.

**Preconditions:**
Go to https://eplast.westeurope.cloudapp.azure.com, log into system as a 'Голова Куреня'. Go to **Main Menu**/**Звітування та Статистика**/**Річні звіти**.

**Steps to reproduce:**
1. Press **Подати річний звіт куреня** button;
2. In **Оберіть курінь для створення річного звіту** modal window select a hovel from drop-down list;
3. In **Річний звіт куреня** window fill in **До куреня приєдналось за звітній період** and **Вибули з куреня за звітній період** with any digit data (e.g., 1);
4. Type 2000 symbols into **Географія куреня. Осередки в Україні:** and **Вкажіть побажання до КБ УСП**;
5. Press **Подати річний звіт** button.

**Actual result:**
A notification 'Щось пішло не так. Спробуйте ще раз' appears in the top right corner. Report is not created. In DevTool a server response 'Максимально допустима кількість символів 200' appears (please see attachments).

**Note:** if to type more than 2000 symbols into **Географія куреня. Осередки в Україні:** and **Вкажіть побажання до КБ УСП**, a validation messages 'Максимальна довжина - 2000 символів' appear under each field.

**Expected result:**
2000 symbols should be allowed to be entered into both fields.
![Bug eplast 2](https://user-images.githubusercontent.com/81754181/115982757-2642d380-a5a6-11eb-8b0e-a4880557130b.png)
![bug eplast3](https://user-images.githubusercontent.com/81754181/115982762-2a6ef100-a5a6-11eb-83ca-bcd205875154.PNG)
![Bug eplast 1](https://user-images.githubusercontent.com/81754181/115982769-2e027800-a5a6-11eb-9056-47be499b17f7.PNG)

**Comment by skshetska** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/81754156/119475581-f37f2d00-bd55-11eb-8898-de921d74a2b3.png)

**Comment by skshetska** [comment]
**Expected result:**
200 symbols should be allowed to be entered into both fields.
