### ISSUE TITLE
[Округи] A User isn't restricted from being an Admin of different Regions at the same time

### ISSUE THREAD

**Issue by ohumenchuk** [ita-social-projects/EPlast#1154]
**Environment:** Windows 8.1 Enterprise, Chrome Version 89.0.4389.114 (Official Build) (64-bit);
**Reproducible:** always;
**Build found:** 13eb975;
**Priority:** high;
**Severity:** low.

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com, log into system as a Super-Admin. Go to **Main Menu/Таблиця користувачів**.

**Steps to reproduce:**
1. In **Таблиця користувачів** grid find a User with 'Дійсний член організації' access level.
2. Grand a User with 'Голова округу' role (**right button click on User's name/Змінити права доступу/Провід округи**);
3. From **Оберіть округу для користувача** drop-down list select **any** Region;
4. In **Додати в провід округи** window select 'Голова округи' from **Тип адміністрування** drop-down list.
5. Repeat steps 2-4 for 1 more Region.

**Actual result:**
A User gets Admin role in different Regions at the same time with no restrictions.

**Expected result**
As per [Провід куреня, станиці, округи](https://docs.google.com/document/d/1CUpjA8gJhp9njOGIKF0j29D8xkoy1lHSmvwWOtgQ1q0/edit#heading=h.ux35qvyn2g9) document, a User, who is not a 'Крайовий адмін', cannot be a head of several Regions at the same time.

**Comment by veronika-kolosova** [comment]
role "Крайовий адмін" is not realized yet, so region admin can be head of several regions

**Comment by OlgaShtogryn** [comment]
Uploading провід округи.mp4…
Also, the region editing window appears when user does right button click on User's name/Змінити права доступу/Провід станиці and vice versa.
![1](https://user-images.githubusercontent.com/87722808/129473577-2d2232a3-f8eb-4786-bfde-d1f13ce44603.png)
![2](https://user-images.githubusercontent.com/87722808/129473578-97fc001a-c12b-4588-bcfe-ef40ac737f6b.png)
