### ISSUE TITLE
[User's Profile] 'Голова округи' cannot view full profiles of Region's members

### ISSUE THREAD

**Issue by ohumenchuk** [ita-social-projects/EPlast#1155]
**Environment:** Windows 8.1 Enterprise, Chrome Version 89.0.4389.114 (Official Build) (64-bit);
**Reproducible:** always;
**Build found:** 13eb975;
**Priority:** high;
**Severity:** low.

**Preconditions:**
Go to: https://eplast.westeurope.cloudapp.azure.com, log into system as a 'Голова округи' and as 'Adherent/Прихильник'

**Steps to reproduce:**
1. Select and open your **Округа** page by path: **Main Menu/Довідник/Округи**;
2. In **Члени округи** frame select any **Станиця**;
3. Once **Станиця** page is opened, click at any User from **Члени станиці** module.
   3.1. **Note:** User should not belong to your **Курінь**.
4. At User's profile page pay attention to **Персональні дані** tab.

**Actual result:**
Only shortened profile info is displayed.

**Expected result**
As per [Рівні доступу](https://docs.google.com/spreadsheets/d/1u52VumXUi0r_ev1JWSSCUDehL4gnM2UecbBy0zM0S7I/edit#gid=103040533) document, Region Admin should be able to see a full profile of a Users, that belong to his/her Region.

![Bug eplast4](https://user-images.githubusercontent.com/81754181/115997703-d1767b80-a5ec-11eb-8b2d-b75c69bda6e0.PNG)

**Comment by ZoryanaKravchuk** [comment]
'Прихильник' should be able to see a full profile of Users, that belong to his/her City and Hovel
![Профіль](https://user-images.githubusercontent.com/87931020/130323394-cf040d8b-9e27-4f20-b8a2-46f89756e378.png)

**Comment by ZoryanaKravchuk** [comment]
**Also, look issue:   [Profiles] The Region Admin, which is an Adherent, doesn't see the 'Бланки' and 'Події' tabs at the profiles of the members of his Region. #1652**

**Steps to reproduce**

1.Go to Main Menu.
2.Click on 'Округи'.
3.Click on the region, the Admin of which you are.
4.Click on any member of the 'Провід округи'.
5.Take a look at the profile of the member of your Region.

**Actual result**
The Region Admin, which is an Adherent, doesn't see the 'Бланки' and 'Події' tabs at the profiles of the members of his Region.
![1](https://user-images.githubusercontent.com/87722808/129780753-2a45df71-1978-422d-ace7-2ad91b5ef12c.png)

**Expected result**
The Region Admin, which is an Adherent, should see the full profiles with all tabs of the members of his Region.
![2](https://user-images.githubusercontent.com/87722808/129780924-188f0c60-f463-4ad5-b9df-0fef19097e42.png)

**Comment by solomiiatarnavska** [comment]
This bug has been sent to 'Done' since we have one global bug which covers all these demands (https://github.com/ita-social-projects/EPlast/issues/1458)

So the comment to see/fix/check this one has been added.
