### ISSUE TITLE
[Персональні дані] Progress Bar should not be complete until probation period is over

### ISSUE THREAD

**Issue by ohumenchuk** [ita-social-projects/EPlast#1178]
**Environment:** Windows 8.1 Enterprise, Chrome Version 89.0.4389.114 (Official Build) (64-bit);
**Reproducible:** always;
**Build found:** commit 8179f79;
**Severity:** minor;
**Priority:** low.

**Preconditions:**
Go to https://eplast.westeurope.cloudapp.azure.com/ and log in as any User who has access to full profiles of other Users (Super Admin, for example).

**Steps to reproduce:**
1. Find a User who has a 'Прихильник' access level for almost 365 days and **Progress Bar** on;
2. Wait until there is 1 day before a probation period is over;
3. Pay attention to **Progress Bar** view.

**Actual result:**
Progress bar looks complete despite the fact that there is still 1 day left (see attachment).

**Expected result:**
**Progress Bar** should not be complete until probation period is over. There should still be some percentage values displayed.

![2](https://user-images.githubusercontent.com/81754181/116697902-6ce06580-a9cc-11eb-8a62-50a356045749.PNG)

**Comment by skshetska** [comment]
![31](https://user-images.githubusercontent.com/81754156/119660245-b2f7e000-be37-11eb-9e29-5bd06c0d684d.png)
Please, add hours to Progress Bar instead of "0 дні"
