### ISSUE TITLE
[API, Редагувати профіль] 'Стать' data is not restricted from changes

### ISSUE THREAD

**Issue by ohumenchuk** [ita-social-projects/EPlast#1190]
**Environment:** Windows 8.1 Enterprise, Chrome Version 89.0.4389.114 (Official Build) (64-bit);
**Reproducible:** always;
**Build found:** commit dee71b4;
**Severity:** minor;
**Priority:** low.

**Pre-conditions:**
1. Open DevTools for a browser tab;
2. Into this tab go to application: https://eplast.westeurope.cloudapp.azure.com/ and log in as a User (any role). You are automatically redirected to **Персональні дані** page. At the page top select **Редагувати профіль** tab;
3. Run Postman and create a PUT request;
4. In DevTools/Sources tab put breakpoint next to window.location.reload(), update any data and press **Підтвердити** button. Catch needed URL https://eplast.westeurope.cloudapp.azure.com/api/User/editbase64.

**Steps to reproduce:**
1. Copy token (type Bearer Token) and request body (format JSON) from catched request in DevTools to Postman;
2. Postman: Into request body update value for 'gender' key (for example, put 'Сир' instead of 'Жінка');
3. Postman: Press 'Send' button.

**Actual result:**
Response status code: 200 OK. Data is changed in data base and, respectively, into application (in 'Стать' drop-down there are three options now: 'Сир', 'Чоловік', 'Інше').

**Expected result:**
Restriction should be established for updating data into 'Gender' field.

**Post-conditions:**
Postman: Update the gender data back to 'Жінка' and send request again.

**Comment by NataliaVoloshynska** [comment]
Into request body update value for 'gender' key (for example, put 'Жінка' instead of 'Чоловік')
Actual result:
In 'Стать' drop-down there are three options now: 'Жінка', 'Жінка', 'Не маю бажання вказувати'
![стать](https://user-images.githubusercontent.com/87755327/129360176-df14e205-80d3-4034-8fb1-904fda8d19fc.png)
