### ISSUE TITLE
[Country Board] there is no option to add automatically 1 year in case term of Country's Board member has been expired

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1217]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: medium
**Severity**: medium
**Build found**: 7a45982

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin

**Steps to reproduce**
1.Go to 'Довідник' and choose 'Округи' section in the left side of a page
2.Open a Country you want (e.g. Львівська Округа)
3.Go to 'Провід округи'
4.Edit any user you want (see attached screen below) by clicking on * icon
5.Pay attention on End date

**Actual result**
The end date has been outdated

**Expected result**
Despite the end date is overdue, according to business rule (see attached screen below) the system may prolong the term on Country Board. So in this case I guess would be better to add 1 more year in case the term has been expired.
https://docs.google.com/document/d/1CUpjA8gJhp9njOGIKF0j29D8xkoy1lHSmvwWOtgQ1q0/edit

**User story and test case links**
![Screenshot at May 13 22-13-35](https://user-images.githubusercontent.com/79641118/118176202-c8cdd400-b439-11eb-8edc-667b4f27dd99.png)
![Screenshot at May 13 22-21-34](https://user-images.githubusercontent.com/79641118/118176210-ca979780-b439-11eb-9b47-efd9bbc009ba.png)

**Comment by Vinnytile** [comment]
This functionality will only work on new members of the administration. It is impossible to prolong the term of administration on the existing members of the administration.
