### ISSUE TITLE
[Documents] Alignment issue on a Country Documents tab

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1240]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: low
**Severity**: low
**Build found**: 5762451

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Go to 'Довідник' and choose 'Округи' section
2.Choose any Country you see, e.g 'Львівська'
3.Open 'Документообіг округи' section (see attached screen below)
4.Press 'Більше' button
5.Pay your attention on the alignment of documents (see attached screen below)

**Actual result**
There is no uniform alignment, maybe it's related to the title's size of the Document (1-2 rows it may take)

**Expected result**
The uniform alignment should be present

**User story and test case links**
![Screenshot at May 20 11-11-04](https://user-images.githubusercontent.com/79641118/118943627-78380880-b95c-11eb-8da0-cbbad9670416.png)
![Screenshot at May 20 11-13-48](https://user-images.githubusercontent.com/79641118/118943650-7bcb8f80-b95c-11eb-9b75-9f1e650ae885.png)

**Comment by Tania-Volovetska** [comment]
The bug is also reproduced in 'Члени станиці' and  'Члени куреня' sections.
![image](https://user-images.githubusercontent.com/3681311/124403780-a7ee7480-dd40-11eb-8ee3-bb54abf7fff1.png)
![image](https://user-images.githubusercontent.com/3681311/124403825-e84df280-dd40-11eb-8eda-23d4030580e4.png)

**Comment by christykobyletska** [comment]
the same issue is on city/club followers

**Comment by solomiiatarnavska** [comment]
Regarding documents name _on a City_ we have this depicting
![Screenshot at Aug 15 23-16-04](https://user-images.githubusercontent.com/79641118/129491538-7e0f449e-f7c7-445d-b2cc-6ba4052ac707.png)

Regarding documents name _on a Hovel_ we have this depicting
![Screenshot at Aug 15 23-18-47](https://user-images.githubusercontent.com/79641118/129491620-e00f0b93-4fa5-4b78-902e-749bbe7621fa.png)

Regarding documents name _on a Region_ we have this depicting
![Screenshot at Aug 15 23-21-45](https://user-images.githubusercontent.com/79641118/129491672-8da72eb3-7df5-4af4-9f08-20dd7e303d37.png)

**Comment by solomiiatarnavska** [comment]
Regarding user's name _on a City_
![Screenshot at Aug 15 23-30-01](https://user-images.githubusercontent.com/79641118/129491869-42b48cc8-4b67-426e-b1e2-abe9cd11ba24.png)

Regarding user's name _on a Hovel_
![Screenshot at Aug 15 23-32-00](https://user-images.githubusercontent.com/79641118/129491897-d1e1516a-c397-4407-b911-06851841761e.png)

Regarding user's name _on a Region_
![Screenshot at Aug 15 23-33-39](https://user-images.githubusercontent.com/79641118/129491932-c8cfac75-1f0e-4b2b-8ca1-d451d19721a3.png)

**Comment by christykobyletska** [comment]
I'll add tooltip to "Документообіг куреня". Can we create new bug just for adding hyphen after word-break?
