### ISSUE TITLE
Add a "Decision/Рішення Керівних Органів"

### ISSUE THREAD

**Issue by Odrees** [ita-social-projects/EPlast#1248]
As an Admin (Крайовий/Окружний/Станичний/Куреня/Cупер Адмін), I want to add a"Decisions/Рішення Керівних Органів" so that other ePlast participants can see the essence of decision and status.

**Preconditions:**
1.The user is logged in as an administrator (Крайовий/Окружний/Станичний/Куреня/Супер Адмін).
2. The user has opened the page "Рішення керівних органів".

![Рішення](https://user-images.githubusercontent.com/83400080/119224171-da803d00-bb05-11eb-88f8-028fcc97498b.jpg)

### Assumptions and Constraints:
**Business rules:**
1.Крайовий/Окружний/Станичний/Куреня та Супер administrators can add a "Decision/Рішення керівних органів"

![Адміністрування_Рішення](https://user-images.githubusercontent.com/83400080/119224256-42368800-bb06-11eb-9bfc-faba2a0110c3.jpg)

Find more information about the access levels in the document "Рівні доступу"

**Acceptance Criteria:**
1.	The administrator clicks the "Add solution" button

![Додати_рішення](https://user-images.githubusercontent.com/83400080/119224310-7c078e80-bb06-11eb-971d-2b5f86285273.jpg)

2.When you click on the icon, the system opens a pop-up window "Додати рішення пластового проводу"

![Додати_рішення_проводу_окно](https://user-images.githubusercontent.com/83400080/119224358-b113e100-bb06-11eb-96eb-3c417e797aee.jpg)

3.The pop-up contains the following fields:

![Таблиця](https://user-images.githubusercontent.com/83400080/119224418-03550200-bb07-11eb-816f-b09d1f7f2348.jpg)

4. After checking the entered data, press the button «Опублікувати»

![Опублікувати](https://user-images.githubusercontent.com/83400080/119224427-0f40c400-bb07-11eb-85f5-8851263d5a40.jpg)

5. It is possible to unpublish the Decision. Press the button «Відмінити»

6. After clicking «Опублікувати» - the Decision is added to the table «Рішення керівних органів»

![Таблиця рішення керівних органів](https://user-images.githubusercontent.com/83400080/119224444-241d5780-bb07-11eb-89a2-c928379d7621.jpg)

**Epic link**
E.g.: Epic #100 [Epic](https://jira.softserve.academy/browse/100)

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by Odrees** [comment]
File size 50Mb

**Comment by ksapiha** [comment]
The maximum number of characters for 'Назва рішення' is **60**
