### ISSUE TITLE
[Governing Bodies] Spelling of Governing Bodies/керівних органів should be unified and TBD

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1269]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: low
**Severity**: low
**Build found**: f7a0541

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Go to the left-side pannel on the main page and choose 'Рішення' section
2.Pay attention on the title 'Рішення керівних органів' (see attaches screen below)

**Actual result**
'Рішення керівних органів' is written with the lower uppercase ('керівних органів')

**Expected result**
All it was mentioned in User Stories, all terminology related with the Governing Bodies should be rewritten with the uppercase ('Керівних Органів' instead of 'керівних органів')

**User story and test case links**
https://github.com/ita-social-projects/EPlast/issues/852
![Screenshot at May 26 22-17-31](https://user-images.githubusercontent.com/79641118/119718550-5fee4f00-be70-11eb-9a37-028932e68682.png)
![Screenshot at May 26 22-18-46](https://user-images.githubusercontent.com/79641118/119718557-6250a900-be70-11eb-865c-05699aea4f1b.png)

**Comment by christykobyletska** [comment]
Not a bug. Talked with Luidmyla about this.
