### ISSUE TITLE
[Репозитарій page] Dates in 'Дата' column are invalid

### ISSUE THREAD

**Issue by anastasiiatytarchuk** [ita-social-projects/EPlast#1277]
**Priority:** low
**Severity:** minor

**Environment:** MacOS, v.11.2.3., Safari
**Reproducible:** always
**Build found:** f7a0541

**Steps to reproduce**
1. Login as admin to Eplast system
2. Go to 'Репозитарій' page (https://eplast.westeurope.cloudapp.azure.com/legislation)

**Actual result**
1. Dates in 'Дата' column are invalid.

**Expected result**
1. Dates in 'Дата' column are displayed in the table.

<img width="1082" alt="Снимок экрана 2021-05-31 в 12 09 25" src="https://user-images.githubusercontent.com/83136306/120169867-0cca2280-c209-11eb-83d4-e5e06fa3d447.png">

**Comment by christykobyletska** [comment]
already fixed. another bug was created about this but for firefox (https://github.com/ita-social-projects/EPlast/issues/1396).

**Comment by solomiiatarnavska** [comment]
already fixed. another bug was created about this but for firefox (#1396) and also was fixed by Yullia Lozynska
