### ISSUE TITLE
[Access levels] [Adherent/ Plast's member] [Regions] The user does not have access to the 'Округи' page.

### ISSUE THREAD

**Issue by skshetska** [ita-social-projects/EPlast#1285]
**Environment:** Windows 10x64, Google Chrome 89.0.4389.114
**Reproducible:** always
**Priority:** high
**Severity:** high
**Build found:** 3603f19

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the application as a Plast's Member
You can find the login and password here https://docs.google.com/spreadsheets/d/19km_8hd-TRTEbpWAjhqkwJaeERESF0PoMmH5vfQdek0/edit?usp=sharing

**Steps to reproduce**
1. Go to the left-side menu of the website
2. Expand the 'Довідник' option
3. Click on 'Округи' category
4. Pay attention to the screen

**Actual result**
The Plast's Member does not have access to the 'Округи' page.
![2021-05-31_22-25-05](https://user-images.githubusercontent.com/81754156/120233876-66f5d280-c25f-11eb-98d8-f52188951dd5.jpg)
This issue also reproduces for Adherent

**Expected result**
The Plast's Member and the Adherent should have access to the 'Округи' page.
![Screenshot_5](https://user-images.githubusercontent.com/81754156/120234192-264a8900-c260-11eb-9cd2-4e9d7793c891.png)

**User story and test case links**
E.g.: "User story #100

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by olesiakhrushch** [comment]
**Steps to reproduce:**

1. Log in to the application as an Adherent 
2. Go to the left-side menu of the website
2. Expand the 'Довідник' option
3. Click on 'Округи' category
4. Click on any "Округа
