### ISSUE TITLE
[Documents] it looks like there is a built (hidden) link on Documents section

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1329]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: low
**Severity**: low
**Build found**: fd1bfc9

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Plast member (Дійсний член органзізації)

**Steps to reproduce**
1.Go to 'Довідник' and choose 'Станиці' (City) section
2.Сhoose a City you do/do not belong to (actually it does not matter) and open it
3.Find 'Документообіг станиці' and put mouse on the name of any of its. Pay attention to the linking of documents
4.Repeat these steps with a Hovel and a Country documentation (see attached screen below)

**Actual result**
There is a 'built' link when a user is trying to press on any documentation in a City/Hovel/Country, but whan you are trying to press on it nothing happens

**Expected result**
Please delete this link from the documents so that there would be only one possibility to open a document just to press 'Більше' button

**User story and test case links**
![Screenshot at Jun 13 21-40-58](https://user-images.githubusercontent.com/79641118/121818482-11beb580-cc90-11eb-9f26-669af0c1cf42.png)

**Comment by christykobyletska** [comment]
Also deleted link from the documents for Regional Board.

**Comment by christykobyletska** [comment]
and for Governing Body.
