### ISSUE TITLE
[Login Page]  Profile data is still displayed on the login page if you do not log out of the system and just go to any other link and then return to the site of Plast

### ISSUE THREAD

**Issue by OStetsevich** [ita-social-projects/EPlast#1368]
**Environment:** Windows 10, 64 bit. Google Chrome 90.0.4430.212
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/EPlast/commit/681db9019a1c54d6646d9d77fab70114cc3039c8

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the application as a curent member of Plast

**Steps to reproduce**
1. Go to any other URL without logging out of he system
2. Turn back to https://eplast.westeurope.cloudapp.azure.com

**Actual result**
![LoginForm](https://user-images.githubusercontent.com/85349049/123911032-ede3bb00-d983-11eb-86e7-3e3705e5b7b5.png)

**Expected result**
![LoginFormExpected](https://user-images.githubusercontent.com/85349049/123911165-18357880-d984-11eb-9937-e1c855eecf14.png)

**Comment by Oleksii-Zh** [comment]
The defect successfully fixed. Should be moved to "Done"
