### ISSUE TITLE
[Annual reports' input fields] allow user to type letters in [digits' input fields]

### ISSUE THREAD

**Issue by irashakh** [ita-social-projects/EPlast#1381]
**Environment:** macOS Big Sur, Safari 14.1.1 
**Reproducible:** always
**Build found:**  67c9c2b

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the application as an admin 

**Steps to reproduce**
1. Go to 'Звітування та Статистика' 
2. Click on 'Річні Звіти' page
3. Click on 'Подати річний звіт станиці'
4. Choose any 'Станиця' (ex. 'Турка')
5. Set data in input fields 
6. Set data ( letters) in input fields where must be digits
7. Press 'Подати річний звіт'

**Actual result**
Input fields (where must be digits) are filled with data (letters)

**Expected result**
Input fields (where must be digits) cannot contain letters, and shouldn't let user type letters

![річний звіт](https://user-images.githubusercontent.com/85729818/124123394-f1f50300-da7f-11eb-9b39-25826731dc95.png)

**Comment by solomiiatarnavska** [comment]
Unfortunately, this bus reproduces on Safari (MacOs environment)
During typing wrong data no error message appears
It appears only after pressing 'Подати річний звіт' button (at the end of a Report creation)
![Screenshot at Sep 26 19-31-44](https://user-images.githubusercontent.com/79641118/134816173-fd7d4364-8a10-4d42-8997-8038d611ea8b.png)
![Screenshot at Sep 26 19-33-44](https://user-images.githubusercontent.com/79641118/134816174-abbd375d-bc45-41b1-abe3-6e02b70e462b.png)
