### ISSUE TITLE
[User filters ] Users filter doen't work in 'Таблиця користувачів'

### ISSUE THREAD

**Issue by OleksiiLiapin** [ita-social-projects/EPlast#1384]
**Environment:** all browsers
**Reproducible:** always
**Build found:** 63d148d

**Preconditions**
1. Login as user with the rights to see 'Таблиця користувачів'

**Steps to reproduce**
1. Go to 'Таблиця користувачів'
2. Choose in the filter Курінь 'Степові відьми' 
3. Click 'OK' button => filter applied
3. Delete selected Курінь from the filter form
4. Choose in the filter Курінь 'Велике плем'я лісових чортів'
5.  Click 'OK' button

**Actual result**
There are the same users from 'Степові відьми' in the table

Comment:
The same bug occurs when I try to filter 'Станиці' with no users in it. 

**Expected result**
Users from the Курінь 'Велике плем'я лісових чортів' should be in the table
![filter error](https://user-images.githubusercontent.com/49100107/124141008-ae0af980-da91-11eb-92fb-47eefcfe3e16.png)
![Округи](https://user-images.githubusercontent.com/49100107/124141772-58831c80-da92-11eb-82b2-266dae4df940.png)

**Comment by solomiiatarnavska** [comment]
Hi!
Actually, it really works. But I guess it would be better to add the possibility to refresh (clean or delete) information after pressing X button in the filter line.
Please see attached screens below for more detailed info.
Thanks!
![Screenshot at Jul 15 18-07-43](https://user-images.githubusercontent.com/79641118/125811665-91be6e15-2e53-4e35-a51b-3bb386e6080d.png)
![Screenshot at Jul 15 18-08-56](https://user-images.githubusercontent.com/79641118/125811675-b30ab0f0-9b92-4a57-9c01-7260e2390bcf.png)
