### ISSUE TITLE
[Decision] button 'Видалити файл' isn't aligned 

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1406]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: high
**Severity**: medium
**Build found**: c003ad3

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Go to the upper left side of the main page and choose 'Рішення' section
2.Open it
3.Click on 'Додати рішення' section 
4.Download any document you want and pay attention on 'Видалити файл' button (see attached screen below)

**Actual result**
The button is not aligned 

**Expected result**
The button should be aligned

**User story and test case links**
![Screenshot at Jul 04 23-00-49](https://user-images.githubusercontent.com/79641118/124397963-e02f8c00-dd1b-11eb-8825-69ed6123cd9c.png)

**Comment by christykobyletska** [comment]
Such bug was in Repository as well.
