### ISSUE TITLE
[Notifications] User with a particular role does not receive a notification when Admin assign another user for this role

### ISSUE THREAD

**Issue by Tania-Volovetska** [ita-social-projects/EPlast#1407]
Environment: Windows 7, 32 bit. Google Chrome 91.0.4472.114
Reproducible: always
Priority: medium
Severity: low
Build found: c003ad3

Preconditions
The user (e.g 'Прихильник Станиці') was assigned a 'Писар' role by Super Admin and then Admin assigns another user for this role.

Steps to reproduce

1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log in to the application as an Adherent 
3. Click on 'Notifications' (a 'bell'-icon in the top right corner of any page)
4. Pay attention to the notifications displayed.

Actual result
The notification about ending 'Писар' role does not appear.
![image](https://user-images.githubusercontent.com/3681311/124402549-948bdb00-dd39-11eb-9123-a174be794070.png)
![image](https://user-images.githubusercontent.com/3681311/124402560-ad948c00-dd39-11eb-9169-3bf9e5db8ac7.png)

Expected result
The notification about ending 'Писар' role appears.

**Comment by OlgaShtogryn** [comment]
![124](https://user-images.githubusercontent.com/87722808/128245716-a526d607-bae9-48a4-92b6-d210b524f9a3.png)
![125](https://user-images.githubusercontent.com/87722808/128245719-b94467e8-6494-4187-b280-da48af2f9a95.png)
