### ISSUE TITLE
[Репозиторій] As the City Admin, I can delete any document in the repository

### ISSUE THREAD

**Issue by OStetsevich** [ita-social-projects/EPlast#1415]
**Environment:** Windows 10, 64 bit. Google Chrome 90.0.4430.212
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/EPlast/commit/838d32642245a586ece6874757fef2546b820221

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the application as City Admin of Plast

**Steps to reproduce**
1. Go to 'Меню'
2. Click on 'Репозитарій'
3. Right-click on any document of 'Репзитарій'

**Actual result**
![delete_document](https://user-images.githubusercontent.com/85349049/124561347-752ea400-de46-11eb-8ddd-2aeb3faa8438.png)

**Expected result**
I should not have the ability to delete documents from Repository

**Comment by christykobyletska** [comment]
https://github.com/ita-social-projects/EPlast/issues/1287 similar bug
