### ISSUE TITLE
Dropdown with unknown data appears in modal window when forwarding  'Станиці-члени' to another [Округа]

### ISSUE THREAD

**Issue by irashakh** [ita-social-projects/EPlast#1438]
**Environment:** macOS Big Sur, Safari 14.1.1
**Reproducible:** always (first 3 seconds)

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the application as an admin 
[Округа] has to have [Станиця] and members in [Провід Округи]

**Steps to reproduce**
1. Go to [Округи]
2. Choose [Округа] (ex. '123')
3. Сlick on 'Видалити округу' 
4. Сlick on 'Так, видалити'
5. Сlick on dropdown menu

**Actual result**
Dropdown with unknown data appears in modal window when deleting [Округа]

**Expected result**
Correct data in dropdown should appear

![delete  округа](https://user-images.githubusercontent.com/85729818/124957402-b7600d00-e021-11eb-94e1-c6a16873055f.png)

Duplicated
https://github.com/ita-social-projects/EPlast/projects/1#card-64611526

**Comment by christykobyletska** [comment]
https://github.com/ita-social-projects/EPlast/issues/1435 the same bug
