### ISSUE TITLE
[City ​​statistics] After minimizing browser window City Admin is not able to view all information of Statistic report

### ISSUE THREAD

**Issue by olesiakhrushch** [ita-social-projects/EPlast#1439]
**Environment:**  Windows 10, Chrome 91.0.4472.101.
**Reproducible:** always.
**Priority:** medium.
**Severity:** low.
**Build found:** 0e0ef88

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log in as a City Admin.
3. Minimize the browser window

**Steps to reproduce**

1. Go to Main Menu
2. Click on 'Звітування та статистика'
3. Click on 'Cтатистика'
4. Click on 'Статистика станиць'
5. Choose any city in the 'Станиці' field
6. Choose any year in the 'Роки' field
7. Choose any indications in the "Показники" field
8. Click the "Сформувати" button

**Actual result**
Indicators "№", "Рік", "Округа", "Станиця" are fixed and after scrolling the "indicators" window is hidden and a City Admin does not see the information in it. 
![Screenshot_4](https://user-images.githubusercontent.com/84467235/124957581-e9716f00-e021-11eb-988c-b9b32d45ef4f.png)

**Expected result**
A City Admin should be able to view all information in a smaller browser window.

**User story and test case links**
https://github.com/ita-social-projects/EPlast/issues/1024
https://github.com/ita-social-projects/EPlast/issues/1025

**Comment by NataliyaDominyuk** [comment]
![statistics](https://user-images.githubusercontent.com/104838173/170097065-26a1119d-0e98-4375-8d9f-21b2e0eb2659.jpg)

**Comment by NataliyaDominyuk** [comment]
![image](https://user-images.githubusercontent.com/104838173/172333345-e8887f34-5dc9-4a7e-913d-78c76a1aa394.png)

**Comment by NataliyaDominyuk** [comment]
Still not fixed
