### ISSUE TITLE
[Regions] The search functionality doesn't work properly when searching regions for forwarding 'Станиці-члени'

### ISSUE THREAD

**Issue by ksapiha** [ita-social-projects/EPlast#1449]
**Environment:** Windows 10, Chrome Version 91.0.4472.124 (Official Build) (64-bit)
**Reproducible:** always
**Priority:** medium
**Severity:** low

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log into the application as an admin 
3. 'Округа' has to have at least one member in 'Члени округи'

**Steps to reproduce**
1. In the left-side menu click 'Довідник' and select 'Округи'
2. Search for a region to be deleted (e.g. 'My region')
3. Сlick the 'Видалити округу' button
4. Confirm the deletion by clicking the 'Так, видалити' button
5. Search for the region you want to move your 'Станиці-члени' by typing the first letter of a region (e.g. 'ч')

**Actual result**
The system suggests regions that don't contain a typed letter (e.g. 'ч')
![image](https://user-images.githubusercontent.com/85742321/125460412-fa5c6550-c3e0-4607-8be3-f8b3352f7324.png)

**Expected result**
The system should suggest regions that contain a typed letter (e.g. 'ч' - 'Чернівецька')

**Comment by solomiiatarnavska** [comment]
This bug isn't reproducible anymore since we have a new functionality that has been developed there (see the screen below)
![Screenshot at Sep 12 18-53-46](https://user-images.githubusercontent.com/79641118/132994335-6d2cbecb-fe0c-493d-9db0-2e4e8d7aed2b.png)
