### ISSUE TITLE
[Decision] The maximum number of characters has to be set for 'Тема рішення' and 'Текст рішення'

### ISSUE THREAD

**Issue by ksapiha** [ita-social-projects/EPlast#1453]
**Environment:** Windows 10, Chrome Version 91.0.4472.124 (Official Build) (64-bit)
**Reproducible:** always
**Priority:** medium
**Severity:** medium

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log into the application as an admin 

**Steps to reproduce**
1. Go to the left-side menu and select 'Рішення'
2. Click the 'Додати рішення' button
3. Type more than 255 characters in the 'Тема рішення' text field
4. Type more than 1000 characters in the 'Текст рішення' text field
5. Observe the result

**Actual result**
A user can type more than 255 characters for 'Тема рішення' and more than 1000 characters for 'Текст рішення'.
No error message about the limit of characters is displayed
![image](https://user-images.githubusercontent.com/85742321/125625555-10566dc9-f68b-4999-9a61-f5c31d4b9523.png)

**Expected result**
A user **can't** type more than 255 characters for 'Тема рішення' and more than 1000 characters for 'Текст рішення'.
In case the text is above the limit, the error message 'Максимальна довжина - 255 символів' or 'Максимальна довжина - 1000 символів' respectively is displayed

**User story links**
User story #1248

**Comment by solomiiatarnavska** [comment]
The maximum number of items in "Тема рішень" is **255**.
![Screenshot at Aug 02 07-41-44](https://user-images.githubusercontent.com/79641118/127805196-59616563-63e9-4cb0-a19e-bc505172f697.png)
