### ISSUE TITLE
[Decisions] A major part of a large text under 'Рішення' has to be hidden

### ISSUE THREAD

**Issue by ksapiha** [ita-social-projects/EPlast#1455]
**Environment:** Windows 10, Chrome Version 91.0.4472.124 (Official Build) (64-bit)
**Reproducible:** always
**Priority:** medium
**Severity:** low

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log into the application as an admin 
3. A decision with up to 1000 characters in a 'Текст рішення' text field is created

**Steps to reproduce**
1. Go to the left-side menu and select 'Рішення'
2. On the 'Рішення керівних оргінів' page look for the decision with up to 1000 under 'Рішення'
3. Observe the result

**Actual result**
The whole text under 'Рішення' is displayed on the page
![image](https://user-images.githubusercontent.com/85742321/125677117-68516708-b1f0-4d57-aeb2-9baa18bf8913.png)

**Expected result**
The major part of a large text in 'Рішення' field should be hidden

**Comment by olesiakhrushch** [comment]
T
![Screenshot_58](https://user-images.githubusercontent.com/84467235/126603314-6f795a08-513b-4a5e-b86c-c12b2ee41fd9.png)
The infotip is fixed to the text and is partially hidden when scrolling down.

**Comment by christykobyletska** [comment]
the same thing is on repository page, "Короткий зміст" column  
![image](https://user-images.githubusercontent.com/25940952/127693163-092e8f80-a69f-40d4-8b88-df780e1cc1e3.png)
