### ISSUE TITLE
Sorting arrows aren't horizontally aligned on [Таблиця Користувачів]

### ISSUE THREAD

**Issue by irashakh** [ita-social-projects/EPlast#1459]
**Environment:** macOS Big Sur, Safari 14.1.1
**Reproducible:** always

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the application as an admin 

**Steps to reproduce**
1. Go to 'Довідник'
2. Click on 'Таблиця Користувачів'

**Actual result**
Sorting arrows aren't horizontally aligned on [Таблиця Користувачів]

**Expected result**
Sorting arrows must be horizontally aligned on [Таблиця Користувачів]

![Таблиця користувачів](https://user-images.githubusercontent.com/85729818/125789013-7cd72531-45c7-4f4a-a5f6-8abe3a248719.png)

**Comment by NataliyaDominyuk** [comment]
Sorting arrows are still not aligned in 'Date of Birth' column
![date of birth](https://user-images.githubusercontent.com/104838173/169847525-05f6471b-2fbe-4309-9692-bf6586628322.jpg)
