### ISSUE TITLE
Login context menu changes position depending on current scroll position

### ISSUE THREAD

**Issue by ylozynska** [ita-social-projects/EPlast#1481]
**Environment:** Windows 7 (32-bit), Firefox 89.0.2 (32-біт)
**Reproducible:** always
**Build found:** 364406c
**Priority:** minor
**Severity:** minor

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin

**Steps to reproduce**
1.	Click on 'Діловодства'
2.	Scroll to the end of the page 
3.	Click on "Привіт, Княгиня!" in the upper menu bar
4.	Pay attention to display the context menu  

**Actual result**
The context menu is displayed in different parts of the screen

**Expected result**
The context menu should be displayed in the upper menu bar
![1](https://user-images.githubusercontent.com/85739384/126142187-aa0d962c-a789-4a7c-ac4e-bda30689b132.jpg)

**Comment by ZoryanaKravchuk** [comment]
**Look this issue** [Profile] [Mobile] [Android] The drop-down menu changes its location. #1495
**Actual result**
A drop-down menu appears near the user menu but then jumps in the left corner.
![photo_2021-07-19_19-26-30 (5)](https://user-images.githubusercontent.com/84467235/126458394-0419c4c9-6e4f-4b50-ad2f-47999a3affba.jpg)
**Expected result**
A drop-down menu should appear near the user menu.
