### ISSUE TITLE
[Profile/Blank] 'Заступник Голови куреня' should have a possibility to modify the documents under 'Бланки' for users from the same hovel

### ISSUE THREAD

**Issue by ksapiha** [ita-social-projects/EPlast#1486]
**Environment:** Windows 10, Chrome Version 91.0.4472.124 (Official Build) (64-bit)
**Reproducible:** always
**Priority:** high
**Severity:** medium

**Preconditions**
Log in to https://eplast.westeurope.cloudapp.azure.com as a 'Заступник Голови куреня' (e.g. 'Літавиці')

**Steps to reproduce**
1. Go to the 'Таблиця користувачів' page;
2. Right-click a user that belongs the same hovel as 'Заступник Голови куреня' (e.g. 'Літавиці')
3. Select 'Переглянути профіль' option;
4. At profile page, select the 'Бланки' tab;
5. Observe the result

**Actual result**
'Заступник Голови куреня' doesn't have a possibility to view/download the 'Життєпис'; to add/delete/download/view the 'Виписка з УПЮ'; to add the 'Досягнення'; to generate the 'Заява для вступу' for users from the same hovel
![image](https://user-images.githubusercontent.com/85742321/126196726-25bfc15f-4f62-4c60-81c8-9414dc706f69.png)

**Expected result**
'Заступник Голови куреня' should have a possibility to view/download the 'Життєпис'; to add/delete/download/view the 'Виписка з УПЮ'; to add the 'Досягнення'; to generate the 'Заява для вступу' for users from the same hovel
![image](https://user-images.githubusercontent.com/85742321/126197212-574cb28f-9916-4726-b0b3-67c0bfd52f02.png)

**Comment by christykobyletska** [comment]
fixed also for City and Region Head Deputies.
