### ISSUE TITLE
[Decisions] [Governing Bodies][Mobile] [Android] Infotip is displayed after clicking on "Крайовий Провід Пласту" і "Рішення"

### ISSUE THREAD

**Issue by olesiakhrushch** [ita-social-projects/EPlast#1488]
**Environment:** Android 11, Chrome 91.0.4472.120.
**Reproducible:** always.
**Priority:** low
**Severity:** low
**Build found:**  364406c

**Steps to reproduce**

1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log in to the system as Super Admin
3. Go to 'Крайовий Провід Пласту'

**Actual result**
After clicking on "Крайовий Провід Пласту" infotip is displayed

![photo_2021-07-19_19-26-30 (4)](https://user-images.githubusercontent.com/84467235/126205276-45850cc8-c4a0-4789-8524-9c7783469b11.jpg)

**Expected result**
After clicking on "Крайовий Провід Пласту" should be open "Крайовий Провід Пласту" page without any infotips.

4. Go to 'Рішення'

**Actual result**
After clicking on "Рішення" infotip is displayed.
![photo_2021-07-19_19-26-30 (3)](https://user-images.githubusercontent.com/84467235/126211612-b6bda552-a84f-4003-9553-46060c858c47.jpg)

**Expected result**
After clicking on "Рішення" should be open "Рішення керівних органів" page without any infotips.

**Comment by christykobyletska** [comment]
the same on "Про базу"
