### ISSUE TITLE
[Mobile] Mobile layout is broken for Profile page

### ISSUE THREAD

**Issue by olesiakhrushch** [ita-social-projects/EPlast#1495]
**Environment:** Android 11, Chrome 91.0.4472.120.
**Reproducible:** always.
**Priority:** low
**Severity:** low
**Build found:** a7a4326

**Preconditions**

1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log into the system as any user.

**Steps to reproduce**

1. Click on '...' near the notification icon.
2. Click on the user name.
3. Pay attention to the drop-down menu.

**Actual result**
A drop-down menu appears near the user menu but then jumps in the left corner.

![photo_2021-07-19_19-26-30 (5)](https://user-images.githubusercontent.com/84467235/126458394-0419c4c9-6e4f-4b50-ad2f-47999a3affba.jpg)

**Expected result**
A drop-down menu should appear near the user menu.

**Comment by ZoryanaKravchuk** [comment]
**Also, look issue:    [User profile] Wrong label color on the button "Діловодства", "Події", "Бланки", "Поручення" #1579**

**Steps to reproduce**

Open User
Click on the three dots button in the right corner near "Дійсне членство"

**Actual result**
Black label on the button "Діловодства", "Події", "Бланки", "Поручення"
![Screenshot_2021-08-03-23-30-32-666_com.android.chrome.jpg](https://user-images.githubusercontent.com/50516451/128203108-456d889b-6a32-4d7c-b379-680dc81ed726.jpg)

**Expected result**
White label on the button "Діловодства", "Події", "Бланки", "Поручення"

**Comment by ZoryanaKravchuk** [comment]
**Look issue:   [Profile] [Mobile] The line offset of the fields name is too small #1761**

**Steps to reproduce**

1.Go to https://eplast.westeurope.cloudapp.azure.com/
2.Click the "..." button
3.Click the "Редагувати профіль"
4.Scroll down to profile information fields

**Actual result**
The line offset of the fields name is too small
![profile](https://user-images.githubusercontent.com/59814492/132602514-f50d9075-407e-4c83-b0d4-170f0c16e53a.jpg)


**Expected result**
There is enough line offset of the fields name
