### ISSUE TITLE
[Events/Події] Empty fields in the form ‘Редагувати подію’, if change any administrative role and save the event

### ISSUE THREAD

**Issue by ylozynska** [ita-social-projects/EPlast#1501]
**Environment:** Windows 7 (32-bit), Firefox 89.0.2 (32-біт)
**Reproducible:** always
**Build found:** d7c14fc
**Priority:** Medium
**Severity:** Low

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as  a Super Admin

**Steps to reproduce**
1.	Click on menu item ‘Довідник’
2.	Click on section 'Події'
3.	Choose type of ‘Events’-“Акція”
4.	Choose type of ‘Категорії’- “Інструкторський вишкіл”
5.	Choose “Подія для тесту”
6.	Click on ‘Редагувати’
7.	Change any administrative role (“Комендант”, “Заступник коменданта”, “Бунчужний”, “Писар”)
8.	Click on ‘Зберегти подію’
9.	Click on ‘Редагувати’
10.	Pay attention, the form of ‘Редагувати подію’ is empty

**Actual result**
All fields of ‘Редагувати подію’ form is empty

**Expected result**
All fields of ‘Редагувати подію’ form should be filled
![всі поля порожні](https://user-images.githubusercontent.com/85739384/126624241-b1635765-1d6b-452d-b0ff-a16b588de25b.jpg)

**Comment by setorianadya** [comment]
Bug still reproduces and the same bug when we edit event from the user page. 
**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log in.
Your user has created events
**Steps to reproduce:**
1. Open your user page
2. Choose "Події"
3. Press the button "Список"
4. Press button "Редагувати"
5. Change any admin and press button "Зберегти"
6. Press button "Редагувати" again

**Comment by setorianadya** [comment]
When we deleted few users (4), and they were admins in few events these events remained in list of events and nobody can edit them, even Super Admin.
