### ISSUE TITLE
[Річні звіти/ Annual reports] “Заступник Голови Округи” has not possible to create the “Річний звіт округи”

### ISSUE THREAD

**Issue by ylozynska** [ita-social-projects/EPlast#1509]
**Environment:** Windows 7 (32-bit), Firefox 89.0.2 (32-біт)
**Reproducible:** always
**Build found:** d7c14fc
**Priority:** Medium
**Severity:** Low

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as  “Заступник Голови Округи” 

**Steps to reproduce**
1.	Click on “Річні звіти” menu item
2.	Pay attention, it is not possible to create the “Річний звіт округи”

**Actual result**
There is no possibility to create the “Річний звіт округи”
![річні звіти2](https://user-images.githubusercontent.com/85739384/126830234-7ab7f0d9-7930-4b51-bec0-dd862d061829.jpg)

**Expected result**
Should be possible to create the “Річний звіт округи”

![річні звіти1](https://user-images.githubusercontent.com/85739384/126830249-3018ee70-7a2a-4cbc-9032-67f00837bf0d.jpg)

**Comment by christykobyletska** [comment]
fixed also for City and Region Head Deputies.
