### ISSUE TITLE
[Repository/Репозитарій] “Заступник Голови Округи” has not possible to add the document

### ISSUE THREAD

**Issue by ylozynska** [ita-social-projects/EPlast#1510]
**Environment:** Windows 7 (32-bit), Firefox 89.0.2 (32-біт)
**Reproducible:** always
**Build found:** d7c14fc
**Priority:** Medium
**Severity:** Low

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as  “Заступник Голови Округи”

**Steps to reproduce**

1.	Click on “Репозитарій” menu item
2.	Pay attention, it is not possible to add the document

**Actual result**
There is no possibility to add the document
![репозитарій1](https://user-images.githubusercontent.com/85739384/126831722-82344f38-bb40-44a4-b85f-ef3bd5d3fb10.jpg)

**Expected result**

Should be possible to add the document
![репозитарій2](https://user-images.githubusercontent.com/85739384/126831730-7812841b-2ca5-4520-a39d-42376951d903.jpg)

**Comment by christykobyletska** [comment]
fixed also for City and Region Head Deputies.
