### ISSUE TITLE
[City / village – станиця] Spaces are allowed when creating a new city/village

### ISSUE THREAD

**Issue by OlenaMazepa** [ita-social-projects/EPlast#1538]
**Environment:** Windows 10 Pro, Google Chrome Version 92.0.4515.107 (64-bit).
**Reproducible:** always
**Priority** minor
**Severity** low
**Build found:** 966d4f6

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as super admin

**Steps to reproduce**
1.	Go to 'Станиці'
2.	Click on 'Створити нову станицю'
3.	Enter spaces into ‘Назва’, ‘Вулиця’, ‘Номер офісу/квартири’, ‘Номер будинку’ fields
4.	Enter valid data in ‘Округа’ ‘Поштовий індекс’ fields

**Actual result**
New city is created.

**Expected result**
New city should not be created.

**Note:** This defect reproduce also when create New Country (Округу) and New Hovel (Курінь).

**Comment by setorianadya** [comment]
Bug reproduce with Postman. Also, we can add numbers in the field name.
{
    "userId": "a84473c3-140b-4cae-ac80-b7cd5759d3b5",
    "appeal": "12345",
    "cityName": "89", or " "
    "regionId": 106,
    "street": "М. ПАВЛИКА",
    "houseNumber": "10",
    "officeNumber": "1",
    "postIndex": "66666",
    "cityURL": "Радехів",
    "email": "setorianadya@gmail.com",
    "phoneNumber": "+380(66)-666-66-66"
}

**Comment by setorianadya** [comment]
The same for regions -Bug reproduces with Postman. Also, we can add numbers in the field name.
{
    "id": 0,
    "regionName": "100", or " "
    "phoneNumber": "+380(66)-666-65-77",
    "email": "setorianadya@gmail.com",
    "street": "М. ПАВЛИКА",
    "houseNumber": "10",
    "officeNumber": "1",
    "postIndex": "33333",
    "city": "Радехів",
    "isActive": true
}

**Comment by setorianadya** [comment]
Bearer token was for Super admin
