### ISSUE TITLE
[Hovels] System allows to appoint an Adherent on role "Голова куреня/Заступник куреня"

### ISSUE THREAD

**Issue by olesiakhrushch** [ita-social-projects/EPlast#1557]
**Environment:** Windows 10, Chrome 91.0.4472.101.
**Reproducible:** always.
**Priority:** major.
**Severity:** medium.
**Build found:** dac65d1

**Preconditions**

1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log in as Hovel Admin

**Steps to reproduce**
1. Go to your Hovel
2. Click on '+' icon in "Провід куреня" window
3. Choose any user who has a role Adherent (e.g. "Прихильник Хрущ")
4. Choose "Тип адміністрування" - "Голова куреня/Заступник голови куреня"
5. Click the "Опублікувати" button

**Actual result**
Adherent is appointed on role "Голова куреня/Заступник куреня"

![Screenshot_16](https://user-images.githubusercontent.com/84467235/128025882-a389edad-1c79-4949-a624-b0dbe25c329f.png)
![Screenshot_17](https://user-images.githubusercontent.com/84467235/128025884-7b2e5d55-d68d-4fe5-ba07-433b6cfb8926.png)

**Expected result**
Adherent cannot be "Голова куреня/Заступник голови куреня" only "Діловод"

**Comment by setorianadya** [comment]
Almost the same - [Hovel Admin] Hovel Admin is able to provide an administrative role for Adherent of Hovel #1586

**Comment by setorianadya** [comment]
Almost the same - [Hovel/User Table] Former member steal in "Провід Куреня" #1689. Look also at this bug, please

**Comment by setorianadya** [comment]
Almost the same - [API/Hovels] We can add any user in "Провід куреня" even if this user isn`t in the hovel #1674. Look also at this bug, please

**Comment by setorianadya** [comment]
Almost the same - [Access Levels] The same user shouldn't be "Голова куреня" and "Заступник голови куреня" at the same time. #1387 Look also at this bug, please
