### ISSUE TITLE
[Hovels/Документообіг] Dropdown list is moved down when chosen option has long text

### ISSUE THREAD

**Issue by yuliianedomirko** [ita-social-projects/EPlast#1560]
**Environment:** Windows 7, Google Chrome v. 92.0.4515.107
**Reproducible:** always
**Priority:** low
**Severity:** low
**Build found:** 33abc36

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log in as a Super Admin

**Steps to reproduce**
1. Go to 'Довідник/Курені'
2. Click on any 'Курінь'
3. Click on "+" sign in "Документообіг куреня" section
4. Choose "Протокол сходин Старшої Пластової Старшини" for "Тип документу"
 
**Actual result**
Dropdown list is moved down, text is fully displayed.

**Expected result**
Dropdown list is aligned with "Тип документу", text is not fully displayed.

![moved dropdown list](https://user-images.githubusercontent.com/87977724/128047293-644933a4-0622-4cef-8e3f-bbc37b46669c.PNG)

**Comment by christykobyletska** [comment]
https://github.com/ita-social-projects/EPlast/issues/1545
