### ISSUE TITLE
Unable to open in new tab any link in side menu

### ISSUE THREAD

**Issue by RuslanaOsypchuk** [ita-social-projects/EPlast#1566]
User should be able to open any option from main menu in a new browser tab clicking on the right mouse button
![Безымянный](https://user-images.githubusercontent.com/87931481/128058144-a52a3d49-57ea-43e2-8797-c912a4777607.png)

**Comment by tvardero** [comment]
Bug is due to using `<Buttons>` instead of `<Link>`.
Buttons do not provide option to user to open link in a new tab. Thus, there's no option in context menu on RMB click.
