### ISSUE TITLE
[User profile] Wrong label color on the button "Діловодства", "Події", "Бланки", "Поручення"

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1579]
**Environment:** Mi Note3MIUI Global 12.0.1 Стабільна збірка, Версія Android 9 PKQ1.181007.001, Google Chrome 92.0.4515.107
**Reproducible:** always
**Priority:** medium
**Severity:** major
**Build found:** d532992

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log in.

**Steps to reproduce**

1. Open User
2. Click on the three dots button in the right corner near "Дійсне членство"

**Actual result**
Black label on the button "Діловодства", "Події", "Бланки", "Поручення"
![Screenshot_2021-08-03-23-30-32-666_com.android.chrome.jpg](https://user-images.githubusercontent.com/50516451/128203108-456d889b-6a32-4d7c-b379-680dc81ed726.jpg)
**Expected result**
White label on the button "Діловодства", "Події", "Бланки", "Поручення"

**Comment by christykobyletska** [comment]
Please, attach a screenshot of what you mean by this bug

**Comment by setorianadya** [comment]
Done
