### ISSUE TITLE
[annual reports] the deputy of a hovel admin couldn't see 'annual reports' page

### ISSUE THREAD

**Issue by stasivanets** [ita-social-projects/EPlast#1593]
Environment: windows 10 pro x64, google chrome v 92.0.4515.107 (Official Build) (64-bit)
Reproducible: always
Priority: High
Severity: Low
Build found: 0f57616

Preconditions:
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as the deputy of a hovel admin ("заступник голови куреня").

Steps to reproduce

1. Go to 'left-side menu'.

Actual result:
the deputy of a hovel admin couldn't see the 'annual reports' button in 'left-side menu'.

![128061212-a8c389d1-9070-4806-b2ca-12fd04ba6530](https://user-images.githubusercontent.com/87824785/128468793-97d4f2db-bb3e-4a01-9804-a9faab15d5d5.jpg)

![EPlast - Google Chrome 06 08 2021 9_54_06](https://user-images.githubusercontent.com/87824785/128469176-df262425-5cc1-43b6-98a9-a6b484766237.png)

Expected result
the deputy of a hovel admin could see only 'annual reports' button in 'left-side menu' as he has the same access rights as a hovel admin.

![128061476-4d1fe44f-b74f-4efc-a743-76bdbe1e1bf8](https://user-images.githubusercontent.com/87824785/128469354-a317d775-a2ce-4ca2-b42a-ecec44fc81ec.png)

**Comment by VSBalanchuk** [comment]
Duplicate #1567
