### ISSUE TITLE
[Deputy of Region Admin] The needed member of region can't be chosen as a Deputy of Region Admin before the Region Admin isn't chosen for this position.

### ISSUE THREAD

**Issue by OlgaShtogryn** [ita-social-projects/EPlast#1602]
**Environment:** Windows 10, Mozilla Firefox 90.0.2.
**Reproducible:** always.
**Priority:** high.
**Severity:** major.
**Build found:** 0f57616

**Preconditions**

1.   Go to https://eplast.westeurope.cloudapp.azure.com
2.   Log in as a Super Admin.

**Steps to reproduce**

1. Go to Main Menu.
2. Click on 'Округи'.
3. Click on any region (e.g. 'Львівська').
4. Choose some member of region for Region Admin position.
5. Choose another member of region for Deputy of Region Admin position.
6. Click on 'Більше' button and check that these two members are added to the board of region.
7. Choose the member of region from step 4 for Deputy of Region Admin position.
8. Pay attention that one member of region is chosen for Region Admin and his Deputy positions.
9. Choose the member of region  from step 5  for Deputy of Region Admin position.
10. Click 'Гаразд' on pop-up window and check that this member is chosen  for Deputy of Region Admin position.

**Actual result**
The one person was chosen for Region Admin and his Deputy positions and only after that we could choose the needed member of region for Deputy of Region Admin position.

https://user-images.githubusercontent.com/87722808/128759110-4b622d08-2b64-410a-bb77-27beff6be19d.mp4
**Expected result**
The one person should be chosen for Region Admin and his Deputy positions, and  we can choose the needed member of region for Deputy of Region Admin position from the first time.

**Comment by solomiiatarnavska** [comment]
This bug isn't reproducible anymore. Now we can add Deputy of Region Admin before Region Admin has been chosen.
