### ISSUE TITLE
[Regions] Modal window does not appear when Region admin deletes document from "Документообіг округи"

### ISSUE THREAD

**Issue by yuliianedomirko** [ita-social-projects/EPlast#1605]
**Environment:** Windows 7, Google Chrome v. 92.0.4515.107
**Reproducible:** always
**Priority:** medium
**Severity:** low
**Build found:** 0f57616

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log in as a Region Admin (  e.g. login: okrygglava@mail.com , password: Qwerty1)  - Хмельницька округа )

**Steps to reproduce**
1. Go to "Довідник/Округи"
2. Choose "Хмельницька округа"
3. Click on "Більше" button in "Документообіг округи"
4. Click on delete icon on "Test" document
 
**Actual result**
"Test" document is deleted

**Expected result**
Modal window appears: "Ви впевнені, що хочете видалити даний документ з документообігу? Так, видалити/Скасувати"

**Comment by christykobyletska** [comment]
also done for city/hovels  "Документообіг"
