### ISSUE TITLE
[Decision] [Precaution] [Award] [Senior Staff] remains the previously entered data

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1627]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: medium
**Severity**: low
**Build found**: feabd1e

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Go to the left-side menu and open 'Рішення' page
2.Click on 'Додати рішення' and fulfill one field (see attached screen below) and press Exit (X button). _Do not_ press 'Зберегти' button.
3.In Search field type 'Спеціалізація' and press OK (Search), afterward press Exit (X button) (see attached screen below)
4.Click on 'Додати рішення' field one more time and pay attention on a form
5.Repeat the same steps 1-4 but on 'Відзначення', 'Перестороги' and ' Кадра виховників' functionality (for more datalied info please attached videos below)

**Actual result**
The previously entered data remains in a field despite other thing have been done with definitely other functionality (see attached screen below). 

It does not depend on the amount of entered data, you may fulfill all necessary fields or might fulfill only one field -- it does not matter. All entered information remains.

**Expected result**
After clicking on X button or Exit all entered previously information should be deleted (as "Зберегти" button _has not_ been clicked on)

**User story and test case links**
![Screenshot at Aug 12 11-58-05](https://user-images.githubusercontent.com/79641118/129170928-b402732f-29a9-4a0d-85e3-c4ed987fb44d.png)
![Screenshot at Aug 12 12-00-13](https://user-images.githubusercontent.com/79641118/129170936-08353336-a030-4a23-b00d-31f1ea77db65.png)
![Screenshot at Aug 12 12-07-27](https://user-images.githubusercontent.com/79641118/129170937-c2238254-607d-4c01-b354-8d9bd0e5c779.png)

https://user-images.githubusercontent.com/79641118/129173097-51015f6b-6954-49cd-8609-1a2944eb2aa2.mp4

https://user-images.githubusercontent.com/79641118/129173455-b2f4b042-4da5-4398-a278-ef9e92b060ea.mp4

https://user-images.githubusercontent.com/79641118/129178218-c39a26e5-bf6c-4a55-bf5f-bce2d14163b6.mp4

**Comment by NatalyMinziuk** [comment]
It`s not a bug but feature

**Comment by solomiiatarnavska** [comment]
We still have this issue only in the [Precaution] section.
But if it's a feature -- let it be :) I'll move it to the [Done] section.
