### ISSUE TITLE
[Regions] We can`t make a region if we have a region with the same name

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1633]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always.
**Priority:** high.
**Severity:** major.
**Build found:** b933a65

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as admin.

**Steps to reproduce**

1. Go to the "Округи"
2. Choose "Створити округу"
3. Make new region with any old name (e. g Черкаська, Харківська, Львів)
4. Fill in all required fields
5. Press button "Підтвердити"

**Actual result**
We can`t make a region if we have a region with the same name
![image](https://user-images.githubusercontent.com/50516451/129197097-dba4aeb5-b9a0-48d4-ba6a-6da4d3108d9d.png)

**Expected result**
We can make regions with the same names (Cities can have the same names).

**Comment by setorianadya** [comment]
And we can`t edit regions

**Comment by setorianadya** [comment]
And we can`t make region with original name
![image](https://user-images.githubusercontent.com/50516451/132239913-a31ff445-70e7-48aa-9cf2-db73a12427f8.png)

**Comment by solomiiatarnavska** [comment]
During fixing this bug please pay your attention to this one related to one of the form's fields
https://github.com/ita-social-projects/EPlast/issues/1734
