### ISSUE TITLE
[Дійсне членство] The date of the swear (дата присяги) must be without limits and the date of completion (дата завершення) may not be faster than the date of the swear

### ISSUE THREAD

**Issue by ZoryanaKravchuk** [ita-social-projects/EPlast#1634]
**Environment**: Windows 10, Google Chrome 92.0.4515.107
**Reproducible**: always
**Priority**: high
**Severity**: low
**Build found**: b933a65

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log in.

**Steps to reproduce**

1. Go to 'User profile' and choose 'Дійсне членство'
2. Click on the button 'Змінити'
3. Сhoose 'Дата присяги ' з календаря
4. Сhoose 'Дата завершення ' з календаря
5.  Cklick on the button 'Змінити'

Actual result
The date of the swear (дата присяги) has limits and the date of completion (дата завершення) is faster than the date of the swear
![дата присяги і завершення](https://user-images.githubusercontent.com/87931020/129203578-eff78822-cf84-4ec0-a5f6-7a89bd7db7b2.png)
![дата присяги](https://user-images.githubusercontent.com/87931020/129203620-b376df12-f2a4-4795-adf8-4d44c73ea1f8.png)

**Expected result**
The date of the swear (дата присяги) must be without limits and the date of completion (дата завершення) may not be faster than the date of the swear

**Comment by OlgaShtogryn** [comment]
Also, if the past date is set in the 'Дата завершення' field, the User won't become the Former User.

**Comment by ZoryanaKravchuk** [comment]
**Also, look issue**  [User profile] We can't change "Дата присяги" and "Дата завершення" for registered user #1724

**Actual result**
We can't change "Дата присяги" and "Дата завершення" for registered user

**Expected result**
We can change "Дата присяги" and "Дата завершення" for registered user

**Comment by ZoryanaKravchuk** [comment]
**Also, look issue**   : **[User profile] We can't change "Дата присяги" and "Дата завершення" for registered user **#1724****

**Steps to reproduce**

1.Go to table of users
2.Open your new registered user
3.Open tab "Дійсне членство"
4.Press button "Змінити" in "Загальна інформація" field
5.Choose any data in "Дата присяги"
6.Choose any data in "Дата завершення"
7.Press button "Змінити"

**Actual result**
We can't change "Дата присяги" and "Дата завершення" for registered user

**Expected result**
We can change "Дата присяги" and "Дата завершення" for registered user

**Comment by setorianadya** [comment]
I can't move this bug in done because of  this bug:
[User profile] We can't change "Дата присяги" and "Дата завершення" for registered user #1724
