### ISSUE TITLE
[Warnings/Перестороги] [Awards/Відзначення] Error with a status code of 500 appears after editing, creating, and deleting warnings and awards

### ISSUE THREAD

**Issue by NataliaVoloshynska** [ita-social-projects/EPlast#1637]
Environment: Windows 10, Chrome 92.0.4515.107
Reproducible: always.
Priority: minor.
Severity: medium.
Build found: b933a65

Preconditions

Go to https://eplast.westeurope.cloudapp.azure.com
Log in as super admin.

Steps to reproduce

1. Open DevTools for a browser tab
2. Go to 'Довідник/Перестороги'
3. Choose any warning
4. Right click on this warning
5. Choose "Редагувати"
6. Сhange any information
7. Click on 'Зберегти' button
8. Go to 'Довідник/Відзначення'
9. Repeat steps 3-7

Actual result
Error with status code 500 appears (changes we made were saved)
![перестороги 500](https://user-images.githubusercontent.com/87755327/129325399-259863cf-23a1-404c-8205-79126b1deaef.png)
![відзначення 500](https://user-images.githubusercontent.com/87755327/129325415-1021df56-8ddc-4e3b-a33e-d2ca9241029e.png)

Expected result
Error shouldn't appear

**Comment by NataliaVoloshynska** [comment]
Also error with a status code of 500 appears after creating and deleting warnings and awards

**Comment by desharicoutsvert** [comment]
Everything is working correctly.

**Comment by solomiiatarnavska** [comment]
Also, we have an error during Senior Stuff editing
1) Find Senior Stuff section and go to КВ1(УПЮ) for example. Open it and try to edit the number by typing the already existing number (e.g. open #2 and try to change it to #124)
2) Press 'Опублікувати' button
3) Pay attention that the error message appears despite 200 status code has been got (also we have a 'true' statement in the Response section)

It should be 400 status code 
![Screenshot at Sep 27 18-33-21](https://user-images.githubusercontent.com/79641118/134940310-a732e074-9eaf-4245-8af4-5ce94f439db9.png)
![Screenshot at Sep 27 18-34-09](https://user-images.githubusercontent.com/79641118/134940316-0148e951-3a3b-4384-b3eb-b0a75697c14d.png)
![Screenshot at Sep 27 18-34-46](https://user-images.githubusercontent.com/79641118/134940322-0ec06687-cff0-46d0-ad0f-a105ca6e285f.png)
![Screenshot at Sep 27 18-35-04](https://user-images.githubusercontent.com/79641118/134940323-fd261ad7-4d9c-4c2a-a7b8-fdda97832de4.png)
![Screenshot at Sep 27 18-35-21](https://user-images.githubusercontent.com/79641118/134940329-883d0d2b-0eb7-4db6-aa1d-a7f9f564729d.png)

**Comment by ZoryanaKravchuk** [comment]
Error with a status code of 500 appears after creating and deleting Senior Stuff
![Кадра виховників](https://user-images.githubusercontent.com/87931020/134952895-fc472866-6a93-4b73-a0fe-461574fd61e2.png)
