### ISSUE TITLE
[Former member] The user remains at the board of City/Hovel/Region after assigning him the status 'Колишній член пласту'.

### ISSUE THREAD

**Issue by OlgaShtogryn** [ita-social-projects/EPlast#1655]
**Environment:** Windows 10, Mozilla Firefox 90.0.2.
**Reproducible:** always.
**Priority:** high.
****Severity:** major.
**Build found:**** d6e59ef

**Preconditions**
1.  Go to https://eplast.westeurope.cloudapp.azure.com
2.  Log in as a Super Admin.

**Steps to reproduce**
1. Go to Main Menu.
2. Click on 'Таблиця користувачів'.
3. Right-click on any member, which is at the board of Hovel/City/ Region.
4. Click on 'Змінити права доступу', then 'Поточний стан користувача'.
5. Choose 'Колишній член пласту' option.
6. Verify the current status of this user and the members of board to which he belonged.

**Actual result**
The former member doesn't belong to any Hovel/City/ Region, but still remains at the board to which he belonged.
![7](https://user-images.githubusercontent.com/87722808/129913949-0c0cb2dd-bba6-4572-94e3-92f1b0505c69.png)
![8](https://user-images.githubusercontent.com/87722808/129913969-02e8c15b-510c-40f1-8d5f-d7fe2ec7e80f.png)
**Expected result**
The former member must be deleted from all boards to which he belonged.

**Comment by setorianadya** [comment]
Almost the same - [Hovel/User Table] Former member steal in "Провід Куреня" #1689. Look also at this bug, please
