### ISSUE TITLE
[Degree] The Deputy of City Admin can assign any degree to members of his city through the Users table.

### ISSUE THREAD

**Issue by OlgaShtogryn** [ita-social-projects/EPlast#1677]
**Environment:** Windows 10, Mozilla Firefox 90.0.2.
**Reproducible:** always.
**Priority:** medium.
**Severity:** minor.
**Build found:** d6e59ef

**Preconditions**

1.   Go to https://eplast.westeurope.cloudapp.azure.com
2.   Log in as a Deputy of City Admin.

**Steps to reproduce**
1.   Go to Main Menu.
2.   Click on 'Таблиця користувачів'.
3.   Right-click on the member of your city.
4.   Click on 'Додати ступінь'.
5.   Choose 'Улад старшого пластунства' and then any degree except Старший пластун прихильник/Старша пластунка прихильниця'' (e.g. 'Старший пластун/ Старша пластунка'), set the current date and click 'Додати'.
6.  Verify that the degree was assigned to the user.
7. Repeat steps 5, 6 with 'Улад пластового сеніорату' and 'Пластун сеніор керівництва/Пластунка сеніорка керівництва' degree.

**Actual result**
The Deputy of City Admin can assign any degree to members of his city through the Users table.
![2](https://user-images.githubusercontent.com/87722808/130435810-c73d5534-d654-4959-85c6-363c93713040.png)
![3](https://user-images.githubusercontent.com/87722808/130435819-2b6bf07c-d465-4bb4-a631-eccc50c5727d.png)

**Expected result**
The Deputy of City Admin should assign only 'Пластун сеніор прихильник/Пластунка сеніорка прихильниця' and 'Старший пластун прихильник/Старша пластунка прихильниця' degrees.
![1](https://user-images.githubusercontent.com/87722808/130435836-99556773-506e-4874-b8af-85b26e20bbf6.png)

**Comment by NatalyMinziuk** [comment]
Dublicate #1765
