### ISSUE TITLE
[Event/Фотографії події] Admin of Event is not able to add a group of photos to Gallery at once

### ISSUE THREAD

**Issue by olesiakhrushch** [ita-social-projects/EPlast#1679]
**Environment:** Windows 10, Chrome 91.0.4472.101.
**Reproducible:** always.
**Priority:** low.
**Severity:** low.
**Build found:** d6e59ef

**Preconditions**

1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log in as any User (except a Registered User)
3. Create a new Event and appoint yourself as an admin

**Steps to reproduce**

1. Go to 'Події'
2. Click on 'Список' in "Створені події" sector
3. Click on 'Деталі' button
4. Add 15 large size photos to Gallery (size of one photo > 5 MB)
5. Click the "Надіслати" button

**Actual result**
Error message appears when the user adds a group of large size photos

![Screenshot_53](https://user-images.githubusercontent.com/84467235/130466412-bd262e92-f637-4d79-a278-11c54dfb17e1.png)
![Screenshot_54](https://user-images.githubusercontent.com/84467235/130466419-6d039f08-a993-443c-ac7a-1b46521e1f50.png)

**Expected result**
Users should have the possibility to add a group of photos

**Comment by LidiiaH** [comment]
Look also to this bug [Events] We can`t add more than three photos to event #1715

**Comment by Hrystyna96** [comment]
We can`t add more than three large size photos to the event. (size of one photo > 5 MB)
![Add photo](https://user-images.githubusercontent.com/96823023/161032473-31494c07-a172-4a3b-bcf5-61cedafb459f.png)

**Comment by sysoyeva** [comment]
Users can add up to 15 photos(size of one photo 5 MB)
