### ISSUE TITLE
[Event/Події] rename 'Сьогодні' button

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1687]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: low
**Severity**: low
**Build found**: a6360ed

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Click on your personal profile 'Редагувати профіль' section
2.Open 'Події'
3.Find 'Календар подій' in the bottom of a page (see attached screen below) and open 'Переглянути' 
4.Click on 'Сьогодні' button and pay attention that nothing has happened 

**Actual result**
After clicking on  'Сьогодні' button the system does not respond (nothing has happened)

**Expected result**
Rename this button on 'Поточний місяць'

**User story and test case links**
![Screenshot at Aug 26 13-18-39](https://user-images.githubusercontent.com/79641118/130946659-491d6d28-7955-4623-965e-3a5fc0cdc89e.png)
![Screenshot at Aug 26 13-19-18](https://user-images.githubusercontent.com/79641118/130946672-10c2a945-9bfd-4cca-8175-8256b204889b.png)
![Screenshot at Aug 26 13-21-13](https://user-images.githubusercontent.com/79641118/130946678-a674fd93-808e-44f8-8bcb-142fbf926a36.png)

**Comment by juliazhorniakAMI** [comment]
edited button
