### ISSUE TITLE
[Events/user page] Buttons on window "Створені події"/"Відвідані"/"Заплановані" are not aligned

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1698]
**Environment:** Mi Note3MIUI Global 12.0.1 Стабільна збірка, Версія Android 9 PKQ1.181007.001, Google Chrome 92.0.4515.107
**Reproducible:** always
**Priority:** medium
**Severity:** minor.
**Build found:** d376577

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log in as a user where you have events.

**Steps to reproduce**

1. Open your user
2. Press the "Events" button
3. Swipe down and find the "Список" button
4. Press the "Список" button
5. Look at the "Деталі", "Редагувати" buttons
 
**Actual result**
"Деталі", "Редагувати" buttons are not aligned
![image](https://user-images.githubusercontent.com/50516451/131262453-60218a68-9114-4002-9c36-11158fe4e3f1.png)

**Expected result**
"Деталі", "Редагувати" buttons should be  aligned

**Comment by christykobyletska** [comment]
such issue on event calendar ->"Переглянути -> choose any event and take a look on appeared modal
![image](https://user-images.githubusercontent.com/25940952/135722280-74295995-f66f-4522-833e-c18bb8100d88.png)

**Comment by ZoryanaKravchuk** [comment]
This bug  is still reproduced on 'Заплановані події'.

Uploading Заплановані події.mp4…
