### ISSUE TITLE
[Access Levels/Active Membership/Оffice management] Adherent should not retain Оffice management(Діловодства) after becoming a registered user

### ISSUE THREAD

**Issue by ZoryanaKravchuk** [ita-social-projects/EPlast#1705]
**Environment**: Windows 10, Google Chrome 92.0.4515.107
**Reproducible**: always
**Priority**: high
**Severity**: high
**Build found**: 4275726

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1. Log into the system
2. Go to the left-side panel on the main page and click on 'Довідник'
3. Choose 'Таблиця користувачів' section
4. Choose anyone Adherent
5. Click the right mouse button on this user
6. Сhoose 'Змінити права доступу'
7. Click on 'Поточний стан користувача'
8. Click on text field
9. Choose 'Зареєстрований користувач'
10. Go to this user's profile
11. Choose Active Membership (Дійсне членство)
12. Choose Оffice management ( Діловодства)

**Actual result**
Adherent who has become a registered user saved all roles in Оffice management( Діловодства)
![Прихильник](https://user-images.githubusercontent.com/87931020/131361021-d1c020ea-21fe-4144-bc30-2634d55b7078.png)
![Зареєстрований користувач](https://user-images.githubusercontent.com/87931020/131361045-39459424-c296-401b-a1b5-38f19fa5709f.png)
![Дійсні діловодства станиці](https://user-images.githubusercontent.com/87931020/131361977-ec19dd3e-1b78-4889-8160-052c5f55b2ef.png)

**Expected result**
When a user becomes a Registered user he/she should not retain Active Membership (Дійсне членство) and Оffice management( Діловодства)

**Comment by Omeliukh-Nazar** [comment]
It is impossible to make user 'Зареєстрований користувач' at 'Змінити права доступу' now. Retest or close issue.

**Comment by Svturinina** [comment]
Defect fixed
