### ISSUE TITLE
[User Page] Combobox offers strange options in the profile information edit in next fields: "Національність", "Віровизнання", "Навчальний заклад", "Спеціальність", "Навчальний ступінь", "Місце праці", "Посада"

### ISSUE THREAD

**Issue by sviatoslab** [ita-social-projects/EPlast#1708]
Environment: Windows 10 x64, Version 92.0.4515.159 (Official Build) (64-bit).
Reproducible: always.
Priority: low.
Severity: minor.
Build found: 4275726

Preconditions
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in.

Steps to reproduce

1. Open your user page;
2. Click on the button "Редагувати профіль" button;
3. Click the combobox in any next fields: "Національність", "Віровизнання", "Навчальний заклад", "Спеціальність", "Навчальний ступінь", "Місце праці", "Посада";
4. Pay attention to offered options.

Actual result
 The combobox offers strange options in the profile information edit in next fields: "Національність", "Віровизнання", "Навчальний заклад", "Спеціальність", "Навчальний ступінь", "Місце праці", "Посада".

Expected result
There are offered normal options in the combobox of next fields: "Національність", "Віровизнання", "Навчальний заклад", "Спеціальність", "Навчальний ступінь", "Місце праці", "Посада".

![2021-08-31_13-27-38](https://user-images.githubusercontent.com/59814492/131488003-6531ce58-d75e-4a32-be83-af4bbb42e8f0.jpg)

**Comment by ZoryanaKravchuk** [comment]
**Look issue**  [User Page] We can`t input long name of our university #1702

**Actual result**
Error message that the maximum number of characters is 50

**Expected result**
At list 100 characters for "Навчальний заклад" field

**Comment by hryhoriivoloshyn** [comment]
This is not a bug. This issue can be safely deleted.
