### ISSUE TITLE
[Region/Access levels] The user remains the region admin even if he changes the city in another region

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1709]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always
**Priority:** high.
**Severity:** major.
**Build found:** 4275726

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as the region admin

**Steps to reproduce**

1. Go to cities
2. Select any city, not in your region (e.g. change "Долина" to "Ізмаїл")
3. Add yourself into this city
4. Open your user page 
5. Choose "Діловодства" and open "Діловодства округи"

**Actual result**
 The user remains the region admin even if he changes the city in another region
![image](https://user-images.githubusercontent.com/50516451/131537724-412e6e0f-e369-4195-9625-935b5c722ceb.png)

**Expected result**
When a user change region he(she) can't be an admin in the previous region

**Comment by solomiiatarnavska** [comment]
Please pay your attention that we have a similar bug which means that user can add other users in "Провід округи" (Region) even if he/she is not Admin of this region. It looks like Admin's rights remain despite the user is not a Region Admin anymore.
So during fixing this open check and fix another.

https://github.com/ita-social-projects/EPlast/issues/1710
