### ISSUE TITLE
[Regions/Access levels] We can add users in "Провід округи" (region) even if we are not admin of this region

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1710]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always
**Priority:** high.
**Severity:** major.
**Build found:** 4275726

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as the region admin (e.g Дніпропетровськa)
A city with few members (e.g Ізмаїл)

**Steps to reproduce**

1. Go to cities
2. Select city from preconditions (any other city which is not in your region, but has members)
3. Add yourself into this city
4. Open "Таблиця користувачів"
5. Choose any member from the city where you added yourself
6. Press the right button on your mouse (cursor over chosen user)
7. Choose "Змінити права доступу"  --> "Провід округи"
8. Choose any role
9. Open region of your new city (e.g Одеська)
10. Look at the "Провід округи" field

**Actual result**
We can add users in "Провід округи" even if we are not admin of this region (see screenshot and screenshot in comments)
![image](https://user-images.githubusercontent.com/50516451/131540753-6821644c-09b7-4c7a-8a9b-422268372d5c.png)

**Expected result**
We can't add admins of the region when we are not admin of this region

**Comment by setorianadya** [comment]
User was as admin in "Дніпропетровська округа"
![image](https://user-images.githubusercontent.com/50516451/131541066-38067303-1155-421c-9ec7-17208cbb3f7a.png)

**Comment by solomiiatarnavska** [comment]
This bug has been sent to 'Done' section since I have described and attached it to another similar bug https://github.com/ita-social-projects/EPlast/issues/1709
