### ISSUE TITLE
[Hovels]  Disenfranchised deputy of hovel admin

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1711]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always
**Priority:** low.
**Severity:** minor.
**Build found:** 4275726

**Preconditions**
Open two browser`s windows (one incognito)
Go to https://eplast.westeurope.cloudapp.azure.com/signin in both windows
Log in as the user to the hovel you will be working with in one of the windows
Log in as Super Admin in another window 

**Steps to reproduce**

1. Go to hovels as Super Admin
2. Choose any hovel where you have users
3. Add your user from a precondition in "Провід куреня" as deputy of city admin
4. In the window where you logged in as a user in hovel delete yourself from "Провід куреня"
5. In the window where you logged in as Super admin add your user as deputy of city admin again
6. In the window where you logged in as a user in hovel reload page

**Actual result**
Disenfranchised deputy of hovel admin
![image](https://user-images.githubusercontent.com/50516451/131562870-03b7ccab-35ea-438c-a599-60984ea55229.png)

**Expected result**
Deputy of city admin must have his rights

**Comment by SerhijK** [comment]
Pay attention, when you delete your 'Deputy of city admin' user from "Провід куреня" in the window where you logged in as Super admin. Then you have opportunity to add your user to "Провід куреня" as 'Deputy of city admin' again in the window where you logged in as a user in hovel, but before you reload the page. And then your user also does not have 'Deputy of city admin' rights.
