### ISSUE TITLE
[Email notification] incorrect message is sent, when User (any role) is excluded from a City/Станиця

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#1720]
Environment: Windows 10 Home 64 bit, Google Chrome Version 92.0.4515.159 (Official Build) (64 bit)
Reproducible: always
Priority: low
Severity: low
Build found: 4275726

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as Super Admin

**Steps to reproduce**

1. Go to 'Довідник' and choose 'Станиці' section in the left side of a page
2. Open a City/Станиця where you are going to exclude your User
3. Click on 'Більше' button in 'Члени станиці' section
4. Click on 'x' icon, then click on 'Такб видалити' button
5. Check your personal e-mail box

**Actual result**
![Email notification act2](https://user-images.githubusercontent.com/89202294/135293994-5f068766-26c7-4d17-aaf2-19db61226d16.jpg)
![Email notification act](https://user-images.githubusercontent.com/89202294/135294037-63dd6f60-4baa-4688-a6e2-1c24b8eca3d0.jpg)

**Expected result**
![Email notification exp](https://user-images.githubusercontent.com/89202294/135294133-fccd18cd-5e91-4a46-a4a5-abe8387c2af7.jpg)

**Comment by Tali32** [comment]
Not a reproducible bug!

**Comment by SerhijK** [comment]
Defect is reproducible only if Super Admin (or City/Village Admin) confirm a user's request and join him/her to the City/Станиці by clicking on '+' button more then once. Also I have noticed, that when user is confirmed by clicking on '+' button twice he is not joined to the City/Станиця and message from actual result appears, when thrice user is joined to the City/Станиця and the same message appears, when four times user is not joined and message from actual result also appears.
Also the defect is reproducible (but without email notification) in Hovels/Курені when Super Admin (or Hovel Admin) confirms the user into the hovel.
