### ISSUE TITLE
[City/Region] Head and Deputy unification in naming

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1726]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: low
**Severity**: low
**Build found**: 701fef2

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Open left-side menu and click on 'Довідник' section
2.Open it
3.Find 'Округи' section and open it
4.Find any Region (Округу) without a Head and Deputy (Голова округи і Заступник голови округи), e.g. Тернопільська (see attached screen below)
5.Pay your attention on the spelling the titles (see attached screen below)
6.Open left-side menu and click on 'Довідник' section
2.Open it
3.Find 'Станиці' section and open it
4.Find any City (Станицю) without a Head and Deputy (Голова станиці і Заступник голови станиці), e.g. Павлоград (see attached screen below)
5.Pay your attention on the spelling the titles (see attached screen below)

**Actual result**
There are some distinctions in City and Region Head/Deputy naming

**Expected result**
Please rewrite Head/Deputy naming in Region section as we have it on a City section and make it bolt 
(**Немає голови округи**,
**Немає заступника голови округи**)

**User story and test case links**
![Screenshot at Sep 06 10-03-00](https://user-images.githubusercontent.com/79641118/132174944-8863f1ec-f58e-4ebe-8742-20a4bb5e3790.png)
![Screenshot at Sep 06 10-06-02](https://user-images.githubusercontent.com/79641118/132174954-c407b3e4-9988-4ae5-ab2e-b1c7d15c3e68.png)

**Comment by christykobyletska** [comment]
A better option will be to rewrite Head/Deputy naming in the Region/City/Club section and make it bolt
(Ще немає голови округи, Ще немає заступника голови округи) to match naming through all system.
