### ISSUE TITLE
[Profile] 'Ступінь в УПЮ' field doesn't change according to the chosen gender in user's profile

### ISSUE THREAD

**Issue by irynadrapak** [ita-social-projects/EPlast#1728]
**Environment:** Windows 10, Google Chrome 92.0.4515.159 (64-bit)
**Reproducible:** always
**Build found:** 701fef2

**Priority**: low
**Severity**: minor

**Steps to reproduce**
1. Go to https://eplast.westeurope.cloudapp.azure.com/signin
2. Log in as any user. 
3. Go to 'Таблиця користувачів' and select user 'Любко Олеськів'. Go to this user's profile.
4. Check the 'Стать' and 'Ступінь УПЮ' fields.

**Actual result**
'Ступінь в УПЮ' field displays 'пластун скоб' value even though the chosen gender is 'Не маю бажання вказувати'.

**Expected result**
'Cтупінь в УПЮ' field displays 'пластун скоб / пластунка вірлиця' value.

![slash in gender](https://user-images.githubusercontent.com/78311377/132201695-73ebd254-8c00-45cf-abd6-8b22cc4405fe.png)

**Comment by christykobyletska** [comment]
already exist https://github.com/ita-social-projects/EPlast/issues/1719
