### ISSUE TITLE
[Regions/Cities] We can create a city in an archived region

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1731]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always.
**Priority:** medium.
**Severity:** major.
**Build found:** 701fef2

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as Super Admin.

**Steps to reproduce**

1. Go to cities
2. Press button "Створити нову станицю"
3. In field "Округа" scroll down
4. Fill in all other required fields
5. Press button "Створити"

**Actual result**
1. We see archived regions in the drop-down list of regions 
2. We can create a city in an archived region
(see screenshots)
![Заархівовані Округи](https://user-images.githubusercontent.com/50516451/132235816-535ef63e-de87-4830-b3e6-ad30ebfad457.png)
Archived regions are marked
![Станиця в хаархівовані окрузі](https://user-images.githubusercontent.com/50516451/132236191-97d4d366-1ad2-46f8-917d-fcbcfdc6a9b0.png)

**Expected result**
1. We can`t see archived regions in the drop-down list of regions and make cities in archived regions

**Comment by setorianadya** [comment]
Also, reproduce with Postman

**Comment by gutovskii** [comment]
It works correctly on deploy

**Comment by AnnaHumeniuk2212** [comment]
It works correctly on build [48e9085](https://github.com/ita-social-projects/EPlast/commit/48e90856447d7d6abeae54daebb1c1c1bcb6f939)
