### ISSUE TITLE
[Cities/Regions] Message "Максимальна довжина - 5 символів" near "Номер офісу/квартири" field

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1734]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always.
**Priority:** low.
**Severity:** minor.
**Build found:** 701fef2

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as Super Admin.

**Steps to reproduce**

Go to cities/regions
Press button "Створити нову станицю"/ "Створити нову округу"
Press button "Створити"/ "Підтвердити" for regions

**Actual result**
Message "Максимальна довжина - 5 символів" near "Номер офісу/квартири" field

**Expected result**
Message "Поле є обов'язковим" near "Номер офісу/квартири" field

**Comment by solomiiatarnavska** [comment]
This bug moves to 'Done' because I have mentioned (attached) it on another ones with a similar functionality
