### ISSUE TITLE
[Awards]  Awards are sorting only on page

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1751]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always.
**Priority:** medium.
**Severity:** minor.
**Build found:** 35add5d

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as Super Admin.

**Steps to reproduce**

1. Go to "Перестороги"
2. Choose any type of precaution
3. look how many precautions you find
4. Got to "Відзначення" 
5. Try to sort awards by numbers

**Actual result**
 Precautions and awards are sorting only on-page

**Expected result**
Precautions and awards should be sorted on all pages and we should have the opportunity to turn on/off sorting

**Comment by setorianadya** [comment]
The same for warnings

**Comment by UlianaVarlamova** [comment]
Tested on a1b8bf1 build. Defect fixed. Status is changed to "Closed"
