### ISSUE TITLE
[Notifications] User get a notification without name of Region while user is deprived a role in the Region

### ISSUE THREAD

**Issue by LidiiaH** [ita-social-projects/EPlast#1756]
**Environment:** Windows 10, Google Chrome Version 93.0.4577.63 (64-bit version)
**Reproducible:** always
**Priority:** High
**Severity:** Minor
**Build found:** 078095a

**Preconditions**
1.Go to https://eplast.westeurope.cloudapp.azure.com/signin
2.Log in as Super Admin and in another tab as user for example "Ліда Ліда"

**Steps to reproduce**
1. Go to "Округи" tab from Super Admin account
2. Select "Вінницька" Region
3. Click on "Plus" button under "Провід округи" label
4. Add user to "Провід округи" and select to user "Ліда Ліда" any administrative role
5. Click "Опублікувати"
6. Go to "Провід округи" and delete user "Ліда Ліда" from it
7. Go to user "Ліда Ліда" page
8. Check the notification

**Actual result**
"Вас було позбавлено адміністративної ролі: 'Член ОПР' в окрузі:" notification appears

**Expected result**
"Вас було позбавлено адміністративної ролі: 'Член ОПР' в окрузі: Вінницька" notification appears

**Labels to be added**
"Bug" ("bug"), "Regions (округи)", "Notifications(Сповіщення)"

![region](https://user-images.githubusercontent.com/89202242/132573307-35db45b7-fc4e-4f0a-893b-343d3b92b45e.png)

**Comment by solomiiatarnavska** [comment]
This bug has been sent to Done since I have described and attached it to a similar one.

**Comment by ystrotska** [comment]
Please note the bug was retested and is available on production. The name of the region is not indicated in the notification message after the user has lost the role in region.

![image](https://user-images.githubusercontent.com/104917914/194244233-40e28f29-d118-4457-b26f-4b326d608c44.png)

**Comment by SvitlanaOleksiv** [comment]
Please note the bug was retested and is available on production. The name of the region is not indicated in the notification message after the user has lost the role in region.
![Сповіщення "домівкар" в окрузі](https://user-images.githubusercontent.com/110596345/196245602-0e856753-4dc5-4cbe-9bfa-1c98b0ed6d20.png)

**Comment by Mykola123-NMT** [comment]
![image](https://user-images.githubusercontent.com/77533165/196365533-39b3ceca-73c3-4e11-bb2e-6eccbfee32ba.png)
Comment explains why this bug was closed.
