### ISSUE TITLE
[User's table/Access levels] Registered user and adherent at the same time  after adding "Пластприят" degree

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1770]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always.
**Priority:** medium.
**Severity:** minor.
**Build found:** 5dfcf5e

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as Super Admin.

**Steps to reproduce**

1. Go to "Таблиця користувачів"
2. Choose any registered user, without a city
3. Press the right button on your mouse
4. Сhoose "Додати ступінь" button and press it
5. Choose "Пластприят"
6. Go on your user page and open "Дійсне членство"

**Actual result:**
Registered user and adherent at the same time 
![image](https://user-images.githubusercontent.com/50516451/132984447-09576f63-1126-4419-9e59-5d850629f197.png)

**Expected result**
User can`t be adherent without city

**Comment by setorianadya** [comment]
Also if we added this user to the city we will have user with two of the same access levels:
![image](https://user-images.githubusercontent.com/50516451/132984596-c5e822a7-ac68-4464-8d05-cc108dfe41eb.png)

**Comment by setorianadya** [comment]
This button should be deleted for registered users:
![Додати ступінь](https://user-images.githubusercontent.com/50516451/136172790-553878c2-4f25-4a8c-a6ee-df13d4ce3925.png)

**Comment by Goven112** [comment]
dublicate bug with bug #1967
