### ISSUE TITLE
[Edit Log in page] Improvement - Change the error message if the user enters the e-mail incorrectly.

### ISSUE THREAD

**Issue by desharicoutsvert** [ita-social-projects/EPlast#1778]
Change the error message if the user enters the e-mail incorrectly to a more correct one: 'Введіть коректну адресу електронної пошти'.

![Логін](https://user-images.githubusercontent.com/89357123/133062619-d119ede4-9213-4a70-8cad-06ddd19b045f.PNG)

**Comment by solomiiatarnavska** [comment]
The same situation appears during New Governing Body creation
![Screenshot at Sep 17 11-43-02](https://user-images.githubusercontent.com/79641118/133753061-217d5263-72e1-478c-8375-e1296340cc08.png)

**Comment by solomiiatarnavska** [comment]
As well as during the creation of a New Direction in a Governing Body
![Screenshot at Sep 17 11-44-27](https://user-images.githubusercontent.com/79641118/133753254-68645f79-84e5-47c7-81fa-a12dff4ba89a.png)
