### ISSUE TITLE
[Event] Incorrect pop-up for the finished events.

### ISSUE THREAD

**Issue by desharicoutsvert** [ita-social-projects/EPlast#1788]
Environment: Windows 10, Google Chrome Version 93.0.4577.63 (Official Build) (64-bit).
Reproducible: always.
Priority: medium.
Severity: low.

Preconditions
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as any User.

**Steps to reproduce**
1. Go to 'Події'
2. Click on 'Зголоситись на подію'
3. Choose any 'Тип' and 'Категорія'
4. Click on the flag icon of any finished event.

**Actual result**
A pop-up 'Завершений(-на)' appears.

**Expected result**
A pop-up 'Завершено' should appear.

![Подія](https://user-images.githubusercontent.com/89357123/133336724-520c801b-ef4b-4182-b424-30eb5122d7cb.jpg)

**Comment by ZoryanaKravchuk** [comment]
**During fixing this bug also, look this one** 'There are dots in the and of the words'
![Aдміністрація події](https://user-images.githubusercontent.com/87931020/133334886-f5b6d4d7-f4e6-4afb-bb90-5eb9b07600c3.png)
![Адміністрування галереї](https://user-images.githubusercontent.com/87931020/133334901-f5e4c6ce-1a4a-4b68-a31d-23e382563cb5.png)
