### ISSUE TITLE
[Singing/User profile] We can see users  credentials in Dev Tools

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1801]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)
**Reproducible:** always.
**Priority:** High.
**Severity:** major.
**Build found:** d6e59ef

**Steps to reproduce**

1. Go to https://eplast.westeurope.cloudapp.azure.com/signin
2. Input your login and password
3. Open dev tools (F12 or right-click on mouse-->Inspect)
4. Open tab "Network"
5. Press button "Увійти"
6. Find request "singing' and scroll down

**Actual result**
We can see users  credentials in Dev Tools

**Expected result**
User credentials must be encrypted

**Comment by tvardero** [comment]
Our project uses `https://` which encrypts all sent and received data.
