### ISSUE TITLE
[Senior Stuff] odd error message during creating a new Senior Stuff

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#1810]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: low
**Severity**: low
**Build found**: d120d27

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Open left-side menu and go to 'Довідник' section
2.Choose 'Кадра виховників' (Senior Stuff) section and click on it
3.Click on 'Надати кадру' button and entering no data click on 'Опублікувати' button

**Actual result**
'Request failed with status code 400' appears under the last field (Номер в реєстрі)

**Expected result**
Only one message 'Поле є обов'язковим' should be present under this field (see attached screen below)

**User story and test case links**
![Screenshot at Sep 17 12-25-49](https://user-images.githubusercontent.com/79641118/133760403-110aba76-9d2c-483f-8478-6461e7a9a7ac.png)

**Comment by ZoryanaKravchuk** [comment]
Also look at Warnings and Award/distinction 
![Відзначення (extra error message)](https://user-images.githubusercontent.com/87931020/134954624-e25c76f8-2a1f-495a-ac6a-271c61a042d7.png)
![Перестороги (extra error message)](https://user-images.githubusercontent.com/87931020/134954648-b90e8959-4447-499f-b8c3-a0b6b4ff505f.png)
