### ISSUE TITLE
[Decisions] When the user adds a new decision on the second page, the decision table is displayed empty

### ISSUE THREAD

**Issue by nsavchuk41** [ita-social-projects/EPlast#1812]
**Environment:** OS Windiws 10, Version 93.0.4577.82 (Development) (64-bit version)
**Reproducible:** always
**Priority:** low.
**Severity:** low.
**Build found:** E.g. "commit 3bcc129"

**Preconditions**
  1.The user is logged in as an administrator (Крайовий/Окружний/Станичний/Куреня/Супер Адмін).
  2. The user has opened the page "Рішення керівних органів".
  
**Steps to reproduce**
1. Go to the second page of the table
2. Click on 'Додати рішення' button
3. Enter the correct data in the form
4. Click on 'Опублікувати' button

**Actual result**
An empty table is displayed to the user.

**Expected result**
The user is shown a table with previously added solutions

**Comment by GitNazar** [comment]
Re-testing passed
