### ISSUE TITLE
[Провід і члени Округи/Станиці/Куреня] users with long first and last name are differently displayed

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#1820]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 94.0.4606.61 (64 bit), Microsoft Edge 93.0.961.52 (64 bit) and Mozilla Firefox 92.0.1 (64 bit)
Reproducible: always
Priority: low
Severity: low
Build found: 3bcc129

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin

**Steps to reproduce**

1. Go to 'Довідник' and choose 'Округи/Станиці/Куреня' section in the left side of a page
2. Click on 'Більше' button in 'Провід округи/станиці/куреня' section 
3. Type some letters in first or last user's name if there are no users with first and last name more than 19 letters (in Google Chrome, Microsoft Edge) and more than 20 letters (in Mozilla Firefox)
4. Verify how users first and last name displays in Google Chrome, Microsoft Edge and Mozilla Firefox (in each browser separately)
5. Click 'Назад' button
6. Click on 'Більше' button in 'Члени станиці/куреня' section
7. Verify how users first and last name displays in Google Chrome, Microsoft Edge and Mozilla Firefox (in each browser separately)

**Actual result**
Users with long first and last name are differently displayed
![Chrome and Edge](https://user-images.githubusercontent.com/89202294/134771799-183db814-54e5-4f92-843e-00ccab8526f4.jpg)
![Mozilla Firefox](https://user-images.githubusercontent.com/89202294/134771807-925ecf91-8c83-4e2a-ad01-76e5dbd52c3b.jpg)

**Expected result**
Users with long first and last name are equally displayed

**Postcondition**
If you change first or last user's name, return it to the previous state

**Comment by SerhijK** [comment]
Also tooltip should appear when we hover the mouse on users with long first and last name in 'Провід і члени Округи/Станиці/Куреня'

**Comment by christykobyletska** [comment]
It looks like user cards have a different size in city/hovel, especially width

**Comment by SerhijK** [comment]
I have just measured size. It is the same in city/hovel. I think there is another reason

**Comment by christykobyletska** [comment]
Please take a look at governing body and sector, the same situation could be there also

**Comment by SerhijK** [comment]
Now users first and last name displays in the same way in 'Провід Округи/Станиці/Куреня/Керівного органу/Напряму Керівного Органу' and in 'Члени станиці/куреня' and with tooltip for long first and last names

**Comment by SerhijK** [comment]
Please make tooltip for long names and delete dublice of name in 'Напрямки Керівного Органу' in Google Chrome, Microsoft Edge and Mozilla Firefox
![Governing body's Sectors](https://user-images.githubusercontent.com/89202294/135715977-73d8c1dd-42a1-464c-bbb7-82fd41fd13ea.jpg)
