### ISSUE TITLE
[Senior Staff] Super admin can add "Кадру виховників" to the registered users with Postman.

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1833]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit). Postman v8.10.0
**Reproducible:** always.
**Priority:** low.
**Severity:** minor.
**Build found:** 8c781c6

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as Super Admin

**Steps to reproduce**

1. Open Dev Tools
2. Go to "Кадра виховників"
3. Add Senior staff to somebody
4. From Dev Tools take the URL and put it in Postman
5. From Dev Tools take the request body and put it in Postman (Method POST)
6. From Dev Tools taketh Bearer token and put it in Postman 
7. Change ID in the request body to the ID of any registered user in Postman (e.g a84473c3-140b-4cae-ac80-b7cd5759d3b5)
8. Press the button "Send" in Postman

**Actual result**
Super admin can add "Кадру виховників" to the registered users with Postman.

**Expected result**
Super admin CAN'T add "Кадру виховників" to the registered user even with Postman.

**Comment by ZoryanaKravchuk** [comment]
It's still possible to add "Кадру виховників" to the registered users with Postman.
![Кадра для зареєстрованого](https://user-images.githubusercontent.com/87931020/147406120-95b9e712-6cd7-4dbd-98be-4f81e33adb48.png)

**Comment by sysoyeva** [comment]
Super admin can't add to "Кадру виховників"  the registered user even with Postman.
![постман](https://user-images.githubusercontent.com/104834042/167296446-f08fae45-8f8c-4b9f-9bee-601e4498c70a.png)
