### ISSUE TITLE
[Annual reports] Elements overlap in city annual report pdf

### ISSUE THREAD

**Issue by irynadrapak** [ita-social-projects/EPlast#1835]
**Environment:** Windows 10, google chrome v 92.0.4515.159 (64-bit)
**Reproducible:** always
**Priority:** low
**Severity:** minor
**Build found:**  #1789

**Preconditions:**
1. Go to https://eplast.westeurope.cloudapp.azure.com/signin
2. Log in as super admin or city admin, whose city has already submitted an annual report. (e.g.: Стрий)

**Steps to reproduce:**
1. Go to 'річні звіти' on the side menu.
2. Select city report (e.g.: 'Стрий').
3. Click on the 'see pdf' button.

**Actual result:**
1. In text fields with long labels, labels overlap with the input text.
2. 'Enters' are displayed as squares. 
3. Text input in section 'Maйно та потрреби станиці' is displayed in 1 line even when the size of input exceeds the length of 1 line. The remaining text is cut.
(see the screenshots)

**Expected result:**
The elements do not overlap.
The input text is broken into several lines when the size of the input text exceeds the length of 1 line.

![annual report overlap 1](https://user-images.githubusercontent.com/78311377/135087606-a93054ae-7962-4c32-ac5c-2284882affdf.png)
![annual report overlap 2](https://user-images.githubusercontent.com/78311377/135087610-4ebf662f-38a7-4b4d-8750-3b0613c98dea.png)
![doesn't break](https://user-images.githubusercontent.com/78311377/135087616-2a70dcf2-6c4a-405f-ad99-185bdc41584a.png)

**Comment by christykobyletska** [comment]
Please take a look at this bug created previously https://github.com/ita-social-projects/EPlast/issues/1403
