### ISSUE TITLE
[API/Персональний профіль] user (except Registered user) has opportunity to edit his 'Дата вступу/присяги/завершення' in 'Дійсне членство' tab by using Postman

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#1843]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 94.0.4606.61 (64 bit)
Reproducible: always
Priority: medium
Severity: medium
Build found: 26f3509

**Precondition**
Go to https://eplast.westeurope.cloudapp.azure.com

**Steps to reproduce**

1. Log into the system as User (except Registered user)
2. Press 'F12' button and click on 'Network' tab
3. Click on 'Дійсне членство' tab
4. Click on 'Змінити' button
5. Click on 'Змінити' button on the pop-up-menu
6. Type in 'Filter' textbox Method:POST
7. Click on 'dates' request and copy Request URL link, then put it in Postman
8. Copy User's token and put it in Postman on 'Authorization' tab (choose Bearer token in type)
9. Copy Request Payload on the bottom of Dev Tools and put it in Postman on 'body' tab
10. Edit User's 'Дата вступу/присяги/завершення' by using Postman

**Actual result**
User (except Registered user) has opportunity to edit his 'Дата вступу/присяги/завершення' by using Postman
![change date act](https://user-images.githubusercontent.com/89202294/135296573-d6b6fdb8-cd97-4871-97a4-da89cdc3afba.jpg)

**Expected result**
User does not have opportunity to edit 'Дата вступу/присяги/завершення' by using Postman. 'Дата вступу' should be earlier than 'Дата присяги/завершення'. 'Дата присяги' should be earlier than 'Дата завершення'
![change date exp](https://user-images.githubusercontent.com/89202294/135296630-c49d5c69-2092-49c3-885e-43e57538a6fd.jpg)

**Comment by SerhijK** [comment]
Pay attention, Super Admin has opportunity to edit 'Дата вступу', 'Дата присяги' and 'Дата завершення' by using Postman for all Users.
City Admin - for all participants of the City.
Region Admin - for all participants of the Region.

**Comment by ZoryanaKravchuk** [comment]
Also pay your attention to these bugs , Super Admin and other users can edit their profile by using Postman.
![Редагування профілю через Postman](https://user-images.githubusercontent.com/87931020/135580158-07ef7459-e132-46fd-ba9c-b7a796b33cdb.png)
![Редагув  профілю (Postman)](https://user-images.githubusercontent.com/87931020/135581861-ff0db81c-1a2e-4c4f-98b2-bc42db2f2c76.png)

**Comment by SerhijK** [comment]
Requirements have changed. Super/Country(Region)/City/Hovel Admin should have opportunity to edit 'Дата вступу/завершення' by using website and Postman. Please return this opportunity

**Comment by SerhijK** [comment]
@petromonka There is no opportunity to choose another 'Дата вступу' when click on 'Змінити' button in 'Дійсне членство' tab. It should be opportunity to change 'Дата вступу' on another one until today's date.
Also there is no opportunity to choose another 'Дата вступу' by using Postman.

https://user-images.githubusercontent.com/89202294/147391648-7cb5ff00-99bb-41bd-bd13-da6da948be62.mp4

**Comment by petromonka** [comment]
@SerhijK  Should be possibility to reset Entry Date? Or entry date should be mandatory and user must enter at least entry date to change dates (Oath date will be optional)?

**Comment by SerhijK** [comment]
@petromonka 

- Entry Date is mandatory, and should be an opportunity to edit this date for Super Admin, Country/City Admins and their Deputies (for users that are in their Country/City). Entry Date is set by default when a user is added to the City for the first time.
- Users (that are not  Country/City Admins and their Deputies) don't have the opportunity to enter or edit his Entry Date.
- There is some inconsistency for the Oath date. Super Admin has the opportunity to choose a date from the previous month when editing it, but  Country/City Admins and their Deputies don't have such an opportunity.
![1843 actual](https://user-images.githubusercontent.com/89202294/147414838-324f1c87-6430-4d7f-b913-41e1d51f6744.jpg)
![1843 actual2](https://user-images.githubusercontent.com/89202294/147414844-5829856e-0662-4904-8a8e-1f12c2983f45.jpg)
