### ISSUE TITLE
[API/Senior Staff] Super Admin has opportunity to edit 'Номер в реєстрі' on an existing one by using Postman

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#1844]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 94.0.4606.61 (64 bit)
Reproducible: always
Priority: medium
Severity: medium
Build found: 26f3509

**Precondition**
Go to https://eplast.westeurope.cloudapp.azure.com

**Steps to reproduce**

1. Log into the system as Super Admin
2. Press 'F12' button and click on 'Network' tab
3. Go to 'Довідник' and choose 'Кадра виховників' section in the left side of a page
4. Right-click mouse button on user name then click on 'Редагувати' in context menu
5. Click on 'Опублікувати' button
6. Type in 'Filter' textbox Method:PUT
7. Click on 'EditKadra' request and copy Request URL link, then put it in Postman
8. Copy token and put it in Postman on 'Authorization' tab (choose Bearer token in type)
9. Copy Request Payload on the bottom of Dev Tools and put it in Postman on 'body' tab
10. Edit 'Номер в реєстрі' on existing on by using Postman

**Actual result**
Super Admin has opportunity to edit 'Номер в реєстрі' on an existing one by using Postman
![registr number act](https://user-images.githubusercontent.com/89202294/135298806-1b67f06e-fedb-451b-bfb2-f0c59536e218.jpg)

**Expected result**
Super Admin does not have opportunity to edit 'Номер в реєстрі' on an existing one by using Postman
![registr number exp](https://user-images.githubusercontent.com/89202294/135298855-5f125ea3-2a33-4a7f-a805-c17d3dc5d36d.jpg)

**Comment by setorianadya** [comment]
Also, we can add the same Senior Stuff to one user:
![image](https://user-images.githubusercontent.com/50516451/135423417-23a6201b-c47e-4b3d-82da-945e8ee4e124.png)

**Comment by setorianadya** [comment]
And the same for precautions.
![image](https://user-images.githubusercontent.com/50516451/135627381-2ef8f186-3867-4f60-833e-9c17e849b984.png)

**Comment by SerhijK** [comment]
Super Admin has opportunity to edit 'Номер в реєстрі' on an existing one and add the same Senior Stuff to one user by using Postman. But there is an opportunity to add the same precaution for one user.
