### ISSUE TITLE
[Precaution] [API] User with access level "Зареєстрований користувач" get precaution list through API

### ISSUE THREAD

**Issue by sviatoslab** [ita-social-projects/EPlast#1847]
**Environment:** Postman 9.0.3, Windows 10 x64
**Reproducible:** always
**Build found:** 2d4deda

**Preconditions**
Have a user with access level "Зареєстрований користувач"
Get its bearer token
Paste this bearer token to the auth field

**Steps to reproduce**
1. Choose the get option in the request menu
2. Paste https://eplast.westeurope.cloudapp.azure.com/api/Precaution/UsersPrecautionsForTable to the URL field
3. Click the send button

**Actual result**
User with access level "Зареєстрований користувач" get precaution list through API

**Expected result**
User with level "Зареєстрований користувач" has not permission to get precaution list
![API_prec](https://user-images.githubusercontent.com/59814492/135540310-097a733d-4600-4aa6-a5a2-439b29d59d70.jpg)

**Comment by ZoryanaKravchuk** [comment]
Also pay your attention to these bugs , Super Admin can add Award/distinction (відзначення) for users who have Warnings or precautions (пересторога) by using Postman.
![Перестороги (Postman)](https://user-images.githubusercontent.com/87931020/135606702-80ab21e1-2f8d-4fc0-a88d-7a2274d000f5.png)
