### ISSUE TITLE
['Дійсне членство' tab] 'Діловод Округи/Станиці/Куреня' is not shown in user profile when add two or more 'Діловод О/С/К' roles and delete one then

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#1897]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 94.0.4606.71 (64 bit)
Reproducible: always
Priority: medium
Severity: medium
Build found: 31e0429

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as Super Admin

**Steps to reproduce**

1. Go to 'Округи/Станиці/Курені' where your User is member
2. Add to your User two or more 'Діловод Округи/Станиці/Куреня' roles
3. Delete one 'Діловод Округи/Станиці/Куреня' of your User's role
4. Open 'Дійсне членство' tab in user's profile on another tab in browser

**Actual result**
'Діловод Округи/Станиці/Куреня' is not shown in 'Дійсне членство' tab in user profile. 
It is shown when add one more 'Діловод Округи/Станиці/Куреня' role again.
![general act](https://user-images.githubusercontent.com/89202294/136529145-7ac863a8-464b-42df-87af-5e01fbb10ec8.jpg)

**Expected result**
'Діловод Округи/Станиці/Куреня' is shown in 'Дійсне членство' tab in User Profile.
![general exp](https://user-images.githubusercontent.com/89202294/136529170-ff2f735d-ae36-42f1-9995-bcf4a2ee46f1.jpg)

**Comment by SerhijK** [comment]
Pay attention, 'Голова/Заступник голови/Діловод Округи' role/s are displayed in 'Дійсне членство' tab when User changes Region and does not have role/s in new Region yet.
![general act](https://user-images.githubusercontent.com/89202294/136529527-991bcb60-7ba7-4d79-be06-dee928b6d0f4.jpg)
![general exp](https://user-images.githubusercontent.com/89202294/136529562-ab99e4dd-4beb-4d26-bb48-c0b1a163c010.jpg)

**Comment by Bodasyuk** [comment]
it's user profile bug

**Comment by AnnaHumeniuk2212** [comment]
The bug is also reproduced after changing the date of 'кінець каденції' - extension of time. 
![рівень доступу - діловод округи](https://user-images.githubusercontent.com/110613286/184015171-6653ddeb-0f5f-4cf8-beea-09eb9ce4f22a.png)
![рівень доступу діловод - зник](https://user-images.githubusercontent.com/110613286/184015209-f51655d3-6874-4151-bfdc-c203c210d88a.png)
