### ISSUE TITLE
User does not receive notifications about changes in the status of his application after registration on the Event (acceptance, concideration, rejection).

### ISSUE THREAD

**Issue by desharicoutsvert** [ita-social-projects/EPlast#1898]
**Environment**: Windows 10, Google Chrome Version 93.0.4577.63 (Official Build) (64-bit).
**Reproducible**: always.
**Priority**: high.
**Severity**: medium.

**Preconditions**:
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as any User who has already signed up for the Event.
At the same time, Log in as an administrator of the same Event.

**Steps to reproduce**
1. As an administrator, approve the user's request to join the Event.
2. As a user who applied for the Event, check the notification about approving of your application.

**Actual result**
After applying on the Event, the User does not receive notifications about acceptance of his application. (The same problem appears with consideration or rejection of Users applications).

**Expected result**
After applying on the Event, the User receive notifications about acceptance of his application. (Also the similar notifications should appear with consideration or rejection of Users applications).

![Notification 1](https://user-images.githubusercontent.com/89357123/136533359-f04b6e70-511f-4561-bd51-c40f74dd358d.jpg)
![Notification 2](https://user-images.githubusercontent.com/89357123/136533369-20f2a11d-3b2c-4e05-b0d3-a604a664e512.jpg)
![Notification 3](https://user-images.githubusercontent.com/89357123/136533372-bc74d53c-88b0-4556-b369-f4dba63b4971.jpg)

**Comment by dashapenkova** [comment]
same as #2080
