### ISSUE TITLE
[Decisions] Buttons disappear when we delete decisions on last page

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1903]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always
**Priority:** low.
**Severity:** major.
**Build found:** 31e0429

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as Super Admin
**Steps to reproduce**

1. Go to "Рішення"
2. Go to the last page on page "Decisions"
3. Delete all decisions on the last page 

**Actual result**
Buttons disappear when we delete decisions on the last page(see video)

https://user-images.githubusercontent.com/50516451/136575677-06a63b2c-c4c9-4165-acf9-11d73135b2e9.mp4

**Expected result**
The page should reload automatically and the buttons should be visible

**Comment by megzobacheva** [comment]
![123](https://user-images.githubusercontent.com/83592770/146148812-8d7be606-5782-4855-9b26-23b76a1d90ec.png)
The bug is still reproducible.
Environment: Windows 10 Pro 64-bit,  Google Chrome Version 92.0.4515.107
