### ISSUE TITLE
[Decisions] We can't see a new decision if it appear on the new page

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1904]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always
**Priority:** low.
**Severity:** major.
**Build found:** 31e0429

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as Super Admin
**Steps to reproduce**

1. Go to "Рішення"
2. Go to the last page on page "Decisions"
3. Press "Додати рішення" button
4. Fill in all required fields
5. Press "Опублікувати" button

**Actual result**
We can't see a new decision if it appears on the new page(see video)

https://user-images.githubusercontent.com/50516451/136578848-e7ea5c80-65cf-4030-945a-35a024c3aa53.mp4

**Expected result**
We should go on the new page automatically if our decision should appear on the new page

**Comment by GitNazar** [comment]
Re-testing unpassed, bug still reproducing

**Comment by GitNazar** [comment]
Re-testing passed (according to the new sorting rules)
