### ISSUE TITLE
[API - Decision] We can change "targetName" (Рішення для) to any value

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1931]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit). Postman v8.10.0
**Reproducible:** always.
**Priority:** medium.
**Severity:** minor.
**Build found:** 80bb09a

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as Super Admin

**Steps to reproduce**

1. Open Dev Tools
2. Go to "Рішення"
3. Add any decision
4. From Dev Tools take the URL where you added advertisement
5. Put this URL into Postman in the field for URLs and choose method "POST"
6. Copy Bearer token (actually it can be token of any user who can add decision)
7. Copy request`s body and put it in postman
8. Change field  "targetName" to any value (e.g Зелений)
9. Press the button "Send" in Postman

**Actual result**
We can change targetName to any value
**Expected result**
We can't change targetName (on site it have list of values)

**Comment by NatalyMinziuk** [comment]
It`s not a bug. TargetName can be any value

**Comment by SofiaSen** [comment]
Field 'Рішення для' should work with @ only for users, no random words

**Comment by SofiaSen** [comment]
Let's do @ functionality including 'Space' :
- If there is no space, for example, when we type the email, that's ok not to search the user in the database;
- if we type space and then @ , the system should propose the user from Plast
