### ISSUE TITLE
[Крайовий провід] "Архів Крайового Проводу Пласту" tab is not displayed on the "Крайовий Провід Пласту" page.

### ISSUE THREAD

**Issue by NataliiaTsepukh** [ita-social-projects/EPlast#1970]
**Environment:** OS: Windows 10 (x64) Google Chrome 93.0.4577.82
**Reproducible:** always.
**Priority:** high
**Severity:** medium
**Build found:** 327644d

**Preconditions:**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as any User who has already registered on the site.

**Steps to reproduce:**

   1. Go to 'Крайовий Провід Пласту'

**Actual result:**
 "Архів Крайового Проводу Пласту" tab is not displayed on the "Крайовий Провід Пласту" page.
![Screenshot_3](https://user-images.githubusercontent.com/24891698/138748358-6437d5d3-b875-4b99-b7fb-efd92ed8cee1.png)

**Expected result:**
 "Архів Крайового Проводу Пласту" tab is displayed on the "Крайовий Провід Пласту" page and all ePlast users can view this  table.

**Comment by Mykola123-NMT** [comment]
Functional is changed.
