### ISSUE TITLE
[User profile/ tab 'Дійсне членство'] page is not refreshed when click on 'Видалити' button as Country/Deputy of Country Admin

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#1980]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 95.0.4638.54 (64 bit)
Reproducible: always
Priority: medium
Severity: low
Build found: fe6e948

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as Country Admin

**Steps to reproduce**
Go to user profile of User that is in your Country (Окрузі)
Click on 'Дійсне членство' tab
Click on 'Додати ступінь' button if User does not have 'Ступінь'
Click on 'Видалити' button

**Actual result**
Page is not refreshed
![actual result](https://user-images.githubusercontent.com/89202294/139019905-729bf1bb-8050-4276-a7cc-86ed118d9a13.jpg)

**Expected result**
Page is refreshed
![expected result](https://user-images.githubusercontent.com/89202294/139019929-a42d832a-02d8-4742-a9ff-eaa0c9f16c57.jpg)

**Comment by petromonka** [comment]
I have something misunderstood or there is no bug here?
https://user-images.githubusercontent.com/83533040/139542992-e1a14144-d9cd-4cae-bde8-60789d514248.mp4
