### ISSUE TITLE
[Notification] The registered user should not get the notification about 'Поручення'

### ISSUE THREAD

**Issue by ZoryanaKravchuk** [ita-social-projects/EPlast#1988]
**Environment**: Windows 10, Google Chrome 92.0.4515.107
**Reproducible**: always
**Priority**: major
**Severity**: low
**Build found**: f7fdf9c

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log into the system as the Super Admin

**Steps to reproduce**

1.Log into the system
2.In users table find registered user
3.Go to his profile 
4.Give him 'Поручення'
5.Log into the system as registered user
6.Click on 'Сповіщення' icon

**Actual result**
The registered user get the notification about 'Поручення'
![Зареєстрований користувач](https://user-images.githubusercontent.com/87931020/139147026-b54fdb19-51ea-47e4-ae27-48b1eea09bbf.png)
![Сповіщення про поручення (зареєстр  корист )](https://user-images.githubusercontent.com/87931020/139147065-a3028c6c-cbb1-486e-be08-adcbf3d0b871.png)

**Expected result**
The registered user should not get the notification about 'Поручення'

**Comment by Liubov-H** [comment]
The bug is not that the registered user receives a notification. The bug is that the button "Поручитися" is active on the registered user's profile.
![image](https://user-images.githubusercontent.com/50576460/143013044-fdc13321-e6db-4eaf-976b-71c2f312452d.png)
