### ISSUE TITLE
[Cities] [Add administrator] 'Провід станиці'  increases 3 times after adding one administrator on the 'City' page.

### ISSUE THREAD

**Issue by SofiiaYavorivska** [ita-social-projects/EPlast#1993]
**Environment:** Windows 10(x64), Google Chrome Version 95.0.4638.54
**Reproducible:** always
**Priority:** medium.
**Severity:** minor.
**Build found:** 761f28b

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as a City Admin

**Steps to reproduce**
1. Go to 'City' page 
2. Select 'Дрогобич' city
3. Press the button 'Plus ' in the 'Провід станиці'
4. Add some administrator 
5. Pay attention to the number of people in the 'Провід станиці'

**Actual result**
'Провід станиці'  increases 3 times after adding one administrator on the 'City' page.

https://user-images.githubusercontent.com/92793418/139292761-c98a99b7-c46b-4466-9804-d646be3cc61a.mp4

**Expected result**
The added administrator should only be displayed once in the 'Провід станиці'

**Comment by setorianadya** [comment]
The same for "Провід куреня". 
![image](https://user-images.githubusercontent.com/50516451/140322993-1c44f1ab-d761-43d9-a242-af0520f95f7b.png)
