### ISSUE TITLE
[User Profile] Error 403 is shown after clicking 'Редагувати Профіль' button on the User page in the same city as city admin deputy

### ISSUE THREAD

**Issue by NataliiaTsepukh** [ita-social-projects/EPlast#2001]
**Environment**: OS: Windows 10 (x64) Google Chrome 93.0.4577.82
**Reproducible:** always.
**Priority:** High
**Severity:** medium
**Build found:** 327644d

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as the City admin/City admin deputy

**Steps to reproduce**
1. Open your city
2. Open any user page, from your city.
3. Click on the 'Редагувати профіль' button

**Actual result**
 Error 403 is shown after clicking 'Редагувати Профіль' button on User page in the same city
![Screenshot_7](https://user-images.githubusercontent.com/24891698/139826258-999086d1-77c4-47f4-8b4e-3464a0f13980.png)
![Screenshot_6](https://user-images.githubusercontent.com/24891698/139826311-0e5c76e2-ad8c-45b0-964f-bcbf4f3d1b18.png)

**Expected result**
City admin/City admin deputy should have opportunity to edit data on the User page in the same city.

**Comment by petromonka** [comment]
City admin/City admin deputy should NOT have opportunity to edit data on the User page in the same city.
![image](https://user-images.githubusercontent.com/83533040/140039818-60d98ee9-38c0-4515-a081-4f1aebc1f236.png)

**Comment by NataliiaTsepukh** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/24891698/140741543-aadc8726-c4d8-42a2-8e88-dac8edd81a49.png)
requirements is changed
