### ISSUE TITLE
[Hovel] [URL] The page URL does not change after switching between paginations

### ISSUE THREAD

**Issue by SofiiaYavorivska** [ita-social-projects/EPlast#2027]
**Environment:** Windows 10(x64), Google Chrome Version 95.0.4638.54
**Reproducible:** always
**Priority:** medium
**Severity:** minor
**Build found:** ce06295

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as any user

**Steps to reproduce**
1. Go to the 'Hovel' page
2. Switch between paginations
3. Pay attention to the URL on the page

**Actual result** The page URL does not change after switching between paginations

https://user-images.githubusercontent.com/92793418/140659513-f12603f6-1cf9-4d3c-abd7-3a7efb714682.mp4

**Expected result** The page URL should be changed after switching between paginations

**Comment by SofiiaYavorivska** [comment]
And also for cities and countries. 
And wherever there are paginations.

**Comment by SofiiaYavorivska** [comment]
The URL changes but when we push back, it doesn't turn us back.

**Comment by UlianaVarlamova** [comment]
On the build 0cae548 the defect is still reproduced on the following pages:
Decision, 
User table 
Event - in following types: Promotion, Training, Camp
Award,
Warning or precaution,
Senior Staff - on tabs: ' КВ1(УПН)', 'КВ1(УПЮ)', 'КВ2(УПН)', 'КВ2(УПЮ)',
Status recovery, 
Legislation,
Reports and statistics - annual report,
And fixed on the following pages:
City, Hovel, Country
