### ISSUE TITLE
[User's Profile/ Hovel] ' Прихильник' cannot view full profiles of users in his or her Hovel who has access level of adherent

### ISSUE THREAD

**Issue by ZoryanaKravchuk** [ita-social-projects/EPlast#2028]
**Environment**: Windows 10, Google Chrome 92.0.4515.107
**Reproducible**: always
**Priority**: major
**Severity**: low
**Build found**: ce06295

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log into the system as adherent

**Steps to reproduce**

1.Log into the system
2.Go to 'Menu' and choose ' Directory/Довідник'
3.Click on 'Hovels'
4.Choose a hovel ' 43-ій Курінь УПС "Карпатські орли" '
5.Click on anyone user

**Actual result**
' Прихильник' doesn't see full profiles of users in his or her Hovel who has access level of adherent , but  he can see full profiles of full members
![Short profile](https://user-images.githubusercontent.com/87931020/140714372-e3c294ea-d673-4c6f-b242-a71fa320b565.png)

**Expected result**
As per Рівні доступу document, adherent should be able to see a full profile of a users, that belong to his/her Hovel

**Comment by ZoryanaKravchuk** [comment]
**Аlso pay attention to this bug.** 

**Actual result**
Adherent can see full profiles of users that are 'Прихильники куреня' if they have access level of full members.

https://user-images.githubusercontent.com/87931020/140715966-a55f9a0d-bf18-46d0-9cdc-38c2cbd55ed8.mp4

**Expected result**
As per Рівні доступу document, adherent shouldn't  be able to see a full profile of a users, that are 'Прихильники куреня' .

**Comment by ystrotska** [comment]
The bug is still available. Adherent is not able to see a full profile of a users, that belong to his/her Hovel.
![hovel members](https://user-images.githubusercontent.com/104917914/193518861-5e4cf63c-6b6c-46bb-9621-5527c30f2c53.jpg)
![short profile_adherent](https://user-images.githubusercontent.com/104917914/193518886-fb2d7c24-396c-450a-b8b8-ce3dcd5aa8d2.jpg)
