### ISSUE TITLE
[Annual reports] Button "Переглянути у форматі PDF" for hovel's annual reports is not work

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#2030]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always.
**Priority:** medium.
**Severity:** major.
**Build found:** ce06295

**Preconditions:**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Created hovels annual reports.
Log in as hovel admin or Super admin.

**Steps to reproduce:**

1. Go to "Річні звіти"
2. Press the right button on your hovel annual report

**Actual result:**
Button "Переглянути у форматі PDF" for hovel's annual reports is not work
**Expected result:**
Button "Переглянути у форматі PDF" for hovel's annual reports should work

**Comment by VSBalanchuk** [comment]
Dublicate #1882
