### ISSUE TITLE
[City] [Add administrator] The message is not displayed that such a user is already in the 'Провід станиці' on the 'City' page

### ISSUE THREAD

**Issue by SofiiaYavorivska** [ita-social-projects/EPlast#2040]
**Environment:** Windows 10(x64), Google Chrome Version 95.0.4638.54
**Reproducible:** always
**Priority:** medium
**Severity:** minor
**Build found:** 807a152

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as a City Admin

**Steps to reproduce**
1. Go to the 'City' page
2. Select 'Дрогобич' city
3. Press the 'Plus ' button in the 'Провід станиці'
4. Add administrator who already has such a role, only in lower case
5. Pay attention to the absence of a message that such a user already exists

**Actual result:** The message is not displayed that such a user is already in the 'Провід станиці' on the 'City' page

https://user-images.githubusercontent.com/92793418/140969965-b93dcc2e-4040-4615-b65b-1065a9cc5b43.mp4

**Expected result:* The message should be displayed that such a user is already in the 'Провід станиці' on the 'City' page

**Comment by SofiiaYavorivska** [comment]
The message is still not displayed.

https://user-images.githubusercontent.com/92793418/141174416-435e3635-84a3-430b-a617-f6ad5f057d9c.mp4

**Comment by Bodasyuk** [comment]
![image](https://user-images.githubusercontent.com/49231163/142774651-5005fe51-0b40-4197-b463-e9aebdfdfdcb.png)
![image](https://user-images.githubusercontent.com/49231163/142774700-03ce634f-1042-4e50-93af-08ba185f67de.png)
![image](https://user-images.githubusercontent.com/49231163/142774703-cdb9a298-7030-4d57-b038-6602b64ba3af.png)
???
