### ISSUE TITLE
[Awards] invalid error message appears when add award and leave 'Номер в реєстрі' field empty

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#2043]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 95.0.4638.69 (64 bit)
Reproducible: always
Priority: low
Severity: low
Build found: 807a152

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as Super Admin

**Steps to reproduce**

1. Go to 'Відзначення'
2. Click on 'Додати відзначення' button
3. Click 'Опублікувати' button in 'Додати відзначення' pop-up menu

**Actual result**
Unnecessary 'Request failed with status code 400' text appears in error message appears below 'Номер в реєстрі' field
![actual](https://user-images.githubusercontent.com/89202294/141070812-8f73f2a6-8258-4c86-9306-90a55cc02c33.jpg)

**Expected result**
'Поле є обов'язковим' error message appears below 'Номер в реєстрі' field
![expected](https://user-images.githubusercontent.com/89202294/141070821-a50e4c92-7161-43f7-bc9c-5b5114d2f6ca.jpg)

**Comment by christykobyletska** [comment]
similar issue https://github.com/ita-social-projects/EPlast/issues/1810 in Senior Stuff
