### ISSUE TITLE
[Legislation] Incorrect date of the document when typing the date manually

### ISSUE THREAD

**Issue by ZoryanaKravchuk** [ita-social-projects/EPlast#2087]
**Environment**: Windows 10, Google Chrome 92.0.4515.107
**Reproducible**: always
**Priority**: high
**Severity**: low
**Build found**: 988c5b6

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log into the system as the Super Admin

**Steps to reproduce**

1.Log into the system
2.Open left-side menu and click on 'Репозитарій'
3.Fill in all mandatory fields
4.Enter 'Дата документа'  manually
5.Сlick on button 'Опублікувати'
6.Find this document in the search field

**Actual result**
If you enter the date of the document manually, after confirmation it is displayed the day before

https://user-images.githubusercontent.com/87931020/143721396-7719e0ac-c6ba-4a5a-b4a1-085f0d3f060b.mp4

**Expected result**
It should be the same date that user entered

**Comment by Liubov-H** [comment]
Fixed this bug on the pages "Репозитарій", "Рішення" and "Кадра виховників"
