### ISSUE TITLE
[API] [Events] We can enter the forbidden number of participants in the event with Postman

### ISSUE THREAD

**Issue by ZoryanaKravchuk** [ita-social-projects/EPlast#2094]
**Environment**: Windows 10, Google Chrome 92.0.4515.107
**Reproducible**: always
**Priority**: major
**Severity**: low
**Build found**: 988c5b6

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as a user who can add an event

**Steps to reproduce**

1.Click on your name (Choose your user`s page)
2.Choose "Події" menu
3.Open DevTools
4.Press "Створити подію" button (Field "Створення події")
5.Create an event
6.Take URL, bearer token and request body
7.Put information from the previous step into Postman
8.In field "Приблизна кількість учасників" put 1000
9.Press the button "Send" in Postman

**Actual result**
An event with 1000 participants was created
![Учасники події](https://user-images.githubusercontent.com/87931020/143769802-71ca5fcc-2a29-4967-ad21-272c725647f0.png)

**Expected result**
The response that it is forbidden to create an event with 1000 participants  in Postman

**Comment by sysoyeva** [comment]
it is not possible to check with any number of participants

**Comment by bkondrat** [comment]
While reproducing bug I did't see any errors. 
This is what I get while changing the number of participants to 1000:
> {
>     "errors": {
>         "Event.NumberOfPartisipants": [
>             "Value for NumberOfPartisipants must be between 2 and 200."
>         ]
>     },
>     "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
>     "title": "One or more validation errors occurred.",
>     "status": 400,
>     "traceId": "|8debed5e-4ea0d0b265f92cc3."
> }

**Comment by sysoyeva** [comment]
Unable to create event with 1000 participants in Postman
![10](https://user-images.githubusercontent.com/104834042/167915452-4ea3a8e3-d2a3-4f9d-8492-7ab130aa48b1.png)
