### ISSUE TITLE
[Events] [Postman] The start date can be the end date when creating an event via Postman

### ISSUE THREAD

**Issue by SofiiaYavorivska** [ita-social-projects/EPlast#2109]
**Environment:** Windows 10(x64), Google Chrome Version 95.0.4638.54
**Reproducible:** always
**Priority:** low.
**Severity:** minor.
**Build found:** d7dbfd0

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as a user who can add an event

**Steps to reproduce**
1. Click on your name (Choose your user`s page)
2. Choose "Події" menu
3. Open DevTools
4. Press 'Створити подію' button (Field 'Створення події')
5. Create an event
6. Take URL, bearer token and request body
7. Put information from the previous step into Postman
8. Change the start date with the end date 
9. Press the 'Send' button in Postman

**Actual result**
The start date can be the end date when creating an event via Postman

![image](https://user-images.githubusercontent.com/92793418/144315744-0e602ca0-6323-414b-bc44-27f7a8c380a0.png)

**Expected result**
The response that it is forbidden to create an event with end date for start date in Postman

**Comment by SerhijK** [comment]
Please, pay attention, the start date also can be the end date when editing an event via Postman and via graphical user interface
