### ISSUE TITLE
[Event] 400 error appearing after declining deletion for the first time

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#2112]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: medium
**Severity**: low
**Build found**: d7dbfd0

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Go to the upper left side of the main page and choose 'Довідник' --> 'Події' section
2.Open any Event you want (e.g. 'Акція' --> 'Інструкторський Вишкіл' --> 'Оцінювання події'). 
_Please have turned on DevTool at the same time during reproducing this bug_
3.Open photo gallery and try to delete an image (see attached screen below)
4.But when the system asks you about confirmation (_Ви впевнені, що хочете видалити дане фото?_) click on ]Скасувати] button
5.Delete one more time the same image and pay your attention on DevTools response

**Actual result**
**400 error** and warning message '**Не вдалося видалити зображення**' appears

**Expected result**
Any photo should be deleted with an appropriate successful message afterward appearing

**User story and test case links**
![Screenshot at Dec 02 11-34-44](https://user-images.githubusercontent.com/79641118/144396873-2f273a93-c2c3-48d6-b47a-dfae5429d137.png)
![Screenshot at Dec 02 11-35-36](https://user-images.githubusercontent.com/79641118/144396889-830e3b36-0b21-4af9-a7f5-cc90c81fd1b8.png)
![Screenshot at Dec 02 11-36-30](https://user-images.githubusercontent.com/79641118/144396894-f825b1e4-6306-4526-af3d-744758dee67b.png)
![Screenshot at Dec 02 11-40-37](https://user-images.githubusercontent.com/79641118/144396897-ce92bd88-6399-49be-85bc-a1043e1d02bd.png)

**Comment by solomiiatarnavska** [comment]
Maybe it's related with a 'truly' deleting a photo (because when we refresh the page a photo disappearing --> has been deleted). In this case actually we are trying to delete already deleted photo (when we are pressing at first 'Скасувати' and after that are deleting the photo one more time).

**Comment by bkondrat** [comment]
It seems like this bug is the same as #2414.
