### ISSUE TITLE
[Cities/Villages(Станиці)] On selected City/Village page 404 error appears while pressing 'Станиці' link to go back to all the Cities/Villages list

### ISSUE THREAD

**Issue by konstantinlkf** [ita-social-projects/EPlast#2113]
**Environment:** Win 10 Home x64, Chrome (96.0.4664.45 x64), MS Edge (96.0.1054.34 x64), 
Redmi Pro 6, Android 11, Chrome (96.0.4664.45)
**Reproducible:** always
**Build found:** d7dbfd0

**Preconditions**

- Log in using any valid credentials
- Press 'Обрати/змінити станицю'
- Chose any 'Станиця' from the available

**Steps to reproduce**
 Click on  'Станиці' link 

**Actual result**
Transfered to https://eplast.westeurope.cloudapp.azure.com/cities with an 404 error message.

**Expected result**
Get transfered to available 'Станиці' page.

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**

![404 stanytsi](https://user-images.githubusercontent.com/66214500/144396773-89df304a-1490-4b3b-8491-f37e32552f9a.gif)

https://user-images.githubusercontent.com/66214500/144396956-fe869699-8e13-4f80-83fa-1233cde09410.mp4

**Comment by GitNazar** [comment]
Re-testing passed
