### ISSUE TITLE
[Events] The event ends only after the end of the day on which it was scheduled (after 00:00)

### ISSUE THREAD

**Issue by GitNazar** [ita-social-projects/EPlast#2121]
**Environment:** Windows 10 Home (v. 21H1); Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 0c8d17f 
**Priority:** medium.
**Severity:** medium.

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Log in as any User who can create the event (a.g. SuperAdmin).

**Steps to reproduce**
1. Click on the side menu opening tab
2. Click on 'Довідник' 
3. Click on 'Події' 
4. Click on 'Створити подію' 
5. Enter the valid data in all fields.
6. Set the close start time of the event (for example 1 minute from the time the event is created). 
7. Set the end time of the event (for example 1 minute from the time when the event started).
8. Click on 'зберегти подію' button. 
9. Wait till the event's end time will come.

**Actual result**
The event continues. Completed event functionality not available (e.g. event estimation). The event will be completed only after the end of the day on which it took place (after 00:00).

**Expected result**
The event ends when the end time is reached.

**Comment by Svturinina** [comment]
The event we can to evaluate only after the end of the day 
Environment: Windows 10  Google Chrome Version100.0.4896.127  (64-bit)
Reproducible: always
Build found: [4ad6f9a](https://github.com/ita-social-projects/EPlast/commit/4ad6f9adcfc63c77d6ec449ec972f4889b535c3f)
Priority: Low.
Severity: Low
Preconditions

1.Go to https://eplast.westeurope.cloudapp.azure.com/
2.Log in as any User who can create the event (a.g. SuperAdmin).
3.Click on the side menu opening tab
4.Click on 'Довідник'
5.Click on 'Події'
6.Click on 'Створити подію'
7.Enter the valid data in all fields.
8.Set the close start time of the event (for example 1 minute from the time the event is created).
9.Set the end time of the event (for example 1 minute from the time when the event started).
10.Click on 'зберегти подію' button.
11. Wait till the event's end time will come.
Actual result
The event continues. Тhe event can be evaluated only after the completion for 00:00
Expected result
 I can evaluate an event after the end

**Comment by bkondrat** [comment]
Event will finishing now more often, circa 3 hours after the real event time ending.

**Comment by Svturinina** [comment]
The event ends after 3.5hours the end.It is possible to evaluate after 3.5 hours
