### ISSUE TITLE
[Events] The start and end time of the event is not displayed on the event information page

### ISSUE THREAD

**Issue by GitNazar** [ita-social-projects/EPlast#2122]
**Environment:** Windows 10 Home (v. 21H1); Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 0c8d17f 
**Priority:** medium.
**Severity:** medium.

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Log in as any User who can view the event information page (a.g. SuperAdmin).

**Steps to reproduce**
1. Go to 'Події' tab.
2. Click on 'Список' at 'Відвідані події'.
3. Click on 'Деталі' at any event. (a.g. "Не видаляти").
4. Pay attention to the fields "Дата завершення" та "Дата початку". 

**Actual result**
Only date information indicated in "Дата завершення" та "Дата початку" fields. 

![2](https://user-images.githubusercontent.com/89203891/144745930-f87621d3-6edf-4805-b852-ab745197861d.png)

**Expected result**
Time and date information indicated in "Дата завершення" та "Дата початку" fields. 
"Дата завершення" та "Дата початку" fields named "Дата **і час** завершення" та "Дата **і час** початку".

**Comment by GitNazar** [comment]
It does not matter whether the event is completed or not and whether the event is approved or not.

**Comment by Hrystyna96** [comment]
"Дата завершення" та "Дата початку" fields should be named "Дата і час завершення" та "Дата і час початку".
