### ISSUE TITLE
[Region] Admin have no possibility to transfer Cities-Adherent to Real Members

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#2130]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: high
**Severity**: high
**Build found**: 0c8d17f

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a **Region Admin** (**Голова Округи**)

**Steps to reproduce**
1.Go to the upper left side of the main page and choose 'Довідник' --> 'Округи' section
2.Open that Region you are an Admin (in my case -- Вінницька округа)
3.Pay attention to the Cities which are an Adherents of your Region (**Станиці-Прихильники Округи**)

**Actual result**
There is no possibility to add any City-Adherent to a relly Members of a Region

**Expected result**
Admin should have this possibility via '+' icon or any other functionality (see business rules screened below)

**User story and test case links**
![Screenshot at Dec 05 21-23-32](https://user-images.githubusercontent.com/79641118/144760651-75fcef5b-aeeb-4acc-832e-f38e27c96293.png)
![Screenshot at Dec 05 21-24-36](https://user-images.githubusercontent.com/79641118/144760656-b153a855-70c7-4bbe-888e-0e0bf8a659ab.png)
![Screenshot at Dec 05 21-26-07](https://user-images.githubusercontent.com/79641118/144760657-3d6e85dd-9703-41b5-ae53-e5e2eb731fd9.png)

**Comment by Navrotska** [comment]
possibility to add to the members occurs after opening the exact adherent (so that Region Admin sees information about each Adherent and then decides whether to add or no). 

![Знімок екрана 2022-05-05 о 22 50 52](https://user-images.githubusercontent.com/104829795/167014579-2bb2a24a-bd17-4ef9-afc7-e92318932d86.png)
