### ISSUE TITLE
[Governing Body] The name of the Governing Body cannot be longer than 50 characters

### ISSUE THREAD

**Issue by ZoryanaKravchuk** [ita-social-projects/EPlast#2133]
**Environment**: Windows 10, Google Chrome 92.0.4515.107
**Reproducible:** always
**Priority**: high
**Severity**: high
**Build found:** 0c8d17f

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log into the system as the Super Admin

**Steps to reproduce**

1.Log into the system
2.Open left-side menu and click on 'Крайовий Провід Пласту'
3.Click on icon '+'
4.Fill in the name of the Governing Body

**Actual result**
![Створення Керівного Органу](https://user-images.githubusercontent.com/87931020/144763388-abae05da-6a8c-454e-85bd-e3fdc0d7ce1a.png)

**Expected result**
The name of the Governing Body should be longer than 50 characters

**Comment by 0l9h** [comment]
@ZoryanaKravchuk, what should be the maximum length of governing body name?
