### ISSUE TITLE
[Statistics] Blocked indicators in 'показники' field in the second attempt to generate statistics

### ISSUE THREAD

**Issue by GitNazar** [ita-social-projects/EPlast#2144]
**Environment:** Windows 10 Home (v. 21H1); Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** bba2bd4
**Priority:** medium
**Severity:** medium

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Log in as any User who can view Statistic (a.g. SuperAdmin). 

**Steps to reproduce**
1. Click on the side menu opening tab
2. Click on 'Довідник' 
3. Click on 'Звітування та статистика' 
4. Click on 'Статистика'
5. Click on 'Статистика станиць' or 'статистика округ'
6. Select different parameters in 'Показники' field (e.g. three different parameters) 
7. Click on 'Сформувати' button
8. Click on 'Очистити' button 
9. Try to enter some another parameters in 'Показники' field

**Actual result**
Some indicators in 'показники' field are blocked by default. 

**Expected result**
Indicators in 'показники' field are not blocked by default. 

![9](https://user-images.githubusercontent.com/89203891/145085696-ddef8c74-8f70-4715-8d55-38706975cbc6.png)

**Comment by Daryna-del** [comment]
Idental bug https://github.com/ita-social-projects/EPlast/issues/1521
