### ISSUE TITLE
[Events] quantity of event participants increase when user apply for event and has not been yet confirmed

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#2156]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 96.0.4664.93 (64 bit)
Reproducible: always
Priority: medium
Severity: low
Build found: 6b2ff73

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as any User (except Registered user)

**Steps to reproduce**

1. Go to 'Події'
2. Choose category of event
3. Choose any active event
4. Click on 'Зголоситись на подію' button
5. Refresh the page

**Actual result**
Quantity of event participants increased
![actual](https://user-images.githubusercontent.com/89202294/145433614-2922ce28-8ec5-4053-9a40-cc54c60698b7.png)

**Expected result**
Quantity of event participants is not increased
![expected](https://user-images.githubusercontent.com/89202294/145433626-fb8cacee-3f18-44e3-abab-d73598ec8b76.png)

**Comment by Svturinina** [comment]
![Screenshot_63](https://user-images.githubusercontent.com/95656837/167291918-000454a0-f1e4-4daa-b072-b7f0fb1e2174.png)
![Screenshot_64](https://user-images.githubusercontent.com/95656837/167291922-80ed5bf0-02e5-487a-8009-707f4a077538.png)
