### ISSUE TITLE
[Cities] 'Редагування станиці' form appears with empty fields when click on 'Редагувати' button in 'Станиця' section

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#2176]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 96.0.4664.110 (64 bit)
Reproducible: always
Priority: high
Severity: low
Build found: 9b45cc5

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as Super Admin

**Steps to reproduce**

1. Go to 'Станиці'
2. Choose some City
3. Click on 'Редагувати' button in 'Станиця' section

**Actual result**
'Редагування станиці' form appears with empty fields
![actual](https://user-images.githubusercontent.com/89202294/146069643-4a66b6aa-8db7-49f0-91c5-65ad3d8912c2.jpg)

**Expected result**
'Редагування станиці' form appears with filled fields

**Comment by SerhijK** [comment]
'Редагування станиці' form appears with filled fields when click on 'Редагувати' button in 'Станиця' section. But we do not have an opportunity to edit a City now. Error with status 500 appears
![edit City](https://user-images.githubusercontent.com/89202294/147389731-8c3a13eb-808f-4266-afd3-07c845223487.jpg)

**Comment by solomiiatarnavska** [comment]
Hi there,
Please olso pay your attention on downloading a new City photo (any photo you've decided to download).

When we (Super Admin) is trying to _download an image_ -- _500_ error has been appeared.
_[Підтвердити]_ button is unactive as well.
![Screenshot at Dec 29 10-38-46](https://user-images.githubusercontent.com/79641118/147643223-9002c373-fb48-4eba-9676-4247863ed501.png)
![Screenshot at Dec 29 10-41-41](https://user-images.githubusercontent.com/79641118/147643374-7a2ca6c0-6123-445b-a55b-a3dc0ee04018.png)

**Comment by solomiiatarnavska** [comment]
![Screenshot at Dec 22 21-41-24](https://user-images.githubusercontent.com/79641118/147643445-e908b8c8-cb6b-4be6-977d-cfca7d323909.png)
 Test data -- this screen you can use as a new City image
