### ISSUE TITLE
[Annual reports] 'Звіти в моєму розпорядженні' button does not work correctly for Deputy of City/Hovel/Country Admin

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#2177]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 96.0.4664.110 (64 bit)
Reproducible: always
Priority: high
Severity: low
Build found: 9b45cc5

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as Deputy of City/Hovel/Country Admin

**Steps to reproduce**
1. Go to 'Річні звіти'
2. If there are no City/Hovel/Country annual report where your User is Deputy of Admin, click on 'Подати річний звіт станиці/куреня/округи' button
3. Fill in all mandatory fields
4. Click on 'Подати річний звіт' button
5. Click on 'Звіти в моєму розпорядженні' button on 'Річні звіти станиць/куренів/округ' tab

**Actual result**
City, Hovel and Country annual reports are not shown for Deputy of City/Hovel/Country Admin
![actual1](https://user-images.githubusercontent.com/89202294/146070015-1116a5d2-c7f9-4966-a32c-ed6d443b5acb.jpg)

Sometimes Hovel annual report is shown for current and previous Hovel where your user is/were Deputy of Hovel Admin
![actual2](https://user-images.githubusercontent.com/89202294/146070025-bf379e1b-0c3c-4a54-a06f-29deb2501600.jpg)

**Expected result**
Current City/Hovel/Country annual reports are shown for Deputy of City/Hovel/Country Admin

**Comment by Hrystyna96** [comment]
City, Hovel and Country annual reports are not shown for Deputy of City/Hovel/Country Admin.

![Звіти станиць](https://user-images.githubusercontent.com/96823023/158698278-0cea49d0-dda2-4ef5-867b-b6f9987aa2a9.png)
![Звіти станиць1](https://user-images.githubusercontent.com/96823023/158698291-56778c5d-4db3-4d8d-a42b-3a2a683a176e.png)

![Звіти станиць2](https://user-images.githubusercontent.com/96823023/158698635-88cf2fb7-9a1d-495d-a2f0-22a55793f6d4.png)
![Звіти станиць3](https://user-images.githubusercontent.com/96823023/158698655-d0ab1a7c-bf8f-4391-8092-98e072d0d71b.png)
