### ISSUE TITLE
[Region] 500 error after a new (typed) role assigning

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#2199]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: high
**Severity**: high
**Build found**: 50a9def

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Open left-side menu and click on 'Довідник' section and choose 'Округи' section afterward
2.Open it
3.Find any Region you want and open it (_e.g. Тернопільська округа_)
4.Using the + button assign any user from the suggested list a new role (e.g. _tester_, just FYI -- according to our business rules, Admin and Region admin have a possibility to type any role they want via keyboard) (see attached screen below)
5.During all these steps execution please have DevTools opened   
6.Press [Опублікувати] button and pay attention to a DevTools (Network) response

**Actual result**
_500 error_ has appeared and [Опублікувати] button is working

**Expected result**
No one error message should be present and Admin should have a possibility of a new role assigning successfully

**User story and test case links**
![Screenshot at Dec 22 21-06-40](https://user-images.githubusercontent.com/79641118/147143396-f310d0cc-b816-4e8a-add4-ffe2b7bd1af2.png)
![Screenshot at Dec 22 21-08-09](https://user-images.githubusercontent.com/79641118/147143402-7ff98236-cfbf-473d-9a67-da844881216b.png)
![Screenshot at Dec 22 21-09-13](https://user-images.githubusercontent.com/79641118/147143405-d91952ee-c69f-4c5e-ac55-595a7578058b.png)
![Screenshot at Dec 22 21-10-04](https://user-images.githubusercontent.com/79641118/147143408-257fd0c0-65d7-4927-bb54-8c7b1a12cf5f.png)

**Comment by Hrystyna96** [comment]
500 error has appeared and [Опублікувати] button is working
![Додати діловода](https://user-images.githubusercontent.com/96823023/158693052-eba0406d-22b0-4778-a4e8-1c5f4125376a.png)
