### ISSUE TITLE
[Region/Region Board] {Колишні діловодства округи} does not list previously gotten roles

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#2201]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: high
**Severity**: high
**Build found**: 50a9def

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Open left-side menu and click on 'Довідник' section and choose 'Округи' section afterward
2.Open it
3.Find any Region you want and open it (e.g. _Тернопільська округа_)
4.Go to the Region board and using _[x]_ button delete any user from obtained role (see attached screen below). 
!!! _But open his/her personal profile at first and pay attention on {Діловодства} section. By default, the role user obtains is listed in the Current Board list {Дійсні діловодства округи}_
5.Open user's profile and check his/her {Діловодства} section

**Actual result**
There is no information mentioned on Previous Board list {Колишні діловодства округи}. Because by default, when a user is deleted from a Board, his/her notices about the obtained role is shifting to {Колишні діловодства округи}

**Expected result**
Corresponding notices about the previously obtained role should be listed in {Колишні діловодства округи} section

**User story and test case links**
![Screenshot at Dec 22 21-39-08](https://user-images.githubusercontent.com/79641118/147146947-ed9c8493-76c8-4252-99fb-06fe32c16f69.png)
![Screenshot at Dec 22 21-40-31](https://user-images.githubusercontent.com/79641118/147146960-e73be263-3b84-43c2-823c-db9c1e79a855.png)
![Screenshot at Dec 22 21-41-24](https://user-images.githubusercontent.com/79641118/147146966-fc6fcbef-8bfe-4818-8284-d98a5e00ca5a.png)
![Screenshot at Dec 22 21-42-14](https://user-images.githubusercontent.com/79641118/147146967-32c5522c-3320-476d-ab61-963a4c9919e0.png)
![Screenshot at Dec 22 21-43-19](https://user-images.githubusercontent.com/79641118/147146969-914a889b-f684-4d9e-a626-639c62b66e2a.png)
![Screenshot at Dec 22 21-44-14](https://user-images.githubusercontent.com/79641118/147146972-93aa6e00-4ae9-41d8-9cb2-0cd969630825.png)

**Comment by Hrystyna96** [comment]
[Region/Region Board] 'Колишні діловодства округи still' does not list previously gotten roles

**Comment by Hrystyna96** [comment]
On the 'Кінець каденції' field ( 'Колишні діловодства округи' page) the end date of the cadence doesn't appear after deleting a user from the obtained role.
![Каденція незавершена](https://user-images.githubusercontent.com/96823023/160382250-f932963d-7721-44eb-a7d5-befc0ecf0c36.png)

**Comment by Goven112** [comment]
retested it . All right
