### ISSUE TITLE
[Cities] superfluous pop-up menu appears when edit 'Час кінця' for user that is in 'Провід станиці' section

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#2216]
Environment: Windows 10 Home 64 bit 1903, Google Chrome Version 96.0.4664.110 (64 bit)
Reproducible: always
Priority: medium
Severity: low
Build found: b4b7a94

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as Super Admin

**Steps to reproduce**

1. Go to 'Станиці'
2. Choose City where there are members
3. If there are no user in 'Провід станиці' section, add someone
4. Click on 'Більше' button in 'Провід станиці' section
5. Click on edit button on some user then change his 'Час кінця'

**Actual result**

- Superfluous pop-up menu 'Призначити даного користувача на цю посаду?' appears
- 'Час кінця' is changed
- Notification 'Адміністратор успішно відредагований' appears

https://user-images.githubusercontent.com/89202294/147412653-29b77fe8-9870-4342-8e8d-6a9f5446441f.mp4

**Expected result**

- 'Час кінця' is changed
- Notification 'Адміністратор успішно відредагований' appears. The behaivor is the same as in Countries and Hovels

https://user-images.githubusercontent.com/89202294/147412657-3f524c18-6eca-429b-b11b-3a58def3db0a.mp4

**Comment by Svturinina** [comment]
Аlso pay attention to this bug.
Pop-up window with incorrect information
Actual result
![image](https://user-images.githubusercontent.com/95656837/172062424-5f60de74-bc1f-463f-8614-25f997fec370.png)
Expected result 
the same pop-up as in the 'Курені '
![image](https://user-images.githubusercontent.com/95656837/172062526-7820f550-7481-4bed-9f95-95db3e9badd8.png)
