### ISSUE TITLE
[API Profile] Registered user, Adherent and Plast member have opportunity to add 'Життєпис', 'Виписка з УПЮ' and 'Досягнення' in 'Бланки' tab for another user

### ISSUE THREAD

**Issue by SerhijK** [ita-social-projects/EPlast#2217]
Environment: Windows 10 Home 64 bit 1903, Postman Version 9.3.1
Reproducible: always
Priority: medium
Severity: low
Build found: b4b7a94

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as Super Admin

**Steps to reproduse**

1. Go to 'Таблиця користувачів' and choose some Adherent or Plast member  
2. Click on 'Бланки' then press 'F12' button (choose 'Network' tab)
3. If there is some 'Життєпис', 'Виписка з УПЮ' and 'Досягнення', delete it
4. Click on 'Додати Життєпис' button, then add some 'Житєпис'
5. Choose request that has POST method then take URL and request body and put it into Postman
6. Delete 'Життєпис' by clicking on 'Видалити життєпис' button
7. Log in as Registered user/Adherent/Plast member
8. Take bearer token then put it into Postman then click 'Send' button in Postman
9. Repeat 4-8 steps for 'Виписка з УПЮ' and 'Досягнення'

**Actual result**
'Життєпис', 'Виписка з УПЮ' and 'Досягнення' is added
![actual](https://user-images.githubusercontent.com/89202294/147412938-656434f2-4c1a-4c80-8486-cb47931f7579.jpg)

**Expected result**
403 error appears for users with Registered user, Adherent and Plast member token that want add 'Життєпис', 'Виписка з УПЮ' and 'Досягнення' for another user by using Postman

**Comment by MishaHMK** [comment]
Bug does not reproduce on deploy
