### ISSUE TITLE
[Announcement] is absent in general list despite successful message has been appeared

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#2228]
**Environment**: macOS 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: high
**Severity**: high
**Build found**: 4bf0a21

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com
Log into the system as a Super Admin (Княгиня Ольга)

**Steps to reproduce**
1.Open left-side menu and click on '_Крайовий Провід Пласту_' section
2.Open it and find any _Керівний Орган_ and open it as well (e.g. kkkkkk)
3.In [_Оголошення_] section try to add a new Оголошення typing spaces (**пробіли**) and press [Опублікувати] button
4.New Оголошення has been created (see bell in the upper right corner of a profile) and open it for more detailed information
5.Go to [Оголошення] section and try to find yours

**Actual result**
Despite you have added a new Announcement, it's absent in the general list

**Expected result**
A new Announcement should be listed in general pool

**User story and test case links**
![Screenshot at Dec 29 12-19-52](https://user-images.githubusercontent.com/79641118/147654241-38a75346-fd7a-4ae2-927e-93967394fae1.png)
![Screenshot at Dec 29 12-21-19](https://user-images.githubusercontent.com/79641118/147654249-9f32f33f-e752-46ea-a1c7-8a6e7a2f63e6.png)
![Screenshot at Dec 29 12-21-56](https://user-images.githubusercontent.com/79641118/147654251-a757aeed-71fa-45ad-81a1-d691d4abf6a2.png)
![Screenshot at Dec 29 12-22-50](https://user-images.githubusercontent.com/79641118/147654252-309a6ad1-d02f-4392-b807-bd22d3dddc81.png)
![Screenshot at Dec 29 12-23-26](https://user-images.githubusercontent.com/79641118/147654254-02e57a19-915b-4069-87c5-7a790f55126a.png)
![Screenshot at Dec 29 12-44-07](https://user-images.githubusercontent.com/79641118/147654255-5ccb6084-e057-4e9e-a209-46b3267f08a3.png)

**Comment by solomiiatarnavska** [comment]
Hi Illya!

Thanks for fixing!
Hope you are doing well :)

Please have a look at a possibility to create an announcement using spaces (пробіли)

Thank you!
![Screenshot at Jan 27 12-02-28](https://user-images.githubusercontent.com/79641118/151336872-d872ff0d-aeb2-4355-9f46-d6631fa418a2.png)

**Comment by Navrotska** [comment]
It is still possible to create announcements by using spaces
 
![Знімок екрана 2022-05-05 о 22 34 32](https://user-images.githubusercontent.com/104829795/167012081-a0fd1875-597b-430e-b417-3d1bb422e24d.png)

**Comment by NataliyaDominyuk** [comment]
We are creating an announcement using spaces in 'Тема оголошення' and 'Tекст оголошення'. After clicking 'Опублікувати' button we are getting continuous loading process and 400 error (response "Title and Text fields are required")
<img width="1434" alt="Screenshot 2022-07-09 at 15 00 09" src="https://user-images.githubusercontent.com/104838173/178104727-aa9d95a6-ecf5-4910-8f53-33f911c90e81.png">
