### ISSUE TITLE
[Cities] 'Станиця' is archived after being created

### ISSUE THREAD

**Issue by oliakalymon** [ita-social-projects/EPlast#2258]
**Environment:** Microsoft Windows 10 v.20H2; Google Chrome v.97.0.4692.71 (64 bit)
**Reproducible:** always
**Build found:** 89e786e
**Priority:** High
**Severity:** Major

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log in as Admin (Email: admin@eplast.com Password: Pq!83874)

**Steps to reproduce:**
1. Go to the 'Станиці' page
2. Click on 'Створити нову станицю'
3. Fill in the necessary fields
4. Click on 'Створити' button

**Actual result**
A city is created and archived. It is displayed on 'Неактивні станиці' page.
![archived city](https://user-images.githubusercontent.com/96819733/148788020-ba83098d-cbc6-43ef-b4ea-b3d036daee0f.jpg)

**Expected result**
A city should be created and displayed on 'Станиці' page.

**Comment by tvardero** [comment]
https://github.com/ita-social-projects/EPlast/pull/2499

**Comment by Svturinina** [comment]
Defect fixed
