### ISSUE TITLE
[Governing Body's Sectors] There is no '+' button on the announcement

### ISSUE THREAD

**Issue by ZoryanaKravchuk** [ita-social-projects/EPlast#2269]
**Environment**: Windows 10, Google Chrome 92.0.4515.107
**Reproducible**: always
**Priority**: high
**Severity**: minor
**Build found**: 1747a83

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log into the system as the Super Admin

**Steps to reproduce**

1.Log into the system
2.Open left-side menu and click on 'Крайовий Провід Пласту'
3.Choose 'Governing Body' with 'Governing Body's Sectors'

**Actual result**
The '+' button is absent on the announcement

**Expected result**
The '+' button should be on the announcement

**Comment by Svturinina** [comment]
Button '+' is present 
![Screenshot_62](https://user-images.githubusercontent.com/95656837/167252876-cf675b12-7041-43b3-9434-38dda54c29bf.png)
