### ISSUE TITLE
[Annual Reports / Річні звіти] The active 'Переглянути' button appears in the 'Річні звіти' page after clicking on a report from a different Region.

### ISSUE THREAD

**Issue by Hrystyna96** [ita-social-projects/EPlast#2292]
**Environment:** Windows 10 Pro; Google Chrome 96.0.4664.110 x64.
**Reproducible:** always.
**Priority:** medium
**Severity:** low
**Build found:** 94ec42f .

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com.
Log into the system as a Region Admin (Окружний Адмін).

**Steps to reproduce**

1. Click on 'Звітування та статистика' button.
2. Go to 'Річні звіти' page.
3. Click on the annual report of your region.
4. Click on the annual report of not your region.
5. Pay attention to the 'Переглянути' button that appears.
5. Quickly click on the "Переглянути" button.

**Actual result**
The active 'Переглянути' button appears in the 'Річні звіти' page after clicking on a report from a different Region.

https://user-images.githubusercontent.com/96823023/151061227-bf11ad69-80dc-4222-a838-8918bbdc6d88.mp4

**Expected result**
The Region Admin can view the annual reports only of his Region.

**Comment by Svturinina** [comment]
Defect fixed
