### ISSUE TITLE
[User Table] The user becomes broken if it gains access rights of Adherent when the Regions and Hovel are not selected

### ISSUE THREAD

**Issue by UlianaVarlamova** [ita-social-projects/EPlast#2298]
**Environment:** Windows 10, Google Chrome Version 96.0.4664.110 (Official Build) (64-bit)
**Reproducible:** always
**Priority:** medium
**Severity:** high
**Build found:** 114ead9

**Preconditions:**

Go to https://eplast.westeurope.cloudapp.azure.com
login as any user who has access to change the current state of the user via the 'User Table'

**Steps to reproduce:**

1. Go to the 'Users Table' page
2. Click on any user who has access rights 'Зареєстрований користувач' but hasn't chosen the Regions and Hovel 
3. Right-click and select 'Поточний стан користувача' and click on 'Прихильник' item from the dropdown list
4. Reload the page and find the same user

**Actual result:**
All user access rights removed (the "Access rights" column is blank)
It is not possible to change any access rights to this user.
If the user logs in to the system the 403 error appears.

**Expected result:**
It shouldn't be possible to grant access rights of Adherent when the Regions and Hovell are not selected. 
Exist access rights of the user should not be deleted.

![users table](https://user-images.githubusercontent.com/96615514/151386726-af61c9fd-b244-4733-838b-d610d5e00367.png)

**Comment by Omeliukh-Nazar** [comment]
Retest, 
![image](https://user-images.githubusercontent.com/91065958/175916193-09a41716-e621-433f-8759-575a9c444181.png)
