### ISSUE TITLE
[Search field][Regions][Hovel][City] Cannot find Region in serch field if user is not on the first page of pagination list

### ISSUE THREAD

**Issue by UlianaVarlamova** [ita-social-projects/EPlast#2299]
**Environment:** Windows 10, Google Chrome Version 96.0.4664.110 (Official Build) (64-bit)
**Reproducible:** always
**Priority:** medium
**Severity:** high
**Build found:** a7278c1

**Preconditions:**

Go to https://eplast.westeurope.cloudapp.azure.com
login as any user who has access to the Regions page

**Steps to reproduce:**

1. Go to the 'Regions'or 'Hovel' or 'City' pages
2. Click on the second page ( or any other pages except first) on pagination buttons
3. Enter the name of any existing Region/Hovel/City in the search field and click the 'Find' button (e. g. Закарпатська)

**Actual result:**
The Region/Hovel/City is not found and the message 'Округу/Станицю/Курінь не знайдено' is shown.

**Expected result:**
The Region/Hovel/City is found and shown.

![defect search field](https://user-images.githubusercontent.com/96615514/151415046-ea4a894d-69bb-487b-8f31-73ab910d2ee1.png)

**Comment by sysoyeva** [comment]
The Region/Hovel/City is found and shown.
![3](https://user-images.githubusercontent.com/104834042/175822116-4ef60690-231a-49a1-879e-0137e2198ef0.png)
