### ISSUE TITLE
[Hovel Admin] Cannot assign a new Hovel Admin  if  the current Hovel Admin has the 'End of cadence' set to "Not completed"

### ISSUE THREAD

**Issue by UlianaVarlamova** [ita-social-projects/EPlast#2300]
**Environment:** Windows 10, Google Chrome Version 96.0.4664.110 (Official Build) (64-bit)
**Reproducible:** always
**Priority:** medium
**Severity:** high
**Build found:** a7278c1

**Preconditions:**

Go to https://eplast.westeurope.cloudapp.azure.com
login as  Super Admin
The Hovel has several members 
Assign to the Hovel 'Hovel admin' and set the 'End of cadence' to "Not completed"

**Steps to reproduce:**
1. Go to the 'Users table' pages
2. Find any member of Hovel and open context menu 
3. Choose 'Провід куреня'
4.  Select 'Hovel Admin' from 'Виберіть тип адміністрування' dropdown list
5. Set current date in 'Час початку' and  any date in a future in 'Час кінця' fields
6. Click 'Опублукувати' button  
7. Go to hte Hovel and check if the Hovel Admin was changed 

**Actual result:**
Hovel Admin isn't canged.
Users table shows two Hovel Admins assigned to the Hovel

**Expected result:**
Hovel Admin is changed.
Users table shows only new Hovel Admin assigned to the Hovel.

![Admin Hivel](https://user-images.githubusercontent.com/96615514/151437399-03ef489f-baa2-4b43-9ba2-5dc3d83a122f.png)

**Comment by sysoyeva** [comment]
Several users still can have one position 'Hovel Admin'
![1](https://user-images.githubusercontent.com/104834042/170998622-70465b8b-4a9b-4f46-9361-ec82ed699a94.png)
