### ISSUE TITLE
[Test case] [Regional Board of the Plast] Verify if the user can browse available to him sections ''Крайовий Провід Пласту' page, with access rights 'unconfirmed' or 'adherent' user.

### ISSUE THREAD

**Issue by UlianaVarlamova** [ita-social-projects/EPlast#2336]
**Preconditions:**
Log into the system as a user who has access rights like 'unconfirmed' or 'adherent' user.
e. g. Login: prihilniks@gmail.com, Password: Qwerty1)

**Test steps:**

1. Go to the main menu and click on 'Крайовий Провід Пласту' item
2. Verify if the following sections are present (according to the mockup):
- 'Крайовий Провід Пласту' section (the basic information)
- 'Опис' section (the description of the activity and responsibilities of the Regional Board)
- 'Керівні органи' section (the governing bodies of the Крайовий Провід)
-  'Документообіг' section (the relevant documents)
3.  Verify if the following section is not present (according to the mockup): 
- 'Рішення' section (the latest decisions the 'Крайовий Провід' has made)

**Expected result:**
The following sections are displayed according to the mockup.

**User story link:**
E.g.: "User story https://github.com/ita-social-projects/EPlast/issues/833
![mockup2](https://user-images.githubusercontent.com/96615514/153773420-075accb0-c3e6-49fc-b652-9f4158db5b88.png)

**Comment by ystrotska** [comment]
As to new requirements, the registered and unconfirmed users should not have access to the "Крайовий Провід Пласту"
