### ISSUE TITLE
[Events] We can create event with start and end dates in the past in Postman

### ISSUE THREAD

**Issue by Navrotska** [ita-social-projects/EPlast#2385]
**Environment:** Mac OS Monterey 12.0.1, Chrome 101.0.4951.54 (x86_64), Postman 9.15.2
**Reproducible:** always
**Build found:** [4ad6f9a](https://github.com/ita-social-projects/EPlast/commit/4ad6f9adcfc63c77d6ec449ec972f4889b535c3f)
Priority: low.
Severity: minor

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as a user who can add an event

**Steps to reproduce**

1. Click on your name (Choose your user`s page)
2. Choose "Події" menu
3. Open DevTools
4. Press "Створити подію" button (Field "Створення події")
5. Create an event
6. Take URL, bearer token and request body
7. Put information from the previous step into Postman
8. In field "eventDateStart" insert date in the past
9. In field "eventDateEnd" insert date in the past
10. Press the button "Send" in Postman

![Знімок екрана 2022-05-05 о 15 39 13](https://user-images.githubusercontent.com/104829795/166928818-dcae0b33-9b3c-404e-a2f4-677d2e1040c5.png)

**Actual result**
An event with start and end date in the past is created

**Expected result**
The response that it is forbidden to create an event with dates in the past

**Comment by sysoyeva** [comment]
![1](https://user-images.githubusercontent.com/104834042/174753962-de514e09-7e4f-42fe-b3fd-b2092e16024e.png)
