### ISSUE TITLE
[Documentation/Документообіг]  'Attach file' button is active on the "Documentation/Докyментообіг" window in Regional Board of the Plast

### ISSUE THREAD

**Issue by ystrotska** [ita-social-projects/EPlast#2391]
**Environment:** Windows 10 64-bit , Google Chrome, Version 99.0.4844.82
**Reproducible:** always
**Build found:** last commit from[4ad6f9a](https://github.com/ita-social-projects/EPlast/commit/4ad6f9adcfc63c77d6ec449ec972f4889b535c3f)

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log into the system as a Country Admin ( Голова Округи)

**Steps to reproduce**
1. Open the left-side menu
2. Click on the 'Regional Board of the Plast/Крайовий Провід Пласту' button in the menu.
3. Scroll down to the 'Documentation/Докyментообіг'  window
4. Verify the active  '+' option near the "More/Більше" button on the right down corner of the window
5. Click on the "+" button to verify the pop-up window for attaching a new file is displayed

**Actual result**
 'Attach file' button is active on the "Documentation/Докyментообіг" window in the Regional Board of the Plast

**Expected result**
 'Attach file' button is not active on the "Documentation/Докyментообіг" window in the Regional Board of the Plast

**User story and test case links**
[attach file.odt](https://github.com/ita-social-projects/EPlast/files/8643234/attach.file.odt)

**Labels to be added**
"Bug" ("bug"), Priority ("pri: ")

**Comment by Omeliukh-Nazar** [comment]
Retest, please. Check that the user has no other roles except Region admin.
