### ISSUE TITLE
[Table of users / Таблиця користувачів] User, who is not a member of the hovel, is visible in the table

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2407]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 4ad6f9adcfc63c77d6ec449ec972f4889b535c3f
**Priority:** medium
**Severity:** major

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as head of the hovel (glavahovel@gmail.com)

**Steps to reproduce**
1. Go to menu 'Довідник'
2. Click on 'Table of users / Таблиця користувачів' section 
3. Look at user №682

**Actual result**
User №682 is in the table, but she is not a member of the hovel

**Expected result**
User, who is not a member of the hovel, shouldn't be seen in the tabl
![user not from the hovel shouldn't be visible](https://user-images.githubusercontent.com/104838173/167473952-723e6590-b90b-4ab1-9b21-100e542fd665.jpg)

**Comment by NatalyMinziuk** [comment]
head of the hovel can see member of his city as plast member.
