### ISSUE TITLE
[City/Village] Region Admin can't to archive 'Станицю'

### ISSUE THREAD

**Issue by sysoyeva** [ita-social-projects/EPlast#2494]
**Environment:** Windows 10 Google Chrome 99.0.4844.82 64-bit
**Reproduce:** always
**Priority:** medium
**Severity:** high
**Build found:**[6e54a11](https://github.com/ita-social-projects/EPlast/commit/6e54a11ac0050faeb9d5fa985e49982b2caa0712)

**Preconditions**
Log into the system as Region Admin
With the left-side menu open page 'Станиці'

**Steps to reproduce**
1. Click on any pre-created 'Станиця' and user is redirected to the chosen ‘Станиця’ page.
2. Click on the button 'Архівувати'
3. Choose one of two options- 'Так,заархівувати'
![1](https://user-images.githubusercontent.com/104834042/170047821-d3692035-ddbc-409b-9210-0751fa97e861.png)

**Actual result**
Region Admin after clicking 'Так,заархівувати' is redirected and he see error 403
![2](https://user-images.githubusercontent.com/104834042/170047703-3aea1308-33f0-4302-9070-a1fbcc151803.png)

**Expected result**
Region Admin if necessary, has the opportunity to archive 'Станицю'

**Comment by Goven112** [comment]
![image](https://user-images.githubusercontent.com/60715039/174083651-29d31d79-2fc5-4815-8be0-ecdbaba93d4e.png)

**Comment by sysoyeva** [comment]
The previous actual result is not correct.
User have possible to press the button "Архівувати станицю" , but he should not have possible to do this.
Region Admin only has access to this functionality for those Cities that are part of his Region.
![1](https://user-images.githubusercontent.com/104834042/185189312-d9701784-dad8-4ef5-b99e-c8c45870bb91.png)
