### ISSUE TITLE
[Notifications/Сповіщення] [Delegation/Поручення][Adherent/Прихильник] No link to the user's personal profile in the notification by mail

### ISSUE THREAD

**Issue by MariyaKonsevych** [ita-social-projects/EPlast#2504]
**Environment:** Windows 10 Enterprise 64-bit operating system, browser, Google Chrome Версія 101.0.4951.54 (Розробка) (64-розрядна версія).
**Reproducible:** always.
**Build found:** 00a5ac0.
**Priority:** Low
**Severity:** Low

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/
Log in as Adherent.
Adherent already got a guarantee from a Plast member (Hovel admin etc.).

**Steps to reproduce**
1. Check the notification on the e-mail from EPlast <eplast.pysar@gmail.com>.
2. Click on this email to see all text of the notification.
3. Find the name of the Plast member to see that there is no link to the user's personal profile:
![image](https://user-images.githubusercontent.com/104513228/170452320-728caa17-3840-4e9b-a25b-b7b30c68bd0f.png)

**The situation is the same when somebody revokes a guarantee. There is no link to the Personal Profile user who gave or revoked a guarantee in the notification by email.**

**Actual result**
There is no link to the Personal Profile user who gave or revokes a guarantee in the notification by email:
![image](https://user-images.githubusercontent.com/104513228/170454190-170c733c-e4db-4912-aeb5-9b15812181f1.png)
![image](https://user-images.githubusercontent.com/104513228/170454328-a92b73e9-6adb-4607-96c4-0c49d3edf2ee.png)

**Expected result**
The link for the short version of the Personal Profile of the member who gave (revoked) the guarantee is active in the notification.

**User story and test case links**

User story
> https://github.com/ita-social-projects/EPlast/issues/947

Test case
> https://github.com/ita-social-projects/EPlast/issues/2461
> https://github.com/ita-social-projects/EPlast/issues/2462
> https://github.com/ita-social-projects/EPlast/issues/2464
> https://github.com/ita-social-projects/EPlast/issues/2498

**Labels to be added**
"Bug" ("bug")

**Comment by tvardero** [comment]
Blocked by https://github.com/ita-social-projects/EPlast/issues/2555
