### ISSUE TITLE
[Users table] Buttons are not aligned in 'Поточний стан користувача' section

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2515]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 76fe57d7e52feb4607679250f34ef0d060a7981d
**Priority:** low
**Severity:** low

**Preconditions**
User is logged in as super admin on the EPlast website (https://eplast.westeurope.cloudapp.azure.com/signin) 

**Steps to reproduce**
1. Go to the left-side menu
2. Click on 'Довідник' -> 'Таблиця користувачів'
3. Right click on any user and choose 'Поточний стан користувача' 
4. Check the buttons

**Actual result**
 Buttons are not aligned in 'Поточний стан користувача' section

**Expected result**
 Buttons should be aligned
![button alignment](https://user-images.githubusercontent.com/104838173/170840113-1bb7a47f-8501-4b24-a265-14230b52fe24.jpg)

**Comment by sysoyeva** [comment]
Buttons also are not aligned in 'Провід куреня' 
![1](https://user-images.githubusercontent.com/104834042/171048208-06ff445b-0392-4ddf-abb7-faa4422ae42c.png)
