### ISSUE TITLE
[Decisions] Field names are different for the same fields

### ISSUE THREAD

**Issue by SofiaSen** [ita-social-projects/EPlast#2519]
**Environment:** MacOS, Opera
**Reproducible:** always.
**Build found:**  https://github.com/ita-social-projects/EPlast/commit/76fe57d7e52feb4607679250f34ef0d060a7981d
**Priority:** low
**Severity:** low

**Preconditions**
User is logged in as a Superadmin

**Steps to reproduce**
1. Go to 'Рішення'
2. Click on 'Додати рішення' button

**Actual result**
Field names during creating and field names in the actual table are different

**Expected result**
Field names during creating and field names in the actual table are the same
![Знімок екрана 2022-05-31 о 12 59 15](https://user-images.githubusercontent.com/104833786/171148427-3bb18c0c-d3d5-448f-b895-e43704b9072d.png)

**Comment by hryhoriivoloshyn** [comment]
Hi, @SofiaSen, I am a little confused by the meaning of "Рішення для" column in the decisions table. As far as I understand it is set with "Тема рішення" field and I am asked to change it's title to "Рішення для". What is the purpose of this field? To tag people with "@" symbol as it is stated in comment to #1931 issue, or does it have some other use?

**Comment by SofiaSen** [comment]
Hello! 
Actually, differences in field names and @ functionality are two different issues. 

The newest bug I have created is about changing the title of the field name, so they are the same in the table and in the menu on the right. Please, take a look on the attachments below in the bug report. They are different. We need them to be the same. The right field names in the menu are correct.

Next, @ functionality is about tagging people from Plast system. But now we can tag any word, like even a random one. 

Hope, this explanation is clear enough. If you still have any questions, please, feel free to contact in Telegram sofiiasenchuk .

Have a nice one!
