### ISSUE TITLE
[Users table] [Deputy Region Admin] 'Провід пласту' is active for those users who don't have rights to make changes there

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2561]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 1f85388dfb8295bd9da80aeaaf13a79b48618639
**Priority:** medium
**Severity:** medium

**Preconditions**
User is logged in as Deputy of the region admin (https://eplast.westeurope.cloudapp.azure.com/signin) 

**Steps to reproduce**
1. Go to the left-side menu
2. Click on Довідник -> Таблиця користувачів
3. Right click on the user

**Actual result**
'Провід пласту' is active, but Deputy of the region admin doesn't have rights to make changes in this part. After making changes in this part we get 403 error

**Expected result**
Deputy of the region admin and region admin shouldn't have active option 'Провід пласту'
Deputy of the region admin and region admin should have such options on right-click: Переглянути профіль, Провід округи, Провід станиці, Поточний стан користувача, Додати ступінь, (? Заархівувати користувача?)
![Provid plastu for region admin](https://user-images.githubusercontent.com/104838173/173896730-06c8dc88-8d53-4c71-ba2d-81db540a52e2.jpg)

**Comment by ChrystynaKubai** [comment]
**Environment**: Windows 10 Enterprise
Microsoft Edge Version 101.0.1210.39 
Google Chrome Version 101.0.4951.54 
Firefox Browser Version 100.0
**Reproducible**: always
**Build found**: [74fabc4](https://github.com/vdespa/quick-introduction-to-postman/commit/74fabc4206a518012bdc16c9d6928431ac3e09cf)

**Preconditions**:
User is logged in as Country Admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**:

1. Go to the left-side menu
2. Click on Довідник -> Таблиця користувачів
3. Right click on the user who has 'Права доступу' as a 'Дійсний член організації'.

**Actual result**
'Провід пласту' option is enabled for the City Admin.

**Expected result**
'Провід пласту' option should be disabled for the City Admin.

https://user-images.githubusercontent.com/18471044/175306777-aeecbd7b-a938-4b81-9e1c-898dbb09478b.mp4

**Comment by ystrotska** [comment]
This defect is also reproduced for Hovel Admin. The details are as follows:

Environment: Windows 10 64-bit , Google Chrome, Version 99.0.4844.82
Reproducible: always

Preconditions:
User is logged in as Hovel Admin (https://eplast.westeurope.cloudapp.azure.com/signin)

Steps to reproduce:

Go to the left-side menu
Click on Довідник -> Таблиця користувачів
Right click on the user who has 'Права доступу' as a 'Дійсний член організації'.
Actual result
'Провід пласту' option is enabled for the Hovel Admin.

Expected result
'Провід пласту' option should be disabled for the Hovel Admin.
