### ISSUE TITLE
[Users table / Таблиця користувачів] City admin has access to all users in his Region, no filter by City

### ISSUE THREAD

**Issue by SofiaSen** [ita-social-projects/EPlast#2563]
**Build found:** https://github.com/ita-social-projects/EPlast/commit/1f85388dfb8295bd9da80aeaaf13a79b48618639
**Priority:** medium
**Severity:** medium

**Preconditions:**
User is logged in as a City Admin 

**Steps to reproduce:**

1. Go to the left-side menu
2. Click on Довідник -> Таблиця користувачів

**Actual result**
City admin has access to all users in his Region

**Expected result**
City admin has access to all users in his City
![Знімок екрана 2022-06-15 о 22 26 49](https://user-images.githubusercontent.com/104833786/173909484-6618835a-1638-476d-94a9-45fa504d58bc.png)

**Comment by bkondrat** [comment]
This user had two access rights: "Голова станиці" i "Голова округи". That`s why we could see users from both areas.
I repeated the same steps with other user which had only one access right: "Голова станиці"and it worked properly.
Looks like Голова Станиці is "broken" user. I could not delete properly his access. But this is another discussion. My recommendation: To check if it is bug or not use another user. Thanks
