### ISSUE TITLE
[Country] The Country Admin is not changed on the main tab of the country and his arrangement date is not saved

### ISSUE THREAD

**Issue by ChrystynaKubai** [ita-social-projects/EPlast#2579]
**Environment**: Windows 10 Enterprise
Microsoft Edge Version 101.0.1210.39
Google Chrome Version 101.0.4951.54
Firefox Browser Version 100.0
**Reproducible**: always
**Build**:[93056b8](https://github.com/ita-social-projects/EPlast/commit/93056b88c5d0b9a5947aa8e02245aa54e5fe3193)
**Priority**: High
**Severity**: High

**Preconditions**:
User is logged in as Super Admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to Reproduce**:
1.Go to the left-side menu.
2.Click on 'Довідник' -> 'Округи'.
3.Click the country.
4.Click on 'Більше' in the 'Провід округи' tab.
5.Click cancel button for 'Голова округи' and confirmed to delete the user from 'Провід округи'.
6.Return to the main page of the country.
7.Click on '+'  button in the 'Провід округи' tab.
8.Select the other user as the 'Голова округи'.

**Actual result**:
The other user is not changed on the main tab of the country.
His arrangement date is not saved.

**Expected result**:
The other user is changed on the main tab of the country.
His arrangement date is saved.

https://user-images.githubusercontent.com/18471044/175499218-fb1ed489-9724-4f56-9d08-12052fca6652.mp4

**Comment by sysoyeva** [comment]
Changing the country administrator on the main country tab is successful.
The date of his arrangement is preserved.
