### ISSUE TITLE
[Announcement] Misspelling the title of the 'Відкріпити оголошення' window  is shown in the 'Дошка оголошень' page after clicking on a pin button

### ISSUE THREAD

**Issue by ChrystynaKubai** [ita-social-projects/EPlast#2633]
**Environment**: Windows 10 Enterprise
Google Chrome Version 101.0.4951.54
Firefox Browser Version 100.0
**Reproducible**: always
**Build** :[792f6e0](https://github.com/ita-social-projects/EPlast/commit/5aa3693f11f388c1fb4494c7990add8ddc036cb4)
**Priority**: Low
**Severity**: Low

**Preconditions**:
The user is logged in as Admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps To Reproduce**:
1. Go to the left-side menu.
2. Click on 'Дошка оголошень'. 
3. Click on a pin button on the right side in the title of an announcement.
4. A 'Відкріпити оголошення' window is appeared.

**Actual Result**: Misspelling the title of the 'Відкріпити оголошення' window is shown.

**Expected Result**: The right spelling of the title of the 'Відкріпити оголошення' window should be shown.

<img width="308" alt="mispelling" src="https://user-images.githubusercontent.com/18471044/177907016-88f17dd1-7b7c-496a-8aa3-9609d42dc82a.png">

**Comment by sysoyeva** [comment]
The title
![3](https://user-images.githubusercontent.com/104834042/188698079-352da712-f216-403c-92a4-6c7013213b64.png)
 is correct.
