### ISSUE TITLE
[VumOnline] Buttons 'Yes' and 'No' have different size when deleting a certificate

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2665]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 24cf084a98c3f4d2d216305b2d85fc8ea0b74ce2
**Priority:** medium
**Severity:** medium

**Preconditions**
Sign in as registered user (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the top menu
2. Click on 'Курс'
3. Click 'Додати сертифікат'
4. Upload certificate and click 'Опублікувати'
5. Click on 'Досягнення'
6. Click on 'Delete' button to delete the certificate

**Actual result**
Buttons 'Yes' and 'No' have different size when deleting a certificate

**Expected result**
Buttons 'Yes' and 'No' should be the same size

![buttons size](https://user-images.githubusercontent.com/104838173/179780914-2aaa041e-deb6-40e9-82f2-2b032a7f6364.jpg)

**Comment by Mykola123-NMT** [comment]
Not a bug.
