### ISSUE TITLE
[Production] after confirming the email, it is not possible to login, [Login page]

### ISSUE THREAD

**Issue by Svturinina** [ita-social-projects/EPlast#2671]
**Environment:** Windows 10 ,Google chrome 
**Reproducible:**sometimes 
**Build found:** [772978e](https://github.com/ita-social-projects/EPlast/commit/772978eb75dc5056f7ff321244210d4919208eca)
Priority: Hight
Severity: Hight
**Preconditions**
Fill out the registration form

**Steps to reproduce**
1. Click login 
2. Go to the mail 
3. Confirm mail
4. Go to https://eplastprd.westeurope.cloudapp.azure.com/signin
5. Click 'Увійти'

**Actual result**
Error message 'Щось пішло не так',it is not possible to login

**Expected result**
Successful login 

**Labels to be added**
"Bug" ("bug")

**Comment by tvardero** [comment]
Unable to reproduce on eplastprd.

**Comment by tvardero** [comment]
If you are still able to reproduce, open email confirmation link with F12 console open

And send me back response of `confirmEmail?userId=...` request

**Comment by Svturinina** [comment]
defect fixed
