### ISSUE TITLE
[Users table][Додати до уладу] Mistake in the word while adding to Plast members procedure

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2674]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 772978eb75dc5056f7ff321244210d4919208eca
**Priority:** high
**Severity:** low

**Preconditions**
Sign in as super admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the left-side menu
2. Click on 'Довідник' -> 'Таблиця користувачів'
3. Right-click on the users
4. Choose 'Додати до уладу' or  'Змінити ступінь'
or
1. Go to the left-side menu
2. Click on 'Довідник' -> 'Станиці'
3. Go to the "Зголошені до станиці" section
4. Click "+ Додати до членів"

**Actual result**
Mistake in the words "Ступіня", "Cтупіню"

**Expected result**
All words should be written correctly 

![stupenya](https://user-images.githubusercontent.com/104838173/180297140-a5aa7213-38ca-441c-88c6-32ade8fa4226.jpg)

**Comment by NataliyaDominyuk** [comment]
Retested on PROD. Bug is still reproducible.

**Comment by SvitlanaOleksiv** [comment]
Bug is still reproducible.
![Ступеню should be ступеня](https://user-images.githubusercontent.com/110596345/203261354-16211f57-36f6-42df-b4c1-182041d2c14c.png)
