### ISSUE TITLE
[Announcements/ Оголошення] Plast member gets 403 error while trying to pin/unpin the announcement

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2700]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** eee869f9c689117261a1df72a159073cf5b4f5be
**Priority:** high
**Severity:** medium

**Preconditions**
Sign in as plast member (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the left-side menu
2. Click on 'Дошка оголошень'
3. Сlick on '...' button in the top right part of the announcement
4. Click on pin/unpin button in the top right part of the announcement

**Actual result**
403 error while trying to pin/unpin the announcement

**Expected result**
Plast member shouldn't have opportunity to edit announcements. Therefore, plast member shouldn't see 'pin/unpin' and '...' buttons
![edit announcement](https://user-images.githubusercontent.com/104838173/182455015-97bbe203-1480-4fce-91fb-2637b1822acd.jpg)

**Comment by sysoyeva** [comment]
Region Admin and Depyte Region Admin also have opportunity to edit announcements. But Region Admin and Depyte Region Admin shouldn't see 'pin/unpin' and '...' buttons.

**Comment by AnnaHumeniuk2212** [comment]
Deputy city admin (Заступник голови станиці) also have opportunity to edit announcements. After clicking user get 403 error.
