### ISSUE TITLE
[Про базу] The add section field skips Latin letters, numbers, and special characters

### ISSUE THREAD

**Issue by sysoyeva** [ita-social-projects/EPlast#2706]
**Environment:** Windows 10 Google Chrome 99.0.4844.82 64-bit
**Reproducible:** always
**Build found:** eee869f
**Severity:** low
**Priority:** low
**Preconditions**
log in as Super Admin

**Steps to reproduce**
1. Go to the left-side menu and open "Про Базу".
2. Admin can add a new chapter.

**Actual result**
New chapter can create with Latin letters. numbers and special characters.

**Expected result**
New chapter can create just with Cyrillic letters.

**Comment by gutovskii** [comment]
Is not a bug
