### ISSUE TITLE
[Bug] error 403 if prompted for forms and events[warnings] 

### ISSUE THREAD

**Issue by Svturinina** [ita-social-projects/EPlast#2709]
**Environment:* Windows 10
**Reproducible:** always
**Build found:** 

https://github.com/ita-social-projects/EPlast/pull/2694
Priority:Hight
Severity :Hight

**Preconditions**
Login as a “Прихильник пласту ”

**Steps to reproduce**
1. Go to 'Довівдник'
2. Click on 'Перестороги.' 
3. Select user
5. Click”Переглянути профіль”
6. Click «Події»and “Бланки”

**Actual result**
error 403 if prompted for forms and events.

**Expected result**
“Forms” and “Events” are open.

**Labels to be added**
"Bug" ("bug")

**Comment by sysoyeva** [comment]
Filed "Подія" should be available to Adherent.
Field "Бланки" by "рівні доступу"  there is no option to view.
![1](https://user-images.githubusercontent.com/104834042/182837682-b1ed9178-5d12-47fb-931c-462da9369bed.png)

**Comment by Svturinina** [comment]
Defect closed
