### ISSUE TITLE
[Hovel] [Провід Куреня] Wrong notification appears when adding the Hovel admins in "Провід Куреня"

### ISSUE THREAD

**Issue by ystrotska** [ita-social-projects/EPlast#2716]
**Environment:** Windows 10 Pro, Google Chrome version 103.0.5060.114 (development)(64-bit).
**Reproducible:** always.
**Build found:** last commit from [eee869f](https://github.com/ita-social-projects/EPlast/commit/eee869f9c689117261a1df72a159073cf5b4f5be)
**Priority:** medium
**Severity:** low

**Preconditions**
Sign in as a super admin (https://eplast.westeurope.cloudapp.azure.com/signin)
There should be at least one active member in the Hovel and vacant admin  roles

**Steps to reproduce**

1. Go to the left-side menu
2. Click on 'Довідник'
3. Go to the 'Hovels'
4. Click on any hovel with members and vacant admin roles
5. Go to the "Провід Куреня"
6. Click on "+" to add a role
7. Choose the needed user, pick the admin role, and start and end dates
8. Click "Опублікувати" button

**Actual result**
The information in the notification window is not correct
![wrong notification](https://user-images.githubusercontent.com/104917914/183262768-ed3b89f1-7523-429d-89fc-4208273dc69a.jpg)
![Active administrations of hovel](https://user-images.githubusercontent.com/104917914/183262789-baa07586-4eef-430b-bc3c-4a629835841f.jpg)

**Expected result**
The information in the notification window should not be displayed

**Comment by BordiukMariana** [comment]
Reproduced when assigning the role "Член КПР" to the member of the hovel with the date that hasn't expired.
