### ISSUE TITLE
[User profile / Профіль]  The 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' fields are implemented as mandatory

### ISSUE THREAD

**Issue by AnnaHumeniuk2212** [ita-social-projects/EPlast#2722]
**Environmen**t: Windows 10 version 21H2, Chrome Version 104.0.5112.81 
**Reproducible**: always
**Build found**: 1748ae1
**Priority**: high
**Severity**: high

**Preconditions**
Sign in as a user or admin https://eplast.westeurope.cloudapp.azure.com/signin

**Steps to reproduce:**
1. Go to 'Редагувати профіль'
2. Edit anything in the fields (e.g. edit 'віровизнання').
3. Leave the 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' fields empty.
4. Click on the 'Підтвердити' button.
5. Verify error messages near 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' fields.

**Actual result**
The 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' fields are implemented as mandatory. Error messages are shown after leaving it empty.

**Expected result**
The 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' fields are not implemented as mandatory. Error messages are not shown after leaving it empty.

![зайві обов'язкові поля при редагуванні профіля](https://user-images.githubusercontent.com/110613286/183653014-126950b6-b06d-4747-a35e-bd7ae2d7c141.png)
[extra mandatory fields in profile.webm](https://user-images.githubusercontent.com/110613286/183743300-612b0fb8-1b5f-411c-8e17-83a8a7499841.webm)

**Comment by lypijka** [comment]
[User profile / Профіль] The 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' are shown as cut text when user edit profile page "Редагувати профіль".
Environment: Windows 10 version 21H2, Chrome Version 104.0.5112.81
Reproducible: always
Build found: [903bf73](https://github.com/ita-social-projects/EPlast/commit/903bf732961d4ff8663d5b90ecfa61e1972a9411)
Priority: high
Severity: high

Preconditions
Make registration into system as user. Fill the fields of facebook, instagram and twitter links with right credentials. (e.g. https://www.facebook.com/goodies.ecoshop , https://www.instagram.com/we_love_kids_lviv/ , https://twitter.com/Pontifex )

Steps to reproduce:
1. Go to 'Редагувати профіль'
2. Pay attention that 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' links are shown as a cut text.
![2022-08-21_05h13_07](https://user-images.githubusercontent.com/62888068/185772166-276cdc01-fae4-4335-a4ba-ec59ef820591.png)
3. Click on the 'Підтвердити' button.
4. Verify error messages near 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' fields.
![2022-08-21_05h15_23](https://user-images.githubusercontent.com/62888068/185772173-77c79446-f15a-43ff-98c2-1ebe257c4746.png)

Actual result
If user fill the fields 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' with right credentials on registration form, they are shown as cut text on Edit profile page, so user can not confirm the changes in other fields.

Expected result
If user fill the fields 'Посилання на facebook', 'Посилання на twitter', ' Посилання на instagram' with right credentials on registration form, they have to be shown correctly on Edit profile page, so he can confirm the changes in other fields.
