### ISSUE TITLE
[Office management] [Діловодства куреня]The role with the expired date is placed in incorrect place

### ISSUE THREAD

**Issue by BordiukMariana** [ita-social-projects/EPlast#2730]
**Environment:** OS: Windows 10.0.19044.1826 , browser: Chrome 104.0.5112.81
**Reproducible:** always
**Build found:** 1748ae1
**Preconditions**
The user is signed in as Superadmin.

**Steps to reproduce**
1. Go to the menu.
2. Click on 'Довідник'.
3. Select "Курені".
4. Select the hovel (курінь) with at least one member and vacant roles of "Писар","Домівкар" and "Скарбник".
5. Click on the "Add" button (+) in the "Провід куреня".
6. Click on the dropdown list and select the user.
7. Click on the dropdown list and select the role ( "Писар","Домівкар" or "Скарбник").
8. Select the start and end date that has expired.
9. Sign in as a user with the role of "Active Member".
10. Click on "Діловодства" tab.
11. Click on "Діловодства куреня" tab.
12. Verify "Дійсні діловодства куреня" and "Колишні діловодства куреня".

**Actual result**
The role with the expired date is placed in  "Дійсні діловодства куреня".
![wrong place for expired role](https://user-images.githubusercontent.com/110609069/183943810-ffdd7cdd-5c1a-4c5f-a192-69c65abe6f39.png)
![wrong place for expired role (2)](https://user-images.githubusercontent.com/110609069/183943824-17893280-d2ec-47e7-b0c5-fdddc37cf033.png)

**Expected result**
The role with the expired date is placed in  "Колишні діловодства куреня".

**Priority** High
**Severity** Medium

**Comment by BordiukMariana** [comment]
Next day the end date of the role changes automatically one year forward
![change of date](https://user-images.githubusercontent.com/110609069/184125252-811bdb44-9aca-47ee-86b5-eed7c2d5eaa1.png)
.

**Comment by JuliaZakharevych** [comment]
The same bug in Станиці
![Знімок екрана (570)](https://user-images.githubusercontent.com/110524788/185359369-e08509e0-c796-4e17-8fe9-7b91f99112c1.png)
