### ISSUE TITLE
[Users table] User's age is not displayed correctly on the 'Прийняти до уладу' window

### ISSUE THREAD

**Issue by MarharytaKonovalova** [ita-social-projects/EPlast#2732]
**Environment:** Windows 10, Chrome Version Version 103.0.5060.114, Microsoft Edge Version 104.0.1293.47
**Reproducible:** always.
**Build found:** 3fc6557
**Priority:** medium
**Severity:** medium

**Preconditions**
Sign in as an admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**

1. Go to the left-side menu
2. Click on the 'Довідник' -> 'Станиці'
3. Choose any city
4. Go to the 'Члени станиці' -> 'Більше' 
5. Click on any user and chose 'Додати до уладу' option
6. Verify age of the user according to the birth date

Actual result
Incorrect age is displayed

Expected result
Valid age of the user should be displayed
![image](https://user-images.githubusercontent.com/110613727/184012701-c50ed02d-02c8-4fdf-b256-6371d823b368.png)

**Comment by ystrotska** [comment]
The bug is still reproduced on production
