### ISSUE TITLE
[Users table] Incorrect pagination of the table pages

### ISSUE THREAD

**Issue by MarharytaKonovalova** [ita-social-projects/EPlast#2733]
**Environment:** Windows 10, Chrome Version Version 103.0.5060.114, Microsoft Edge Version 104.0.1293.47
**Reproducible:** always.
**Build found:** 3fc6557
Priority: medium
Severity: medium

Preconditions
Sign in as an admin (https://eplast.westeurope.cloudapp.azure.com/signin)

Steps to reproduce

1. Go to the left-side menu
2. Click on the 'Довідник' -> 'Станиці'
3. Choose any city (e.g Львів)
4. Go to the 'Члени станиці' -> 'Більше'
5. Verify pagination on the page

Actual result
Not existing pages are displayed

Expected result
Correct number of pages should be displayed

https://user-images.githubusercontent.com/110613727/184015755-c682f539-5f3e-4c47-99e7-71bfde22d8da.mp4

**Comment by SvitlanaOleksiv** [comment]
![Пагінація](https://user-images.githubusercontent.com/110596345/198239179-632c019f-cbc8-4bf5-80eb-09d3c18342fd.png)
