### ISSUE TITLE
[Regions/Округи] Super admin can't add document in 'Документообіг округи'

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2734]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 3fc6557a7ade84548db832f7efcc4ec62c2e7420
**Priority:** high
**Severity:** medium

**Preconditions**
Sign in as super admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the left-side menu
2. Click on the 'Довідник' -> 'Округи'
3. Choose any region (округа) 
4. Go to the 'Документообіг округи' section
5. Try to add new document

**Actual result**
'+' Button is  missing. Super admin can't add document in 'Документообіг округи'. 

**Expected result**
Super admin should be able to add document in 'Документообіг округи'. 

![add documents ](https://user-images.githubusercontent.com/104838173/184082684-f2af3c89-2979-4089-b749-6e7e7ad226f3.jpg)

**Comment by ystrotska** [comment]
Governing Body Admin ( "Крайовий Адмін") also can not add document in 'Документообіг округи'.
