### ISSUE TITLE
[Regional Board of the Plast] No redirection onto profiles after clicking on the users in Regional Board of the Plast

### ISSUE THREAD

**Issue by BordiukMariana** [ita-social-projects/EPlast#2737]
**Environment:** OS:Windows 10.0.19044.1826 , browser: Chrome 104.0.5112.81
**Reproducible:** always.
**Build found:** 3fc6557

**Preconditions**
A user is logged in as Active Member
**Steps to reproduce**
1. Go to the menu.
2. Select "Крайовий провід Пласту".
3. Click on the user in "Адміністрація Крайового Проводу" or on the user in any governing bodies(Керівні органи).

**Actual result**
No redirection onto user's profile is performed.

**Expected result**
The user is redirected onto the selected user's profile.

**Priority**: Medium
**Severity**:Medium

**Comment by Mykola123-NMT** [comment]
Functional was changed.
