### ISSUE TITLE
[Округи] Super Admin can't edit the 'Округа' - 404 error is shown

### ISSUE THREAD

**Issue by AnnaHumeniuk2212** [ita-social-projects/EPlast#2738]
**Environment:** Windows 10 version 21H2, Chrome Version 104.0.5112.81
**Reproducible:** always
**Build found:**3fc6557
**Priority:** high
**Severity:** medium

**Preconditions**

Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log into the system as Super Admin.

**Steps to reproduce**
1. Go to the ' Довідник'  and click on the 'Округи'.
2. Choose one of the Округи (e,g. Вінниця).
3. Click on the edit icon.
4. Verify the result. 

**Actual result**
404 error is shown after trying to edit 'Округа'. Super Admin can't edit 'Округи'.

**Expected result**
Super Admin can edit 'Округи' after clicking on the edit icon on the page of 'Округа'.

![edit округи](https://user-images.githubusercontent.com/110613286/184156677-b0cbb21e-f124-4b25-8e0e-2c941cb5103d.png)
**After clicking on icon edit:** 
![404 error](https://user-images.githubusercontent.com/110613286/184156728-4585e21d-5a93-40de-93ec-cb6003c1f949.png)
[404 - редагування округи.webm](https://user-images.githubusercontent.com/110613286/184156747-60b4d24e-dd0a-4251-8b8b-495577d8a615.webm)

**Comment by ystrotska** [comment]
The same bug is reproduced for the Governing Body Admin/"Крайовий"
![image](https://user-images.githubusercontent.com/104917914/184506823-62a43e49-ffc0-4e71-bef9-7f37153d56f1.png)
![image](https://user-images.githubusercontent.com/104917914/184506864-0ae7d3bd-bedf-4d42-89f5-c014d94bf1b8.png)

**Comment by AnnaHumeniuk2212** [comment]
The bug is still reproducible for the build [4d5f734](https://github.com/ita-social-projects/EPlast/commit/4d5f734b35197d6f7b678416e1c416f756683b91)
