### ISSUE TITLE
[Cities/Станиці] A user does not obtain a new role in 'Провід Станиці' after his/her administration type has been edited

### ISSUE THREAD

**Issue by JuliaZakharevych** [ita-social-projects/EPlast#2752]
**Environment:** Windows 10 Google Chrome 104.0.5112.80 64-bit
**Reproducible:** always
**Build found:** [3fc6557](https://github.com/ita-social-projects/EPlast/commit/3fc6557a7ade84548db832f7efcc4ec62c2e7420)
**Severity:** high
**Priority:** high

**Preconditions**
Sign in as super admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the left-side menu
2. Click 'Довідник'->'Станиці'
3. Select one of the Станиця (e.g. 'Львів')
4. Scroll down to 'Провід Станиці'
5. Press '+' button and assign any user a role in 'Провід станиці' (e.g. 'Писар') 
6. Click 'Більше'
7. Click on the Edit icon at the bottom left under the name of the User with the role 'Писар'
8. Change the User administration type (e.g. to 'Скарбник')

**Actual result**
The user loses the edited administration type ('Писар') and does not receive a new one ('Скарбник')

**Expected result**
The user's administration type changes from Писар to Скарбник

https://user-images.githubusercontent.com/110524788/185153254-72513bd6-e84e-47da-a74d-86c087266239.mp4

![Знімок екрана (568)](https://user-images.githubusercontent.com/110524788/185153859-11e33714-933e-4c41-89a6-5ce70e74b6b0.png)

**Comment by NataliyaDominyuk** [comment]
The same bug in Regional board (Крайовий провід пласту - Провід керівного органу)

https://user-images.githubusercontent.com/104838173/185175035-042f09a9-b5f9-40ea-a9ae-09894b2279f7.mov
