### ISSUE TITLE
[Regional board/ Крайовий провід пласту-Керівні ограни ] No distance between word 'Оголошення' and the number of announcements

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2755]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 903bf732961d4ff8663d5b90ecfa61e1972a9411
**Priority:** medium
**Severity:** low

**Preconditions**
Sign in as super admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the left-side menu
2. Click on the 'Довідник' -> 'Крайовий провід пласту'
3. Go to 'Керівні органи' section and make any selection
4. Check the 'Оголошення' section 

**Actual result**
No distance between word 'Оголошення' and the number

**Expected result**
There should distance between word 'Оголошення' and the number

![distance between words](https://user-images.githubusercontent.com/104838173/185176539-af523b7c-0638-4e58-bb7c-591897366000.jpg)

**Comment by NataliyaDominyuk** [comment]
The same bug in 'Провід напряму керівного органу'

![provid napryamu](https://user-images.githubusercontent.com/104838173/185308572-f8a08e20-d751-4eeb-87e8-7dc670cea472.jpg)

**Comment by ystrotska** [comment]
The bug is available in prod in "Керівний орган..."
![image](https://user-images.githubusercontent.com/104917914/195103180-9bb5c5bb-46e8-4a97-95bb-e7c0d03ae9fc.png)
