### ISSUE TITLE
[Regions board/Крайовий провід пласту] No space between the text 'Назва документу' and the input field in 'Документообіг' section

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2759]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 903bf732961d4ff8663d5b90ecfa61e1972a9411
**Priority:** medium
**Severity:** low

**Preconditions**
Sign in as super admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the left-side menu
2. Click on the 'Крайовий провід пласту'
3. Go to 'Документообіг' section and press '+' button (add document)
4. Check the first input field

**Actual result**
No space between the text 'Назва документу' and the input field.
Input field is shifted down.

**Expected result**
There should space between the text 'Назва документу' and the input field. 
Text and the input field should be on the same level.

![space before input field](https://user-images.githubusercontent.com/104838173/185305330-6ca0521e-bcc5-4c92-8529-9e053024d17c.jpg)

**Comment by Serhii-Buniak** [comment]
not reproduce on windows 10. Make retesting please

**Comment by MishaHMK** [comment]
'Документообіг' was removed from 'Крайовий провід пласту'
