### ISSUE TITLE
[Regions/Округи] Registered user/Зареєстрований користувач should not have an access to the Regions tab

### ISSUE THREAD

**Issue by MarharytaKonovalova** [ita-social-projects/EPlast#2760]
**Environment:** Windows 10, Chrome Version Version 103.0.5060.114, Microsoft Edge Version 104.0.1293.47
**Reproducible:** always
**Build found:** 903bf73

**Preconditions**
Sign in as a registered user (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**

1. Click on the name of the region (atachment)

**Actual result**
Region page is opened

**Expected result**
User shoud not have access to Regions tab
Name of the region should not be clickable for this type of user

![regions](https://user-images.githubusercontent.com/110613727/185338778-3a2ed757-5a2a-4a16-8652-8af4b9bdddbb.jpg)

**Comment by NataliyaDominyuk** [comment]
Name of the region isn't clickable. This part is fixed. But please, change the type of cursor from hand (pointer) to arrow(default), when hovering over the name of the region
