### ISSUE TITLE
[Password Reset/Скидання пароля] Incorrect header of the Password Reset page and incorrect fields alignment

### ISSUE THREAD

**Issue by JuliaZakharevych** [ita-social-projects/EPlast#2808]
**Environment:** Windows 10 Google Chrome 104.0.5112.80 64-bit
**Reproducible:** always
**Build found:** [4d5f734](https://github.com/ita-social-projects/EPlast/commit/4d5f734b35197d6f7b678416e1c416f756683b91)
**Priority:** low
**Severity:** low

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/

**Steps to reproduce**
1. Press 'Забули пароль' button
2. Enter existing email
3. Click on "Надіслати" button
4. Open the mail of the user for whom you want to change the password
5. Open the letter from Plast and follow the link in the letter
6. Verify the header of the page
7. Verify the alignment of the fields

**Actual result**
1. Header of the page is 'Скидання пароля. Введіть електронну пошту'
2. Fields names are not aligned.

**Expected result**
1. Header of the page should be 'Скидання пароля'
2. Fields names should be aligned

![Знімок екрана (590)](https://user-images.githubusercontent.com/110524788/188908921-b6466c8d-d06b-4074-aa74-cffb5a071be1.png)

**Comment by NataliyaDominyuk** [comment]
the bug is still present

<img width="700" alt="Screenshot 2022-11-01 at 11 59 42" src="https://user-images.githubusercontent.com/104838173/199208695-5a05552b-713c-412d-9d08-7a3ae95fb387.png">
