### ISSUE TITLE
NETLV-306 As an Administrator I want to add a new annual report for ‘Станиця’

### ISSUE THREAD

**Issue by OlesiaLetsin** [ita-social-projects/EPlast#284]
To replace a textbox ‘Подати річний звіт станиці’ with a button. According to the Interface Guidelines, it is not the best practice for actions to be performed with a dropdown, but to use a button instead. The button would draw people’s attention and it would take less time to find a way to submit a report.

**Comment by Oksana-lviv** [comment]
![image](https://user-images.githubusercontent.com/71265495/96337504-5148e980-1090-11eb-94c8-4a8b3537a5a7.png)
