### ISSUE TITLE
[VUM course] Uploaded course completion certificate isn't present in "Досягнення" section

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2864]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 0a759f95cce4e052f6236c7006b3abb1941572ad
**Priority:** medium
**Severity:** medium

**Preconditions**
Sign in as new registered user (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the top menu
2. Choose "Курс" 
3. Click "Додати сетифікат" and upload the document
4. Check "Досягнення" section.

**Actual result**
Uploaded course completion certificate isn't present in "Досягнення" section

**Expected result**
Uploaded course completion certificate should be in "Досягнення" section

https://user-images.githubusercontent.com/104838173/191603727-76a7fe9e-ccc3-49a2-b727-ee2c369c0dae.mov

**Comment by AnnaHumeniuk2212** [comment]
The bug  is also reproduced after clicking on the 'Бланки' - 'Досягнення' buttons 
[курс-бланки.webm](https://user-images.githubusercontent.com/110613286/191739391-fcde2ca7-6067-4d12-8ac0-1b742950d0c3.webm)

**Comment by gutovskii** [comment]
I fixed the bug, but it doesn't reproduce only on production. So i put it to 'Ready for testing new'
