### ISSUE TITLE
[Forgor password] The 'Forgot password' link in the email doesn't work correctly

### ISSUE THREAD

**Issue by AnnaHumeniuk2212** [ita-social-projects/EPlast#2876]
**Environment:** Windows 10 version 21H2, Chrome Version 105.0.5195.127
**Reproducible:** always
**Build found:** [edef58b](https://github.com/ita-social-projects/EPlast/commit/edef58b6d56ef68b19d1179e7052e24e4c909e57)
**Priority:** high
**Severity:** high

**Preconditions**
The user must be registered on the site https://eplast.westeurope.cloudapp.azure.com/ 

**Steps to reproduce**
1. Go to the site https://eplast.westeurope.cloudapp.azure.com/
2. Click on the 'Забули пароль' button.
3. Enter the valid email of the registered user and click on the 'Надіслати' button.
4. Open the email from Plast and click the link to reset the password.
5. Verify the message and result.

**Actual result**
The 'Forgot password' link in the email doesn't work correctly. The user can not reset his password. 

**Expected result**
A user can reset the password after clicking on the link in the email. The 'Forgot password link' in the email works correctly. 
![лист з посиланням](https://user-images.githubusercontent.com/110613286/192542758-374019de-1b5c-4e48-8567-e411f8bc1fa7.png)
![переадресування](https://user-images.githubusercontent.com/110613286/192542761-b18b6406-a49e-41e0-9a5a-8fa149186a1f.png)
![not found](https://user-images.githubusercontent.com/110613286/192543588-303b4531-0d96-4812-ab14-d0629c47287b.png)

**Comment by sysoyeva** [comment]
The same situation, if Region Admin should view the user profile in the mail, the link doesn't work correctly.
![5](https://user-images.githubusercontent.com/104834042/193531920-c665d75a-5fad-42ab-9f50-de0752ab04e0.png)
![6](https://user-images.githubusercontent.com/104834042/193532355-ec9a05e6-58a0-428a-85a6-72306ef7428a.png)

**Comment by AnnaHumeniuk2212** [comment]
The same situation, when the new user receives a mail about joining to Plast
![4 10  - лист про долучення](https://user-images.githubusercontent.com/110613286/193554352-9d7498fd-e185-487c-9845-534baf373a3b.png)

**Comment by AnnaHumeniuk2212** [comment]
The bug is fixed. Retesting was done on the site: https://eplastprd.westeurope.cloudapp.azure.com/signin
