### ISSUE TITLE
[Precaution (Перестороги)] Wrong date format in the notification, while creating a precaution for a user who has active precaution of the same type

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2880]
**Environment:** Mac OS Monterey 12.6, Safari version 15.6.1 (17613.3.9.1.16)
**Reproducible:** always
**Build found:** 9e7bc1b6917aa89785693d20de85ba00f11c2003
**Priority:** medium
**Severity:** medium

**Preconditions**
Sign in as admin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the left-side menu
2. Choose "Довідник" -> "Перестороги"
3. Try to create a precaution (пересторога) for a user who has active precaution of the same type
4. Check the date format in the warning notification (Не вдалось створити пересторогу! Користувач має активну до {date})

**Actual result**
Wrong date format mm/dd/yy in the warning notification 

**Expected result**
Date should be in format dd/mm/yy

![wrong date format](https://user-images.githubusercontent.com/104838173/193790534-b10eff01-28c5-4fa4-b852-083aee6c94a1.jpg)

**Comment by NataliyaDominyuk** [comment]
the bug is still present
![wrong date format](https://user-images.githubusercontent.com/104838173/201616263-1583dbfd-ccd7-42d3-a62c-9bd5e5463cb4.jpg)

**Comment by SvitlanaOleksiv** [comment]
Bug is still reproducible. There is no specific date.
![invalid date 1](https://user-images.githubusercontent.com/110596345/203266368-b343224e-875d-46aa-b3f5-16ea31b45d11.png)
