### ISSUE TITLE
[Regional Board of the Plast][Documentation] Incorrect pointer when superadmin hovers over non-clickable attached document

### ISSUE THREAD

**Issue by ystrotska** [ita-social-projects/EPlast#2901]
**Environment:** Windows 10 Pro, Google Chrome version 103.0.5060.114 (development)(64-bit).
**Reproducible:** always.
**Build found:** last commit from [e3b1dcd](https://github.com/ita-social-projects/EPlast/commit/e3b1dcdcaff9ffdfed898cb5cd8b20a665c00bd2)
**Priority:** low
**Severity:** low

**Preconditions**
Sign in as a superadmin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**

1. Go to the left-side menu
2. Click on 'Крайовий Провід Пласту"
3. Go to the 'Документообіг' section
4. Hover over icon of the document attached
5. Verify the pointer 

**Actual result**
A 'white palm' pointer
 ![image](https://user-images.githubusercontent.com/104917914/195157453-ff740e0f-4f1f-466b-9a87-25c838a1dba5.png)
 which means the user can click and view the non-clickable document is displayed.

![hand mouse pointer_non-clickable attachment](https://user-images.githubusercontent.com/104917914/195157650-4774a717-420e-4542-9f5a-fc58e1829843.jpg)

**Expected result**
An arrow mouse pointer 
![image](https://user-images.githubusercontent.com/104917914/195157878-dd1d3620-df8b-4d92-b9fe-4c09c25d4fc5.png)
  should be displayed when the user hovers over a non-clickable document.

**Comment by gutovskii** [comment]
We don't have this page anymore
