### ISSUE TITLE
[Event] Admin/Governing body admin and his deputy don't get notification about created event that needs their approval

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2928]
**Environment:** Mac OS Monterey 12.6, Google Chrome version 105.0.5195.125 (Official Build) (arm64)
**Reproducible:** always
**Build found:** 7c7b61d248c3a55a4d1ed63ed7da960471db49b4
**Priority:** high
**Severity:** high

**Preconditions**
1. New event should be created by any Plast member at https://eplast.westeurope.cloudapp.azure.com

**Steps to reproduce**
1. Sign in Super Admin/Governing body admin or his deputy
2. Check the notification bell

**Actual result**
1. Admin/Governing body admin and his deputy don't get notification about created event that needs their approval

**Expected result**
Super Admin/Governing body admin and his deputy should get notifications about created event that needs their approval

![admin event approval](https://user-images.githubusercontent.com/104838173/198249855-5ed28d3b-15e6-4f75-8fdb-e799695660eb.jpg)

**Comment by gutovskii** [comment]
All governing body admins and his deputies in entire ePlast should get a notification?
