### ISSUE TITLE
[City] Super Admin can't create role City Admin to the new user and changes don't display on the user's profile page

### ISSUE THREAD

**Issue by sysoyeva** [ita-social-projects/EPlast#2932]
**Environment:** Windows 10 Google Chrome 99.0.4844.82 64-bit
**Reproducible:** always
**Build found:** 7c7b61d

**Preconditions**
Log in as a Super Admin

**Steps to reproduce**
1. Open left-side menu and choose City "Lviv"
2. Press the Plus button on the 'Провід Станиці'
3. Give the role City Admin to any new user and press Save
4. Verify the correct changes on the City page " Lviv"
5. Open this user's profile page
6. Verify the correct display of his new role in the "Дійсне членство ,Діловодства"

**Actual result**
Super Admin can make changes, but this change doesn't correctly display on the City page, and on the user's profile page "Дійсне членство ,Діловодства"

![1](https://user-images.githubusercontent.com/104834042/198326311-576ec50e-cc8b-4316-aeb4-eff6d9e3654e.png)
![5](https://user-images.githubusercontent.com/104834042/198319450-977663f9-2de1-4f1c-9948-76759e237a39.png)
![2](https://user-images.githubusercontent.com/104834042/198319491-a2089bd2-1f68-4195-a79d-75a99081595c.png)
![2](https://user-images.githubusercontent.com/104834042/198328031-0693142d-dc90-4a89-90bd-8b2e651b9cde.png)

**Expected result**
After Super Admin makes the changes, it should correct display on the City page, and on the user's profile page "Дійсне членство ,Діловодства"

**Comment by gutovskii** [comment]
Bug is still reproducing

**Comment by sysoyeva** [comment]
Requirements have been changed
