### ISSUE TITLE
[User table/Таблиця користувачів] 500 error after a member of the plast selected the user table 

### ISSUE THREAD

**Issue by SvitlanaOleksiv** [ita-social-projects/EPlast#2961]
**Environment:** Windows 11x64, Opera 87.0.4390.45
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev [eba75bb](https://github.com/ita-social-projects/GreenCityClient/commit/eba75bb9ccbbb02be7f440c534244e52a2006ef0)

**Preconditions**
Be registered as a plast member (access of a member of the organization), not admin
![Доступ члена організації](https://user-images.githubusercontent.com/110596345/203036110-e8e44249-d27d-4962-b5a6-8ccdf58fee8f.png)

**Steps to reproduce**
1. Go to 'https://eplast.westeurope.cloudapp.azure.com'
2. Log in as plast member
3. Expand the 'Довідник' menu
4. Click 'User table/Таблиця користувачів'

**Actual result**
A pop-up window with an informative message "Помилка!
Error: Request failed with status code 500"
![500](https://user-images.githubusercontent.com/110596345/203036162-8ec4ec29-a9f3-4282-86d9-e7c65b8b247f.png)

**Expected result**
The 'User table/Таблиця користувачів' tab is opened and the list of users is shown

**Labels to be added**
"Bug" 
"pri: high"

**Comment by gutovskii** [comment]
Not reproducing
