### ISSUE TITLE
['Річний звіт станиці Берислав' page] No data to choose when clicking on 'Голова новообраної Cтаршини' field

### ISSUE THREAD

**Issue by OlesiaLetsin** [ita-social-projects/EPlast#335]
https://jira.softserve.academy/browse/NETLV-753

Steps to reproduce:

Go to https://eplastua.azurewebsites.net/signin;
Log in as Administrator 'Крайового проводу':
Login: admin@eplast.com
Password: Aa12345.
Click on the button 'Річні звіти' at the 'Документи' tab;
Click on the button 'Подати річний звіт' above the table of all reports;
Choose the name 'Берислав' of 'Станиця' from dropdown list;
Click on button 'Створити річний звіт';
Select 'Голова новообраної Старшини' from dropdown list
Actual result:
Іра Завущак is selected as 'Голова новообраної Старшини'

Expected result:
There is no data to choose 'Голова новообраної Старшини'

**Comment by Oksana-lviv** [comment]
'Берислав' of 'Станиця'  does not exist, but bug is verified on other cities.
