### ISSUE TITLE
['Річні звіти станиць' page] Pop-up menu is not closed after clicking outside the table

### ISSUE THREAD

**Issue by OlesiaLetsin** [ita-social-projects/EPlast#337]
https://jira.softserve.academy/browse/NETLV-764

Steps to reproduce:

Test case NETLV-747 is done;
Go to https://eplastua.azurewebsites.net/signin;
The user logs in with the rights of administrator 'Крайового проводу'
Admin 'Крайового проводу':
Login: admin@eplast.com
Password: Aa12345.
Click on the button 'Річні звіти' at the 'Документи' tab;
Click the report by right mouse button;
Close the pop-up menu clicking outside the table by left mouse button
*
Actual result:*
The pop-up menu isn't closed after clicking outside the table by left mouse button (it can only be closed by clicking on the table)
Expected result:
The pop-up menu is closed

**Comment by Oksana-lviv** [comment]
pass
