### ISSUE TITLE
[Registration page] Wrong error message appears when try to register already registered user

### ISSUE THREAD

**Issue by IhorQC523** [ita-social-projects/EPlast#339]
[https://jira.softserve.academy/browse/NETLV-99](url)
Priority: Low
Severity: Trivial 
Environment: MacOS High Sierra 10.13.6, Firefox Browser 77.0.1 (64-bit)

Steps to reproduce:

    1. Go to https://eplast.azurewebsites.net/  url.
    2. Click on "Зареєструватись" tab
    3. Enter "sm@lion.net.ua" in to "Електронна пошта" field
    4. Enter "test123*" in to "Пароль" field
    5. Enter "test123*" in to "Повторіть пароль" field
    6. Enter "Влад" in to "Ім'я" field
    7. Enter "Шпак" in to "Прізвище" field

Actual result:

Error message appears "Сповіщення Register-RegisteredUser"

Expected result:

Error message appears "Користувач з введеною електронною поштою вже зареєстрований"

<img width="1329" alt="Wrong message" src="https://user-images.githubusercontent.com/69673169/92334260-eff72900-f094-11ea-9a23-880805da0f89.png">

**Comment by Oksana-lviv** [comment]
One step missed: 8. Click on the 'Зареєструватись' button
![bug-ver-fail339](https://user-images.githubusercontent.com/71265495/95066250-d20bfb00-070a-11eb-855e-e4c1bc2dc9d4.jpg)
@ViktorKalynenko

**Comment by MykytaKlymachkov** [comment]
Retested 11.11
