### ISSUE TITLE
[Registration page] Alignment problem with "Пароль" and "Повторіть пароль" fields

### ISSUE THREAD

**Issue by IhorQC523** [ita-social-projects/EPlast#340]
[https://jira.softserve.academy/browse/NETLV-99](url)
Priority: Very Low
Severity: Trivial 
Environment: MacOS High Sierra 10.13.6, Firefox Browser 77.0.1 (64-bit)

Steps to reproduce:

    1. Go to https://eplast.azurewebsites.net/  url
    2. Click on "Зареєструватись" tab
    3. Pay attention to the "Пароль" and "Повторіть пароль" fields

Actual result:

Hint text in "Пароль" and "Повторіть пароль" fields isn't left aligned relative to hint text in other fields (see attachment below)

Expected result:

Hint text in all fields is left aligned
![Wrong alignment](https://user-images.githubusercontent.com/69673169/92334104-95a99880-f093-11ea-9def-ad75aae5a4e0.png)

**Comment by Oksana-lviv** [comment]
pass
![bug-ver-pass340](https://user-images.githubusercontent.com/71265495/95065822-3aa6a800-070a-11eb-9cbe-73cd8023b96b.jpg)
