### ISSUE TITLE
[Registration page] Absence of error message when entering invalid data into password field

### ISSUE THREAD

**Issue by IhorQC523** [ita-social-projects/EPlast#342]
[https://jira.softserve.academy/browse/NETLV-99](url)

Priority: Low
Severity: Trivial 
Environment: MacOS High Sierra 10.13.6, Firefox Browser 77.0.1 (64-bit)

Steps to reproduce:

    1. Go to https://eplast.azurewebsites.net/ website
    2. Click on 'Зареєструватись' tab
    3. Enter invalid value into password field (e.g. Ann123)

Actual result:

The field filled with data. There is no any error message.

Expected result:

Error message appears 'Пароль повинен містити літери, цифри та знаки'

**Comment by Oksana-lviv** [comment]
Actual result: The field filled with data. There is no any error message.
![bug-ver-fail344](https://user-images.githubusercontent.com/71265495/95068223-ad655280-070d-11eb-9e05-7bbdf29fcc1a.jpg)
@ViktorKalynenko
