### ISSUE TITLE
[Registration page] Wrong error message appears when entering invalid data into surname field

### ISSUE THREAD

**Issue by IhorQC523** [ita-social-projects/EPlast#343]
[https://jira.softserve.academy/browse/NETLV-99](url)

Priority: Low
Severity: Trivial 
Environment: MacOS High Sierra 10.13.6, Firefox Browser 77.0.1 (64-bit)

Steps to reproduce:

    1. Go to https://eplast.azurewebsites.net/ website
    2. Click on 'Зареєструватись' tab
    3. Enter invalid value into surname field (e.g. Шпакшпакшпакшпакшпакш)

Actual result:

Error message appears 'Дане поле повинне містити тільки літери'

Expected result:

Error message appears 'Прізвище повинно містити менше 20 літер'

**Comment by Oksana-lviv** [comment]
Pass
![bug-ver-pass343](https://user-images.githubusercontent.com/71265495/95064087-e3073d00-0707-11eb-996d-fd367d00c528.jpg)
