### ISSUE TITLE
['Редагування куреня' page] A user can enter more than 150 characters into the 'Посилання' text field

### ISSUE THREAD

**Issue by AnnaBurtnyk** [ita-social-projects/EPlast#346]
**Pre-condition:** Log in https://eplastua.azurewebsites.net/ with login s_dukach_s@ukr.net and password test123*

**Steps:**

1. Click on the menu button (three strips) on the top of the left corner of the page
2. Click on the "Інформація" dropdown
3. Click on the "Курені" link
4. Choose any existing Hut ("Курінь"). E.g. "Першопрохідці"
5. Click on the "Pencil" icon on the top of the left corner of the page
6. Enter more than 150 characters in "Посилання" text field

**Actual result:**
User can enter more than 150 characters. No error message.

**Expected result:**
Error message appears: "Web-сторінка не може перевищувати 150 символів"

**Environment**: 64x-based PC, Windows 7, Google Chrome (версія 85.0.4183.83)
**Priority:** medium
**Severity:** major
[https://jira.softserve.academy/browse/NETLV-756](url)

**Comment by MykytaKlymachkov** [comment]
Still more than 150 symbols can be entered. Error message appears when there is 500 symbols. 
Maximum 156 symbols can be added to the field
![image](https://user-images.githubusercontent.com/72553191/98224673-6b257000-1f5c-11eb-93e6-64bfb551b6f9.png)
![Screenshot_73](https://user-images.githubusercontent.com/72553191/98224705-78425f00-1f5c-11eb-8dde-469ac3cd0865.jpg)
