### ISSUE TITLE
['Забули пароль' page] Wrong message when a user click on "Надіслати" button

### ISSUE THREAD

**Issue by AnnaBurtnyk** [ita-social-projects/EPlast#348]
**Pre-condition:**
A user has an existing account (e.g. L: forplast@email.ua P: Forplast00)

**Steps:**
1. Go to https://eplastua.azurewebsites.net/ and click on the "Увійти" tab
2. Click on the "Забули пароль" link.
3. Fill in email address associated with ePlast account (e.g. forplast@email.ua)
4. Click on the "Надіслати" button

**Actual result:** 'ForgotPasswordConfirmation' message appears
**Expected result:** The corresponding message: "Для скидування пароля, перейдіть за посиланням в листі, яке відправлене на вашу електронну пошту" appears

**Environment**: 64x-based PC, Windows 7, Google Chrome (версія 85.0.4183.83)
**Priority**: low
**Severity**: trivial

[https://jira.softserve.academy/browse/NETLV-762](url)

**Comment by Oksana-lviv** [comment]
Bug verification failed
![bug-ver-fail1](https://user-images.githubusercontent.com/71265495/95063685-565c7f00-0707-11eb-914d-db04c9c6f6fd.jpg)
@ViktorKalynenko

**Comment by MykytaKlymachkov** [comment]
Retested 11.11
