### ISSUE TITLE
By clicking on the 'Більше' button in the 'Провід станиці' block, he/she would be redirected to the empty page.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#421]
**Defect**
**Summary:** If a 'Станиця' doesn't have a head and the user clicks on the 'Більше' button in the 'Провід станиці' block, he/she would be redirected to the empty page.

**Steps to Reproduce:**
1. Open the application and register into a system (doesn't matter your authorities)
2. Choose the 'Станиці' tab
3. Choose the 'Станиця' that doesn't have a head of 'Станиця' 
(For example https://eplast.westeurope.cloudapp.azure.com/cities/17)
4. Click on the 'Більше' button in the 'Провід станиці' block

**Actual Result:**
The page is empty and doesn't load.
**Expected Result:**
The user is redirected to the 'Провід станиці' page. 

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/94129734-64d3ac80-fe64-11ea-81d5-3a0b3d08f9bc.png)
Expected.png
![image](https://user-images.githubusercontent.com/50527578/94129667-52597300-fe64-11ea-9b69-7c11692a03e1.png)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 24.09.20 at 12:00
**Tester:** Nataliya Romanyuk

**Severity:** High
**Priority:** High

**Comment by Oksana-lviv** [comment]
![image](https://user-images.githubusercontent.com/71265495/96336878-3de74f80-108b-11eb-8db4-fe239f015793.png)
