### ISSUE TITLE
On the 'Станиця' page when the user clicks on the 'Деталі' button, there is a list of details with the link. There is no ability to be redirected to the website by clicking on this link.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#423]
**Defect**
**Summary:** On the 'Станиця' page when the user clicks on the 'Деталі' button, there is a list of details with the link. There is no ability to be redirected to the website by clicking on this link.

**Steps to Reproduce:**
- Open the application and register into a system (doesn't matter your authorities)
- Choose the 'Станиці' tab
- Choose any 'Станиця' that has a link in the description 
(For example https://eplast.westeurope.cloudapp.azure.com/cities/5)
- Click on the 'Деталі' button under the photo of a 'Станиця'.
- The details page is opened.

**Actual Result:**
The 'Посилання' link is not clickable and there is no possibility to open a website.
**Expected Result:**
The 'Посилання' should be clickable, not only a text. The link should be a blue-colored and be underlined when a user hovers over it.
The user is redirected to the website by clicking on the 'Посилання' link.

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/94135512-39ed5680-fe6c-11ea-8395-8412ea308bed.png)

Expected_without_user_pointer.png
![image](https://user-images.githubusercontent.com/50527578/94136548-c2b8c200-fe6d-11ea-978a-65eba9261a31.png)

Expected_with_user_pointer.png
![image](https://user-images.githubusercontent.com/50527578/94136602-d6fcbf00-fe6d-11ea-87f5-512daf24ee14.png)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 24.09.20 at 13:00
**Tester:** Nataliya Romanyuk

**Severity:** 
**Priority:**

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
