### ISSUE TITLE
There is no limits in the fields when the user create a new 'Станиця'.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#425]
**Defect**
**Summary:** There are no limits in the fields when the user creates a new 'Станиця'.

**Steps to Reproduce:**
- Open the application and register into a system as a Region Administrator.
- Choose the 'Станиці' tab.
- Click on the PLUS to create a new 'Станиця'.
- Write to required fields the unlimited amount of symbols with any type.
[For example:
*Назва:* *7-_&$#@#$%^&(0__ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
*Вулиця:* *7-_&$#@#$%^&(0__ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
*Округ:* - choose any from the dropdown
*Номер будинку:* *7-_&$#@#$%^&(0__ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
]
- Click on the 'Підтвердити' button.

**Actual Result:**
In the right upper corner there is a pop-up window with the text 'Створення'.
The system does nothing.

**Expected Result:**
There should be limits to each field. Also, the appropriate messages should tell the user what to do to fill everything correctly.
All limits and error messages are described in this User Story:
https://github.com/ita-social-projects/EPlast/issues/401#issue-706185579

If something went wrong there should be a pop-up window that signals about the problems with the creation of a new ‘Станиця’. The text in this window: ‘Не вдалося створити станицю’.

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/94163759-e04b5300-fe90-11ea-99fb-9fc64dea0f3e.png)
Expected_an_example.png
![image](https://user-images.githubusercontent.com/50527578/94164245-75e6e280-fe91-11ea-9e35-a30d59b2b489.png)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 24.09.20 at 13:00
**Tester:** Nataliya Romanyuk

**Severity:** Medium
**Priority:** Medium

**Comment by Oksana-lviv** [comment]
pass
