### ISSUE TITLE
When the new 'Станиця' is created, the user could come back again to the creation of a 'Станиця' and double do the same action.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#426]
**Defect**
**Summary:** When the new 'Станиця' is created, the user could come back again to the creation of a 'Станиця' and double do the same action.

**Steps to Reproduce:**
- Open the application and register into a system as a Region Administrator.
- Choose the 'Станиці' tab.
- Click on PLUS to create a new 'Станиця'
- Enter all required fields
*[For example:
**Назва**: Львів
**Вулиця:** Наукова
**Округ:** Львівський
**Номер будинку:** 1]*
- Click on the 'Підтвердити' button
- Click 'Back' in the browser

**Actual Result:**
The user is in the creation of a new 'Станиця' field

**Expected Result:**
The user is in the 'Станиці' tab

**Attachments:**
Back_button.png
![image](https://user-images.githubusercontent.com/50527578/94246446-6cf32100-ff24-11ea-9c9a-3e33622a7b19.png)

Actual.png
![image](https://user-images.githubusercontent.com/50527578/94246291-3cab8280-ff24-11ea-8c51-b1a0d0324ae5.png)
Expected.png
![image](https://user-images.githubusercontent.com/50527578/94246333-49c87180-ff24-11ea-8bef-082e4e93e76e.png)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 25.09.20 at 12:00
**Tester:** Nataliya Romanyuk

**Severity:** Medium
**Priority:** Low

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
