### ISSUE TITLE
[Creation of 'Станиця'] The link field is demonstrated on the whole screen.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#428]
**Test Data**
Login: admin@eplast.com
Password: 12345

_For the creation of a new 'Станиця'_
Назва: Львів
Вулиця: Наукова
Округ: Львівський
Номер будинку: 1
Послання: dsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdfdsdsdf
**Pre-Conditions**
1. Open the ePlast application
2. Log in to the system using test data
**Steps to Reproduce:**
1. Choose the 'Станиці' tab.
2. Click on PLUS to create a new 'Станиця'
3. Enter all required fields and 'Посилання' field with 250 symbols (use a test data)
4. Click on the 'Підтвердити' button

**Actual Result:**
There are no limits in the 'Посилання' field.
The 'Посилання' link is on the whole screen and overlaps the frame. 
**Expected Result:**
There is a limit in the input to the 'Посилання' field (as it was in the User Story: 200 symbols)
There is a reduction of long links.
If the user hovers over the link, the hint should appear with the whole link.

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 25.09.20 at 13:00
**Tester:** Nataliya Romanyuk

**Severity:** Medium 
**Priority:** Medium

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/94247618-0c64e380-ff26-11ea-97a7-abf383a9b452.png)
Expected_withoutpoint.png
![image](https://user-images.githubusercontent.com/50527578/94247952-7d0c0000-ff26-11ea-9d06-d52182a5b47d.png)
Expected_withpoint.png
![image](https://user-images.githubusercontent.com/50527578/94276681-38e22500-ff51-11ea-9764-100981f9ec5a.png)

**Comment by NataRomm** [comment]
Error Message in the 'Посиланя' field is 'Максимальна довжина - 500 символів!'
In fact, the user may input only 256 symbols in this field. In any other case the 'Не вдалося створити станицю' cannot be created (the error message appears on the right upper corner).

**Comment by MykytaKlymachkov** [comment]
256 symbols? Can be closed?
