### ISSUE TITLE
The 'Опис' in the details of 'Станиця' is not fully demonstrated.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#440]
**Summary:** The 'Опис' in the details of 'Станиця' is not fully demonstrated.

**Steps to Reproduce:**

1. Click on the 'Станиці' tab
2. Open an existent 'Станиця' with the description more than 
(for example: )
3. Click on the 'Деталі' button.

**Actual result:**
The 'Опис станиці' field is limited to 38 characters. Other info is not visible for users.

**Expected results:**
The user could see all description of a 'Станиця'. The 'Опис' field is fully visible.

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/94693284-2fcfca00-033c-11eb-948f-f517eb385955.png)

Expected.png
![image](https://user-images.githubusercontent.com/50527578/94693219-1cbcfa00-033c-11eb-8418-b6a4e76a239d.png)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 25.09.20 at 13:00
**Tester:** Nataliya Romanyuk

**Severity:** Medium
**Priority:** Medium

**Comment by tvardero** [comment]
![image](https://user-images.githubusercontent.com/45442278/171046465-85dc14ef-293f-4ee2-a420-dfdf26eeddfd.png)
