### ISSUE TITLE
[Awards Page] There is no error message when input letters in the 'Номер в реєстрі' field

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#447]
**Summary:** [The creation of an award]There is no error message when input letters in the 'Номер в реєстрі' field.

**Test Data**
Номер в реєстрі: aaa%%^

**Pre-Conditions:**
- Open the application and register into a system as a Region Administrator.
- Choose the 'Відзначення' tab.

**Steps to Reproduce:**
- Click on the 'Додати відзначення' button
- Type in the 'Номер в реєстрі' field data from the test data (letters and reserved characters)

**Actual Result:**
Error message: 'Це поле має бути заповненим'
**Expected Result:**
Error message: 'Це поле може містити лише цифри'

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/95063181-b141a680-0706-11eb-842d-5ba9aa1dbaad.png)
Expected.png
![image](https://user-images.githubusercontent.com/50527578/95063460-07164e80-0707-11eb-81e5-e3d1307c58c7.png)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 25.09.20 at 13:00
**Tester:** Nataliya Romanyuk

**Severity:** Low
**Priority:** Low

**Comment by MykytaKlymachkov** [comment]
No letters or other symbols can be entered to the field, so existing error message is OK

Retested 05.11.2020
