### ISSUE TITLE
[Awards Page] The 4-digit number in the '№' column is shifted to the next row

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#450]
**Summary:** [Awards Page] The 4-digit number in the '№' column is shifted to the next row

**Test Data**
Номер в реєстрі: 1000
Відзначення: Залізний пластовий хрест
Ім'я: Victor Kalynenko
Дата затвердження: 05-10-2020

**Pre-Conditions:**
- Open the application and register into a system as a Region Administrator.
- Choose the 'Відзначення' tab.

**Steps to Reproduce:**
- Click on the 'Додати відзначення' button
- Input all valid info to required fields
- Click on the 'Опублікувати' button
- Find this new line in the list
- Pay attention to the '№' field

**Actual Result:**
The 4-digit number in the '№' column is shifted to the next row
**Expected Result:**
The 4-digit number in the '№' column is in the one line.

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/95066421-0da6c500-070b-11eb-9c49-ec86109679c1.png)

Expected.png
![image](https://user-images.githubusercontent.com/50527578/95066606-4b0b5280-070b-11eb-9129-3dc13dff7829.png)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 5.10.20 at 13:00
**Tester:** Nataliya Romanyuk

**Severity:** Low
**Priority:** Low

**Comment by MykytaKlymachkov** [comment]
Retested 05.11
