### ISSUE TITLE
[Awards Page] if a long 'Тип відзначення' is entered, its name overlaps the frame

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#453]
**Summary:** [Awards Page] if a long 'Назва типу відзначення' is entered, its name overlaps the frame.

**Test Data**
Назва типу відзначення: 1111111111111111111111111111111111111111111111111111111111112222222222222222222222222222222222222222222222222222222222222222222222222222333333333333333333333333333333333333333333333333333333333333333333333333333555566666666666666666666666666666666677

**Pre-Conditions:**
- Open the application and register into a system as a Region Administrator.
- Choose the 'Відзначення' tab.

**Steps to Reproduce:**
- Click on the 'Редагування типів відзначень' button
- Type in the 'Номер в реєстрі' field data from the test data
- Click on the 'Додати' button

**Actual Result:**
The name overlaps the frame
**Expected Result:**
Reduction of long names (adding '...' in the end).
If the user hovers over the name, the hint should appear with the whole name.

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/95070201-704e8f80-0710-11eb-95ab-a2e85939b9d5.png)
Expected.png

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 5.10.20 at 13:00
**Tester:** Nataliya Romanyuk

**Severity:** Low
**Priority:** Low

**Comment by MykytaKlymachkov** [comment]
Retested 05.11
