### ISSUE TITLE
[Awards Page] The search by numbers doesn't work correctly.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#477]
**Pre-Conditions:**
- Open the application and register into a system as a Region Administrator
- Choose the 'Відзначення' tab.
- There are at least 2 items on the list.

**Steps to Reproduce:**
- Click on the 'Search' field
- Type '11'

**Actual Result:**
There are items that in the list has '11' at their data.

**Expected Result:**
There are not only items that in the list has '11' at their data.

**Attachments:**
![image](https://user-images.githubusercontent.com/50527578/95443767-a8024500-0965-11eb-9333-b6886e15f457.png)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 06.10.20 at 13:00
**Tester:** Nataliya Romanyuk

**Severity:** Low
**Priority:** Medium

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
