### ISSUE TITLE
[Header][Homepage] Dropdown menu icon disappears after resizing window

### ISSUE THREAD

**Issue by MykytaKlymachkov** [ita-social-projects/EPlast#483]
**Environment**
Google Chrome Version 86.0.4240.75 (Official Build) (64-bit)
Windows 10 (64-bit)
**Severity:** Low
**Priority:** Low
**Steps to reproduce:**
1. Open ePlast homepage: https://eplast.westeurope.cloudapp.azure.com/
2. Resize window with a button on top right corner of the screen
3. Resize window with mouse

**Actual result:**
Menu in header is grouped under "..."

**Expected result:**
Menu in header expands back after  resizing window back to fullscreen.

**Additional information:**
Menu still works, but if user navigates to "contacts" page "..." icon will disappear from the header
If window is resized from the contacts page "..." icon will also disappear 

![ePlastAfterResize1](https://user-images.githubusercontent.com/72553191/95687008-b3759a80-0c09-11eb-9dae-a5ed2a29cb6c.jpg)
![ePlastAfterResize2](https://user-images.githubusercontent.com/72553191/95687012-b4a6c780-0c09-11eb-8fa0-e7af65993e06.jpg)
![ePlastAfterResize3](https://user-images.githubusercontent.com/72553191/95687014-b53f5e00-0c09-11eb-87d2-4423851c4dd4.jpg)
![ePlastAfterResize4](https://user-images.githubusercontent.com/72553191/95687015-b5d7f480-0c09-11eb-98a1-0d354aba0a7e.jpg)

**Comment by OlenaTomashevska** [comment]
Bug remains the same
![After resizing](https://user-images.githubusercontent.com/72553215/99710477-43c8ba00-2aa9-11eb-9a36-829d8da4fda9.png)
