### ISSUE TITLE
['Станиці'] Right switch pagination button is shifted down.

### ISSUE THREAD

**Issue by bor1lviv** [ita-social-projects/EPlast#489]
**Summary:** Right switch pagination button is shifted down.

**Preconditions:**
1. At least the 6 pages of 'Станиці' is created.
2. Go to https://eplast.westeurope.cloudapp.azure.com/.
3. Log in as Admin or any registered user.

**Steps to reproduce:**
1. Tap the 'Станиці' link at the left menu.
2. Scroll down the page to the pagination controls.
3. Pay attention to the Right switch pagination button.

**Actual result:**
Right switch pagination button is shifted down.

**Expected result:**
Right switch pagination button is displayed alligned in one row with pages buttons.

![pagination navigation button is shifted](https://user-images.githubusercontent.com/71265604/95737591-989a3900-0c90-11eb-8423-97205f9813e2.jpg)

**Priority:** Low
**Severity:** Minor
**Environment:** Android 6.0 MRA58K, Chrome Browser 86.0.4240.75

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
