### ISSUE TITLE
[Awards Page] After the clicking on editing a type of award and then deleting, the edit string does not change the appearance 

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#491]
**Pre-Conditions:**

1. Open the application and register into a system as a Region Administrator
2. Choose the 'Відзначення' tab.
3. In the 'Редагування типів відзначень' should be at least 1 type.

**Steps to Reproduce:**

1. Click on the 'Редагування типів відзначень' button
2. Click on the 'Edit' button near the some item
3. After the appearing an editability in the field, click on the 'Delete' button (the same item)

**Actual Result:**
The string in the field for editing is not changed. The deleted item is disappeared from the list.

**Expected Result:**
The string in the field for editing is changed to the previous one appearance. The deleted item is disappeared from the list.

**Attachments:**
![pl](https://user-images.githubusercontent.com/50527578/95744354-d5b7f880-0c9b-11eb-9852-f4e84d05c8fa.gif)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 12.10.20 at 15:00
**Tester:** Nataliya Romanyuk

**Severity:** Medium
**Priority:** Medium

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
