### ISSUE TITLE
[Awards Page] The 'Обгрунтування' field in the 'Додати відзначення' has an ability to stretch more than necessary.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#492]
**Test Data**
Обгрунтування: 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
**Pre-Conditions:**

1. Open the application and register into a system as a Region Administrator
2. Choose the 'Відзначення' tab.

**Steps to Reproduce:**

1. Click on the 'Додати відзначення' button
2. Stretch the bottom right corner of the 'Обгрунтування' field down
2. Type 250 symbols in the 'Обгрунтування' field using a test data

**Actual Result:**
The field is stretched more than necessary.

**Expected Result:**
The field is nor stretched more than 7 strings that is the maximum space for 250 symbols.

**Attachments:**
![plл](https://user-images.githubusercontent.com/50527578/95745681-30525400-0c9e-11eb-9849-d1a568d9057e.gif)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 12.10.20 at 15:00
**Tester:** Nataliya Romanyuk

**Severity:** Low
**Priority:** Medium

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
