### ISSUE TITLE
[Awards Page] The 'X' button in the search field 

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#493]
If a user writes something in the search and would like to delete all the info, it would be better to set up an 'X' button.
It may help to do it very quickly.

**Actual:**
![image](https://user-images.githubusercontent.com/50527578/95746020-c8503d80-0c9e-11eb-82f2-205d029cf7b2.png)

**Expected:**
![image](https://user-images.githubusercontent.com/50527578/95746032-cdad8800-0c9e-11eb-9bcb-297803f8bbf3.png)
![image](https://user-images.githubusercontent.com/50527578/95746062-db630d80-0c9e-11eb-8250-11a233b5e034.png)

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
