### ISSUE TITLE
[Edit profile] - Date picker validation does not work.

### ISSUE THREAD

**Issue by ostapalfavitskyi** [ita-social-projects/EPlast#507]
**Priority:** High
**Severity:** High

**Environment:**
OS Microsoft Windows [Version 10.0.18363.1082]
Browser Google Chrome [Version 85.0.4183.121]

**Summary:**
Selecting of future date in the "Дата народження" date picker is allowed.

**Preconditions:**
1. Go to the https://eplast.westeurope.cloudapp.azure.com.
2. Log in.
3. Navigate to the Personal Cabinet page.

**Steps to Reproduce:**
1. Choose the "Редагувати профіль" tab in the Personal Cabinet.
2. Click on the "Дата народження" dates picker.
3. Have a look, that dates after current dates are enabled for selecting.

**Actual Result:**
The future dates in the dates picker are enabled for choosing so the possibility of selecting the future date of birthday is allowed.

**Expected Result:**
All future dates in the dates picker are disabled for choosing so the selection of future dates is blocked.

**Attachment:**
![image](https://user-images.githubusercontent.com/71269318/97162237-97d0cf00-1787-11eb-9ace-8146b1a2211a.png)

**Comment by MykytaKlymachkov** [comment]
#514 #513 - the same problem on other pages
