### ISSUE TITLE
[Awards page] ‘Відзначення’ types can be edited only after double-clicking on ‘Edit’ icon

### ISSUE THREAD

**Issue by OlhaBura** [ita-social-projects/EPlast#519]
**Defect type:** Functional

**Description:**

**Steps to reproduce:**
1. Go to: https://eplast.westeurope.cloudapp.azure.com/
2. Login as a Region Administrator (user name: admin@eplast.com, password: Aa12345.)
3. Go to the left side of web-page.
4. Choose the ‘Відзначення’ tab (‘Персональні дані tab’ → ‘Menu on the left side of the web-page’ → ‘Інформація’ → ‘Відзначення’).
5. Click on the ‘Редагування типів відзначень’ link.
6. Press on ‘Edit’ icon near any type of ‘Відзначення’.

**Actual result:**
Nothing happens. Edit icon works only after double clicks.

**Expected result:**
Edit icon works after one click. Selected field appears in the text-box designed for editing.

**Environment:**
Microsoft Windows 10 Home 2004 
Microsoft Edge 86.0.622.43 

**Severity:** Major
**Priority:** Medium

**Comment by MykytaKlymachkov** [comment]
Retested 10.11
