### ISSUE TITLE
[User’s table, Senior stuff, Awards pages] Standardization to ‘Search’ field, buttons’ view and location.

### ISSUE THREAD

**Issue by OlhaBura** [ita-social-projects/EPlast#520]
### Steps to reproduce:
1. Go to: https://eplast.westeurope.cloudapp.azure.com/
2. Login as a Region Administrator (user name: admin@eplast.com, password: Aa12345.)
3. Go to the left side of web-page.
4. Choose the ‘Таблиця користувачів’ tab.
5. See ‘Search’ field.
7. Choose the ‘Кадра виховників’ tab.
8. See ‘Search’ field and ‘Додати кадру’ button.
7. Choose the ‘Відзначення’ tab.
8. See ‘Search’ field and ‘Додати відзначення’ and ‘Редагування типів відзначення’ buttons.

### Actual result:
‘Search’ fields and buttons are located in arbitrary order. Some ‘Search’ text-boxes contain zooms and some - not.

### Expected result:
‘Search’ field should be located on the left top corner of web-page. The ‘Search’ fields should not contain zooms. Please see mock-ups.

### Environment:
Microsoft Windows 10 Home 2004 
Microsoft Edge 86.0.622.43 

### Priority: Low
![Кадра виховників](https://user-images.githubusercontent.com/72555189/96599199-590ac700-12f8-11eb-9511-981f037eca17.PNG)
![Таблиця користувачів](https://user-images.githubusercontent.com/72555189/96599256-67f17980-12f8-11eb-9300-69233a602dcc.PNG)
![Відзначення](https://user-images.githubusercontent.com/72555189/96599773-eea65680-12f8-11eb-9eb8-154fe7af2082.PNG)

**Comment by MykytaKlymachkov** [comment]
retested 10.11
