### ISSUE TITLE
If the user chooses a 'Станиця' on the 5th page and comes back, he is on the first page again.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#531]
**Pre-Conditions:**
1. Choose the 'Станиці' tab
2. There should be at least 11 items in the 'Станиці'.
3. The configuration of pages is '10/сторінці'

**Steps to Reproduce:**
1. Click on the next page
2. Choose any 'Станиця'
3. Click on the Back button in Browser

**Actual Result:**
The user is on the first page in the 'Станиці' tab
**Expected Result:**
The user is on the last visited page in the 'Станиці' tab

**Attachments:**
Actual.gif
![ffg](https://user-images.githubusercontent.com/50527578/96694719-7770d100-1391-11eb-81fa-d506927b459a.gif)

**Environment:** 
OS Windows, Version 10 Pro

Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 21.10.20 at 12:00
**Tester:** Nataliya Romanyuk

**Severity:** Medium
**Priority:** Medium

**Comment by TonyWebber** [comment]
Not a bug
