### ISSUE TITLE
There is no error message when a 'Станиця' was deleted.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#533]
**Pre-Conditions:**
1. Register to the system as a Region Administrator
2. Click on the 'Станиці' tab
3. There should be at least 1 'Станиця' in the list.

**Steps to Reproduce:**
1. Click on the any 'Станиця' in the list.
2. Click on the Delete button
3. The pop-up window has appeared on the screen
4. Click on for the approvement 'Так, видалити' button

**Actual Result:**
The user is on the 'Станиці' tab.

**Expected Result:**
The user is on the 'Станиці' tab and the error message appears: 'Станицю видалено'.

**Attachments:**
Actual.png
![G](https://user-images.githubusercontent.com/50527578/96700232-e4876500-1397-11eb-8e07-7ea2af80e6ee.gif)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 21.10.20 at 12:00
**Tester:** Nataliya Romanyuk

**Severity:** Low
**Priority:** Medium

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
