### ISSUE TITLE
[Login page] 'Запам'ятати мене' checkbox doesn't work

### ISSUE THREAD

**Issue by OlhaBura** [ita-social-projects/EPlast#550]
**Defect type**: Functional

### Description:

**Steps to reproduce:**

1.Go to: https://eplast.westeurope.cloudapp.azure.com/
2. Enter data into 'Електронна пошта' and ' Пароль' fields  (user name: admin@eplast.com, password: Aa12345.)
3. Input tick into 'Запам'ятати мене' checkbox.
3. Press 'Go' button.
4. Log out from the system.

**Actual result:**
Login page is opened, 'Електронна пошта' and ' Пароль'' textboxes are not filled with data.

**Expected result:**
Login page is opened, 'Електронна пошта' and ' Пароль' textboxes are filled with the credentials entered and saved before

Environment:
Microsoft Windows 10 Home 2004
Microsoft Edge 86.0.622.43

Severity: Major
Priority: Medium

**Comment by DariaBochulya** [comment]
The bug is still reproduceable. Environment: OS Windows 10 pro, Google Chrome 87.0.4280.141

**Comment by DariaBochulya** [comment]
The defect is fixed.
