### ISSUE TITLE
[Edit profile] - The "Стать" drop-down list has unnecessary options.

### ISSUE THREAD

**Issue by ostapalfavitskyi** [ita-social-projects/EPlast#561]
**Priority:** High
**Severity:** High

**Environment:**
OS Microsoft Windows [Version 10.0.18363.1082]
Browser Google Chrome [Version 85.0.4183.121]

**Summary:**
Instead of the two options "Чоловік" and "Жінка", the drop-down list has additional mistaken options.

**Preconditions:**
1. Go to the https://eplast.westeurope.cloudapp.azure.com.
2. Log in.
3. Navigate to the Personal Cabinet page.

**Steps to Reproduce:**
1. Choose the "Редагувати профіль" tab in the Personal Cabinet.
2. Click on the "Стать" drop-down list
3. Have a look, that drop-down list has mistaken options.

**Actual Result:**
The "Стать" drop-down list has additional mistaken options for selecting.

**Expected Result:**
Only "Чоловік" and "Жінка" options are displayed in the "Стать" drop-down list.

**Attachment:**
![image](https://user-images.githubusercontent.com/71269318/97166221-960a0a00-178d-11eb-85ae-15521d218972.png)

**Comment by MykytaKlymachkov** [comment]
**! Need clarification**
Is 'інше' value is valid for product owner. I suggest to leave only two values such as:
'Чоловік' and 'Жінка'
![Screenshot_58](https://user-images.githubusercontent.com/72553191/97849400-2fd83680-1cfb-11eb-9481-d11d1ea57b00.jpg)
