### ISSUE TITLE
[Edit profile] - The image upload feature works selectively (uploading permitted files after several attempts).

### ISSUE THREAD

**Issue by ostapalfavitskyi** [ita-social-projects/EPlast#562]
**Priority:** High
**Severity:** High

**Environment:**
OS Microsoft Windows [Version 10.0.18363.1082]
Browser Google Chrome [Version 85.0.4183.121]

**Summary:**
 The permitted image is uploaded after several failed attempts. **_This bug is accidental and not always reproducible._**

**Preconditions:**
1. Go to the https://eplast.westeurope.cloudapp.azure.com.
2. Log in.
3. Navigate to the Personal Cabinet page.

**Steps to Reproduce:**
1. Choose the "Редагувати профіль" tab in the Personal Cabinet.
2. Click on the "Вибрати" uploading button.
3. Select an image allowed for uploading.
4. Have a look, that photo uploading can be failed for unknown reasons.

**Actual Result:**
The permitted image is uploaded after several failed attempts.

**Expected Result:**
An image is successfully uploaded after the first attempt.

**Attachment:**
![image](https://user-images.githubusercontent.com/71269318/97169696-239c2880-1793-11eb-9893-4c9b2b7444ca.png)

**Comment by MykytaKlymachkov** [comment]
Tried to reproduce several time with JPG images with different size, also tried PNG img.

Closed 05.11.2020
