### ISSUE TITLE
Unify the date format throughout the ePlast App

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#565]
It would be better to unify the date format throughout the whole program. 
Right now there are 2 types of data formats presented in the app:
![image](https://user-images.githubusercontent.com/50527578/97286365-142ce600-184c-11eb-8720-b00371189630.png)
![image](https://user-images.githubusercontent.com/50527578/97286392-1e4ee480-184c-11eb-98b1-17c9c894f659.png)

I suggest unifying all data formats to the format **DD.MM.RRRR**. It is the standard format in Ukraine:
![image](https://user-images.githubusercontent.com/50527578/97286469-345ca500-184c-11eb-94ed-62a8914695c8.png)

**Comment by MykytaKlymachkov** [comment]
Related Issues #515  #617 #618
