### ISSUE TITLE
[Creation of 'Станиця'] Incorrect error message near the field 'Електронна пошта'

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#566]
**Test Data:**
Login: admin@eplast.com
Password: Aa12345.

Email: qwerty

**Pre-Conditions:**
1. Log in to the website as a Region Administrator.
2. Click on the 'Станиці' tab.
3. Click on the PLUS button to create a new 'Станиця'

**Steps to Reproduce:**
1. Set value that does not match the email suit (use the test data).

**Actual Result:**
The error message appears: 'Неправильна пошта'
**Expected Result:**
The error message appears: 'Неправильний формат електронної пошти!'

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/97287485-50ad1180-184d-11eb-860b-5f9945b9bcb1.png)

**Environment:** 
OS Windows, Version 10 Pro

Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 27.10.20 at 12:00
**Tester:** Nataliya Romanyuk

**Severity:** Low
**Priority:** Medium

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
