### ISSUE TITLE
[Creation of 'Станиця'] 'Поштовий індекс' field accepts negative values.

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#567]
**Test Data:**
Login: admin@eplast.com
Password: Aa12345.

Поштовий індекс: -0987

**Pre-Conditions:**
1. Log in to the website as a Region Administrator.
2. Click on the 'Станиці' tab.
3. Click on the PLUS button to create a new 'Станиця'

**Steps to Reproduce:**
1. Set a negative value in the 'Поштовий індекс' field ()use the test data).

**Actual Result:**
There is no error message, so you can create a new 'Станиця'.
**Expected Result:**
There is an error message: 'Поштовий індекс може містити лише додатні цифри!'
So, you cannot create a new 'Станиця'.

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/97288504-95857800-184e-11eb-842b-cb0116063106.png)

**Environment:** 
OS Windows, Version 10 Pro

Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 27.10.20 at 12:00
**Tester:** Nataliya Romanyuk

**Severity:** Medium
**Priority:** Medium

**Comment by MykytaKlymachkov** [comment]
Similar field validation as in issue #447
![stanica +-](https://user-images.githubusercontent.com/72553191/98222957-24cf1180-1f5a-11eb-950b-83ff6e243ec4.jpg)
![stanica index field](https://user-images.githubusercontent.com/72553191/98222962-26003e80-1f5a-11eb-84d9-ed8808ae06dd.jpg)
