### ISSUE TITLE
[Awards page] Improvement - adding options for sorting to columns in ‘Відзначення’ list

### ISSUE THREAD

**Issue by OlhaBura** [ita-social-projects/EPlast#569]
Adding options for sorting by 'Відзначення', 'Ім'я' and 'Дата затвердження' columns in ascending and descending order in 'Відзначення' list will help all sorted data by different fields to be got very quickly in case of necessity.
![image](https://user-images.githubusercontent.com/72555189/97346292-ee2b3400-1893-11eb-816c-af3b729d1379.png)

**Comment by MykytaKlymachkov** [comment]
Tested 10.11 - Nice one!
