### ISSUE TITLE
[Decisions page] 'Відмінити' button works incorrectly in 'Додати відзначення' pop-up window

### ISSUE THREAD

**Issue by OlhaBura** [ita-social-projects/EPlast#571]
**Defect type:** Functional

**Description:**

**Steps to reproduce:**

1. Open the application and log in the system (login: "admin@eplast.com", password: "Aa12345."
2. Choose the 'Рішення' tab
3. Click on 'Додати рішення' button.
4. Fill mandatory fields with some data.
5. Click on 'Відмінити' button.
6. Click on 'Додати рішення'.

**Actual result:**
Previously entered data is saved in the fields.

**Expexted result:**
All fields should be blank after clicking 'Відмінити' button and press on 'Додати рішення'.

**Environment:**
Microsoft Windows 10 Home 2004
Microsoft Edge 86.0.622.43

**Severity**: Major
**Priority:** Medium
**Reproducible:** Always

**Comment by MykytaKlymachkov** [comment]
If any attachment was added, than it is not cleared with 'Відмінити' button

![Screenshot_59](https://user-images.githubusercontent.com/72553191/97849873-dde3e080-1cfb-11eb-9c3e-6dd193d67867.jpg)
![Screenshot_60](https://user-images.githubusercontent.com/72553191/97849875-df150d80-1cfb-11eb-873e-b483ba5f65db.jpg)
