### ISSUE TITLE
[Create event] The incorrect gender label is displayed for field of event assignment

### ISSUE THREAD

**Issue by Oksana-lviv** [ita-social-projects/EPlast#573]
**Description:** The incorrect gender label is displayed for field of event assignment
**Environment:** OS: Windows 10, Browser: Google Chrome 81.0.4044.138
**Priority:** high
**Severity:** major
**Reproducibility:** always
**Pre-conditions:** registered user as admin with credentials e-mail: 'admin@eplast.com', Password 'Aa12345.'.

**Steps to reproduce:**
1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Sign in with proper credentials
3. Click on the "Події" link
4. Pay attention to the "Призначений для" field

**Actual result:** The incorrect gender label "Призначений для" is displayed for field of event assignment 
**Expected result:** The correct gender label "Призначена для" is displayed for field of event assignment 

![event-genus](https://user-images.githubusercontent.com/71265495/97359724-df4d7d00-18a5-11eb-8c86-e28fe296f6bd.jpg)

**Comment by MykytaKlymachkov** [comment]
Retested 05.11.2020
