### ISSUE TITLE
[Create event] Incomplete warning message is displayed under "Питання/побажання до булави" field

### ISSUE THREAD

**Issue by Oksana-lviv** [ita-social-projects/EPlast#574]
**Description:** Incomplete warning message is displayed under "Питання/побажання до булави" field after leaving it empty during event creation
**Environment:** OS: Windows 10, Browser: Google Chrome 81.0.4044.138
**Priority:** medium
**Severity:** minor
**Reproducibility:** always
**Pre-conditions:** registered user as admin with credentials e-mail: 'admin@eplast.com', Password 'Aa12345.'.

**Steps to reproduce:**
1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Sign in with proper credentials
3. Click on the "Події" link
4. Click on the "Створити подію" button
5. Choose the "Акція" event, Category "Конгрес"
6. Choose the "Комендант", "Заступник коменданта", "Бунчужний", "Писар" from registered users
7. Choose the “Дата початку” 12/21/2020
8. Choose the “Дата завершення” 12/27/2020
9. Fill the fields with valid data
10. Leave the "Питання/побажання до булави" field empty
11. Click on the "Зберегти подію" button
12. Look at the warning message under the "Питання/побажання до булави" field

**Actual result:** The warning message "Вкажіть питання" is displayed under the field "Питання/побажання до булави"
**Expected result:** The warning message "Вкажіть питання/побажання до булави" is displayed under the field "Питання/побажання до булави" 

![incomplete-warning](https://user-images.githubusercontent.com/71265495/97360939-8c74c500-18a7-11eb-9418-ffb74375717b.jpg)

**Comment by MykytaKlymachkov** [comment]
Reteste 05.11.2020
