### ISSUE TITLE
[Create event] Incorrect warning message is displayed under "Опис події" field

### ISSUE THREAD

**Issue by Oksana-lviv** [ita-social-projects/EPlast#575]
**Description:** Incorrect warning message is displayed under "Опис події" field after leaving it empty during event creation
**Environment:** OS: Windows 10, Browser: Google Chrome 81.0.4044.138
**Priority:** medium
**Severity:** minor
**Reproducibility:** always
**Pre-conditions:** registered user as admin with credentials e-mail: 'admin@eplast.com', Password 'Aa12345.'.

**Steps to reproduce:**
1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Sign in with proper credentials
3. Click on the "Події" link
4. Click on the "Створити подію" button
5. Choose the "Акція" event, Category "Конгрес"
6. Choose the "Комендант", "Заступник коменданта", "Бунчужний", "Писар" from registered users
7. Choose the “Дата початку” 12/21/2020
8. Choose the “Дата завершення” 12/27/2020
9. Fill the fields with valid data
10. Leave the "Опис події" field empty
11. Click on the "Зберегти подію" button
12. Look at the warning message under the "Опис події" field

**Actual result:** The warning message "Вкажіть, які зміни впроваджено " is displayed under the field "Опис події"
**Expected result:** The warning message "Вкажіть, які зміни впроваджено" is displayed under the field "Опис події"

![incorrect-warning](https://user-images.githubusercontent.com/71265495/97361557-5edc4b80-18a8-11eb-93fd-f843e8b8cca5.jpg)

**Comment by tetyanakutsko** [comment]
Actual result: The warning message "Вкажіть, які зміни впроваджено " is displayed under the field "Опис події"
Expected result: The warning message "Вкажіть, які зміни впроваджено" is displayed under the field "Опис події"

???
Expected result: Вкажіть опис події
???

**Comment by Oksana-lviv** [comment]
**Actual result**: The warning message "Вкажіть опис події" is displayed under the field "Опис події"

**Comment by MykytaKlymachkov** [comment]
retested 05.11.2020
