### ISSUE TITLE
[Creation of 'Станиця'] 'Номер телефону' field accepts less quantity of digits than required

### ISSUE THREAD

**Issue by OlhaBura** [ita-social-projects/EPlast#577]
**Test Data:**
Login: admin@eplast.com
Password: Aa12345.
Номер телефону: +38(093)-567-89-0_

**Pre-Conditions:**
1. Log into the website as a Region Administrator.
2. Click on the 'Станиці' tab.
3. Click on the PLUS button to create a new 'Станиця'

**Steps to Reproduce:**
1. Set less quantity of digits than required to 'Номер телефону' field (see test data).

**Actual result:**
New 'Станиця' with less quantity of digits is created. No error message is shown when creating.
![image](https://user-images.githubusercontent.com/72555189/97446042-9bef1f00-1936-11eb-9593-0312b5877e04.png)

**Expected result:** 
Error message "Введіть дійсний номер телефону!" should be shown.
![image](https://user-images.githubusercontent.com/72555189/97447126-e45b0c80-1937-11eb-9476-97f75dfa788f.png)

**Environment:**
Microsoft Windows 10 Home 2004
Microsoft Edge 86.0.622.43

**Severity:** Medium
**Priority:** Medium
**Reproducible:** Always

**Comment by MykytaKlymachkov** [comment]
Retested 10.11
