### ISSUE TITLE
[Річний звіт Станиці] Arrange fields one below the other.

### ISSUE THREAD

**Issue by bor1lviv** [ita-social-projects/EPlast#579]
For the better user experience the fields of the 'Річний звіт станиці' should be arranged one below other, and scrollbar in the right side should be implemented.

**AS IS**
![AS IS](https://user-images.githubusercontent.com/71265604/97494138-96153000-196e-11eb-97e8-cafa2127bfa7.jpg)

**TO BE**
Approximate mockup:
![Zvit Stanyci 03](https://user-images.githubusercontent.com/71265604/97494376-e42a3380-196e-11eb-9e98-5402fe717181.jpg)

**Comment by TonyWebber** [comment]
Узгодили не міняти з замовником
