### ISSUE TITLE
[Decisions page] Wrong error message alignment in 'Додати відзначення' pop-up window

### ISSUE THREAD

**Issue by OlhaBura** [ita-social-projects/EPlast#592]
**Defect type:** UI

**Steps to reproduce:**
1. Open the application and log in the system (login: "admin@eplast.com", password: "Aa12345.")
2. Choose the 'Рішення' tab
3. Click on 'Додати рішення' button.
4. Click on 'Опублікувати' button.

**Actual Result:**
All error messages have different alignment.
![image](https://user-images.githubusercontent.com/72555189/97594520-6e27da00-1a0b-11eb-9bfc-ed7a2107d837.png)

**Expected result:**
Error message alignment is consistent and is similar to all fields.
![image](https://user-images.githubusercontent.com/72555189/97595425-58ff7b00-1a0c-11eb-90fb-9deaca709c09.png)

**Environment:**
Microsoft Windows 10 Home 2004
Microsoft Edge 86.0.622.43

**Severity:** Low
**Priority**: Low
**Reproducible:** Always

**Comment by MykytaKlymachkov** [comment]
Should it be aligned to the left side of the text field?
![Screenshot_55](https://user-images.githubusercontent.com/72553191/97847295-141f6100-1cf8-11eb-8c8f-31c1debf6eb9.jpg)
