### ISSUE TITLE
[Creation of 'Округ'] Unable to delete the uploaded image

### ISSUE THREAD

**Issue by Zvizdetska** [ita-social-projects/EPlast#603]
**Pre-Conditions:**
1. Open the application and log in to the system (login: "admin@eplast.com", password: "Aa12345.")
2. Choose the 'Округи' tab

**Steps to reproduce:**
1. Click on the '+' button to create a new 'Округ'.
2. Upload a picture (only JPG, PNG, BMP image formats, less than 3 MB)

**Expected result:**
There should be a possibility to delete the uploaded image
![image](https://user-images.githubusercontent.com/32437581/97755602-29cb3580-1b02-11eb-9156-a093d8f5684c.png)

**Actual result:**
There is no possibility to delete the uploaded image
![image](https://user-images.githubusercontent.com/32437581/97755335-a3165880-1b01-11eb-925e-55ef336054f3.png)

**Environment:**
OS Windows, Version 10 Pro
Browser Google Chrome, Version 86.0.4240.111 (Official Build) (64-bit)
**Data and Time:** 30.10.20 at 22:00
**Tester:** Oleksandra Zvizdetska

**Severity:** Low
**Priority:** Low

**Comment by MykytaKlymachkov** [comment]
Retested 05.11
