### ISSUE TITLE
['Контакти' page] error messages are not displayed when the user leaves the fields empty

### ISSUE THREAD

**Issue by Zvizdetska** [ita-social-projects/EPlast#604]
**Steps to reproduce:**

1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Open 'Контакти'
3. Press 'Відправити' button

**Expected result:**
There should be an error message: "Це поле є обов`язковим!" under each field if it is empty.

![image](https://user-images.githubusercontent.com/32437581/97776640-7189a580-1b72-11eb-8fd5-6d307cc88838.png)

**Actual result:**
There are no error messages below the  'Вкажіть Ваш email' and 'Вкажіть Ваш номер телефону' fields. And notification says nothing.

![image](https://user-images.githubusercontent.com/32437581/97776592-18217680-1b72-11eb-9bf0-f4fae6e6e499.png)

**Environment:**
OS Windows, Version 10 Pro
Browser Google Chrome, Version 86.0.4240.111 (Official Build) (64-bit)
**Data and Time:** 31.10.20 at 12:00
**Tester:** Oleksandra Zvizdetska

**Severity:** Low
**Priority:** Medium

**Comment by MykytaKlymachkov** [comment]
Retested 08.11
