### ISSUE TITLE
['Рішення' page]Inconsistent date format

### ISSUE THREAD

**Issue by MykytaKlymachkov** [ita-social-projects/EPlast#617]
**Environment**
Win 10 64(bit)
Google Chrome Version 86.0.4240.75 (Official Build) (64-bit)

**Severity:** Very Low
**Priority:** Trivial

**Steps to reproduce:**

1. Login to ePlast web page with an Administrator
2. Go to 'Рішення' page (https://eplast.westeurope.cloudapp.azure.com/decisions)
3. Pay attention to date format in 'Дата' field.
4. Click 'Додати рішення'
5. Choose any date and pay attention to its' format

**Actual Result:**
Different date formats on the screen to the date format on other pages and in 'Додати рішення' datepicker.  'MM/DD/YYYY '
![Screenshot_56](https://user-images.githubusercontent.com/72553191/97848192-644af300-1cf9-11eb-87a7-c709f59e7249.jpg)
![Screenshot_57](https://user-images.githubusercontent.com/72553191/97848195-64e38980-1cf9-11eb-9bc6-62ea7ba5db82.jpg)

**Expected Result:**
Date format should be consistent and be the same format on any page or screen in format  'DD-MM-YYYY'

**Comment by MykytaKlymachkov** [comment]
#632  
New issue occurred

**Comment by LanchevychMaxym** [comment]
We are going to use "DD.MM.YYYY" format everywhare, thanks!
