### ISSUE TITLE
[Creation of 'Округ'] Additional symbols can be added to fields after error message about max quantity of symbols is shown

### ISSUE THREAD

**Issue by OlhaBura** [ita-social-projects/EPlast#633]
**Defect type:** Functional

**Steps to reproduce:**
1. Open the application and log in the system (login: "admin@eplast.com", password: "Aa12345.")
2. Choose the 'Округи' tab.
3. Click on the PLUS button to create a new 'Округ'.
4. Input big quantity of symbols (more than validation allows) to each fields.

**Actual Result:**
Additional symbols can be added to fields after error message about max quantity of symbols is shown.
![image](https://user-images.githubusercontent.com/72555189/98223614-0a496800-1f5b-11eb-8ddc-5eca032df2a6.png)

**Expected result:**
After max quantity of symbols is entered, the user should not be allowed to add more symbols to the fields while creating new 'Округ'.

**Environment:**
Microsoft Windows 10 Home 2004
Microsoft Edge 86.0.622.43

**Severity**: Medium
**Priority:** Minor
**Reproducible:** Always

**Comment by OlenaTomashevska** [comment]
In the 'Поштовий індекс' text field no limit for entering data.
![No limit](https://user-images.githubusercontent.com/72553215/99709325-b5a00400-2aa7-11eb-83ab-b4ce96ca1df7.png)
