### ISSUE TITLE
[Edit profile page] The user should not be allowed to enter a phone number that is too short

### ISSUE THREAD

**Issue by Zvizdetska** [ita-social-projects/EPlast#637]
**Defect type**: Functional

**Severity**: Medium
**Priority**: High

**Steps to reproduce:**

1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Log in the system (e.g. login: "admin@eplast.com", password: "Aa12345.")'
3. Open 'Редагувати профіль' option.
4. Enter a phone number that is too short (e. g. +38(120)-313-02-__) in the 'Номер телефону' field.
5. Press 'Підтвердити' button.

**Expected result**:
An error message "Введіть коректний номер телефону!" should appear. Changes should not be accepted when the user clicks the 'Підтвердити'  button.

**Actual result**:
Changes are accepted. No error message about the wrong phone number.

Attachment:
![image](https://user-images.githubusercontent.com/32437581/98244217-bc8f2880-1f77-11eb-844b-3442503cfad5.png)

**Reproducible**: Always

**Environment**:
OS Windows, Version 10 Pro
Browser Google Chrome, Version 86.0.4240.111 (Official Build) (64-bit)
**Data and Time**: 05.11.20 at 15:00
**Tester**: Oleksandra Zvizdetska

**Comment by MykytaKlymachkov** [comment]
Still reproduces. No error message is shown!

![Screenshot_82](https://user-images.githubusercontent.com/72553191/98535806-65e36080-228f-11eb-8dba-76834bb00bc2.jpg)
![Screenshot_83](https://user-images.githubusercontent.com/72553191/98535810-667bf700-228f-11eb-9186-856a09657262.jpg)
