### ISSUE TITLE
[Edit profile page] Wrong date of birth is displayed if the user has not selected a date of birth

### ISSUE THREAD

**Issue by Zvizdetska** [ita-social-projects/EPlast#638]
**Defect type**: UI

**Severity**: Medium
**Priority**: High

**Steps to reproduce**:

1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Log in the system (e.g. login: "admin@eplast.com", password: "Aa12345.")'
3. Open 'Редагувати профіль' option.
4. Make sure you haven't selected the date of birth. 
5. Open 'Персональні дані' option.

**Expected result**:
There should be displayed "-" in "Дата народження" field on 'Персональні дані' page if the user has not selected date of birth.

**Actual result**:
The "Дата народження" field on 'Персональні дані' page displays "01-01-0001" if the user has not selected date of birth.

**Attachment**:
Actual result:
![image](https://user-images.githubusercontent.com/32437581/98250284-eb110180-1f7f-11eb-8c22-e79123765302.png)

Expected result:
![image](https://user-images.githubusercontent.com/32437581/98250675-6c689400-1f80-11eb-8d2c-0e179d510568.png)

**Reproducible**: Always

**Environment**:
OS Windows, Version 10 Pro
Browser Google Chrome, Version 86.0.4240.111 (Official Build) (64-bit)
**Data and Time**: 05.11.20 at 15:00
**Tester**: Oleksandra Zvizdetska

**Comment by MykytaKlymachkov** [comment]
Retested 09.11
