### ISSUE TITLE
[Edit profile page] Improvement - 'delete' button to be able to delete the uploaded profile image

### ISSUE THREAD

**Issue by Zvizdetska** [ita-social-projects/EPlast#639]
It would be convenient for the user to be able to delete the uploaded image. 

**Attachments**:

Actual result:
![image](https://user-images.githubusercontent.com/32437581/98260784-637dbf80-1f8c-11eb-94ce-1d86d721c8e9.png)

Expected result:
![image](https://user-images.githubusercontent.com/32437581/98261088-bce5ee80-1f8c-11eb-9d5d-87a100253fc8.png)

**Comment by K-Hrodz** [comment]
![Photo deleting](https://user-images.githubusercontent.com/75993822/102268749-5a392880-3f24-11eb-9ccd-2fb25c65e5ac.PNG)
'Delete' button added (see mock-up)
