### ISSUE TITLE
[Edit profile page] The system does not accept ' "" () ' characters in 'Навчальний заклад', 'Місце праці' fields

### ISSUE THREAD

**Issue by Zvizdetska** [ita-social-projects/EPlast#640]
**Defect type**: Functional

**Severity**: Low
**Priority**: Medium

**Steps to reproduce**:

1. Go to https://eplast.westeurope.cloudapp.azure.com/
2. Log in the system (e.g. login: "admin@eplast.com", password: "Aa12345.")'
3. Open 'Редагувати профіль' option.
4. Enter words containing ' "" () ' characters in 'Навчальний заклад', 'Місце праці' fields.
5. Press 'Підтвердити' button 

**Expected result**:
The system should allow the user to enter ' "" () ' characters in 'Навчальний заклад', 'Місце праці' fields. Since these characters can be in such fields.

**Actual result**:
The system does not accept  ' "" () ' characters. Error messages are displayed.

**Attachment**:
Actual result:
![image](https://user-images.githubusercontent.com/32437581/98263207-37b00900-1f8f-11eb-87f4-a97947364d15.png)

**Reproducible**: Always

**Environment**:
OS Windows, Version 10 Pro
Browser Google Chrome, Version 86.0.4240.111 (Official Build) (64-bit)
**Data and Time**: 05.11.20 at 17:00
**Tester**: Oleksandra Zvizdetska

**Comment by ohumenchuk** [comment]
For 'Начальний заклад' issue was fixed. For 'Місце праці' issue not fixed, plus it also cannot contain digits, so a separate bug #1102 was opened; this bug #640 is moved to Done to avoid duplication.
