### ISSUE TITLE
['Рішення' page] Double notification is shown when adding new entry with 'Скасовано' status

### ISSUE THREAD

**Issue by MykytaKlymachkov** [ita-social-projects/EPlast#670]
**Priority:** medium
**Severity:** medium

**Environment:**
Win 10 64(bit)
Google Chrome Version 86.0.4240.75 (Official Build) (64-bit)

**Steps to reproduce:**

1. Login as Admin to Eplast system
2. Go to 'Рішення' page (https://eplast.westeurope.cloudapp.azure.com/decisions)
3. Click 'Додати рішення'
4. Fill all fields with valid credentials
5. Choose 'Статус рішення':  'Скасовано'
6. Click `Опублікувати`

**Expected result:**
"Рішення успішно додано" notification is shown. New entry is created

Actual result:
"Рішення успішно додано" notification is shown.
"Рішення не існує" notification is shown. 
New entry is not visible on the page, but appears after reloading web page(F5)

![Screenshot_94](https://user-images.githubusercontent.com/72553191/99254174-9b052b00-281a-11eb-951f-75eb6fef8c53.jpg)

**Comment by MykytaKlymachkov** [comment]
This can be reproduced with other statuses. Can`t catch it, but sometimes new entry cannot be created

**Comment by MarianaTsiuz** [comment]
Bug was reproduced severals time when I was trying to add new entry, couldn't catch it after

Steps to reproduce:

Login as Admin to Eplast system
Go to 'Рішення' page (https://eplast.westeurope.cloudapp.azure.com/decisions)
Click 'Додати рішення'
Fill all fields with valid credentials
Attach file
Choose 'Статус рішення': 'У розгляді'
Click Опублікувати

![пласт 2](https://user-images.githubusercontent.com/76007540/102860137-e45a2300-4435-11eb-9fa1-2bbac64dd482.png)
