### ISSUE TITLE
[Registration] Latin letters could be used for a 'New User' creation

### ISSUE THREAD

**Issue by Iravozna** [ita-social-projects/EPlast#733]
**Defect type:** Functional
**Severity:** Low
**Priority:** High
**Environment:** Google Chrome version 86.0.4240.198 , Windows Server 2016 Standard (64-bit).
**Reproducible:** always

**Steps to reproduce:**

1. Go to: https://eplast.westeurope.cloudapp.azure.com/
2. Click on Registration form 
3. Add a valid e-mail into 'Email' field
4. Create password (8 characters according to User Story #389 )
5. Re-type password once again
6. Add a name into 'Name' field using Latin letters 'Iryna', 
7. Add a surname into 'Surname' field using Latin letters 'Vozna'
8. Press 'Save' button

**Actual result:**
A new user created with Latin letters. No restrictions/error messages appear to create a user with Latin letters.

**Expected result:**
Only Cyrillic letters could be used for creation user's name and surname.

**User story and test case links**
[NETLV-99] As a user I want to register into a system #389
https://github.com/ita-social-projects/EPlast/issues/389

**Labels to be added**
"Bug" ("bug")

**Comment by tvardero** [comment]
Backend now denies use of Latin letters in first name and last name (+ father's name). 
Should not be reproducible anymore.

**Comment by tvardero** [comment]
Waiting for PR https://github.com/ita-social-projects/EPlast-Client/pull/980
