### ISSUE TITLE
[Events notifications] Notification about created events of Admin/rejected or submitted events for User are not disappearing in notification menu

### ISSUE THREAD

**Issue by K-Hrodz** [ita-social-projects/EPlast#737]
**Environment:** Windows 10, Chrome 87.0.4280.88 , Firefox 84.0, Edge 87.0.664.60.

**Reproducible:** Always.

Severity: Minor

Priority: Low

**Steps to reproduce**
1. Go to 'https://eplast.westeurope.cloudapp.azure.com/signin'
2. Log in the system as User.
3. Go to Event/'Події' Tab.
4. Declare event.
5. Log out and re-log in as Admin.
6.  Go to  Event/'Події' Tab.
7. Reject or accept declared event.
8. Log out and re-log in as User.

**Actual result**
Notification about created events of Admin/rejected or submitted events for User are not disappearing in notification menu, only in alert window immediately after changing of event status.

**Expected result**
Notification about created events of Admin/rejected or submitted events for User should disappear in notification menu.

**User story and test case links**
"User story [Event] As a user (except Adherent) I want to create an event #390

**Comment by tetyanakutsko** [comment]
Event can't have rejected status. Only not approved, approved, finished
