### ISSUE TITLE
[Events/UI] Main menu end Events sub-menu UI improvment (mobile version)

### ISSUE THREAD

**Issue by K-Hrodz** [ita-social-projects/EPlast#769]
**Environment:** Android, IOS.

### **1. Main menu.**
Background color of  drop-down main menu would be better to perform more lighter for better contrast and readability (see attachments).

**Actual result** 

.ant-menu-submenu-popup .ant-menu.ant-menu-sub {
    background-color: #3c5438;
... }

**Example of improvment**
.ant-menu-submenu-popup .ant-menu.ant-menu-sub {
    background-color: #d4dad4;
... }

### **2. Events sub-menu **

In all Events sub-menu ('Created events', 'Events details') would be better to center options buttons (see attachment). 

**Actual result** 
.EventUser_buttonSmall__gXsIc {
    ...
    margin-left: 125px;
... }

**Example of improvment**

.EventUser_buttonSmall__gXsIc {
    ...
    margin-left: ...
    margin-right: ...
... }
![Impr  menu ](https://user-images.githubusercontent.com/75993822/103135108-b1769000-46be-11eb-8b39-4eb87706a7fd.jpg)
![impr  menu_example](https://user-images.githubusercontent.com/75993822/103135110-b5a2ad80-46be-11eb-8378-6e04367865c5.png)
![Impr  buttons](https://user-images.githubusercontent.com/75993822/103135114-ba676180-46be-11eb-880f-05ee17df7b4a.jpg)
![Impr  button2](https://user-images.githubusercontent.com/75993822/103135117-bcc9bb80-46be-11eb-88c1-76b0008744b0.png)

**Comment by christykobyletska** [comment]
1. done
2. there is a bug #1698 for this
