### ISSUE TITLE
[Governing bodies/Керівні Органи][All roles] Use the "Органи Управління" search page. - IRRELEVANT

### ISSUE THREAD

**Issue by x0lana** [ita-social-projects/EPlast#847]
**As a user, I want to use the "Керівні Органи" search page so that I could view the list of all the existing governing bodies and find a specific one.**

**Preconditions:**
- User has opened the **ДЕ БУДЕ ЗНАХОДИТИСЬ ЦЯ ВКЛАДКА**

**Assumptions and Constraints:**

**Business rules:**
1. All ePlast users have access to the "Керівні Органи" search page.

### Acceptance Criteria
1. The "Керівні Органи" search page consists of the following elements:
- a title "Керівні Органи"
- a search box
- list of governing bodies
- pagination
![image](https://user-images.githubusercontent.com/76438143/106793365-0b745900-6660-11eb-9a2e-d0a0c512e899.png)

1. A user can search the governing bodies using a search box.
  1.1. The search input field contains a hint: "Пошук"
  1.2. A system searches the matches by 1 letter, a combination of letters, a word, a phrase.
  1.3. A search is case insensitive.
  1.4. A system displays the options that contain data from the search input.
  1.5. To start a search, user:
- presses Enter on the keyboard
- clicks on the submit button.
  
  1.6. If a user presses Enter or clicks on the submit button with an empty search field, the system will not perform any actions.
  1.7. If the system has not found any matches, it will show a message:
![image](https://user-images.githubusercontent.com/76438143/106794890-162fed80-6662-11eb-95bd-3969f3e2bd08.png)
  1.8. To return to the initial page view, a user clears the search field and presses Enter or clicks on the submit button.

2. A user can view all the existing governing bodies on the "Керівні Органи" search page.
  2.1. A system displays the governing bodies in the following format:
- an image
- a clickable name of the governing body

  2.2. When a user clicks either on the image or the name of the governing body, a system redirects him to a page of the corresponding governing body.

3. A user can select the number of items shown per page by clicking on the dropdown at the bottom right corner of the page.
  3.1. The default number of items per page = 10.
  3.2. A user can select:
- '10/сторінці' (10 items per page)
- '20/сторінці' (20 items per page)
- '50/сторінці' (50 items per page)
- '100/сторінці' (100 items per page)

  3.3. When the page is reloaded, the number of items per page is default 10 items.
  3.4. When the number of items/page changes, the number of pages changes correspondingly.

4. A user can switch between the pages by:
- clicking on the page number
- clicking on the forward ">" and backward "<" arrows.

  4.1. When a user is on the last page, the forward arrow is disabled.
  4.2. When a user is on the first page, the backward pagination is disabled.

**Epic link**
E.g.: Epic #100 [Epic](https://jira.softserve.academy/browse/100)

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by setorianadya** [comment]
A user story is irrelevant because will be only 7 Governing bodies and we don't need to search for such amount of items.
