### ISSUE TITLE
[Перестороги/Warnings] The value 'догана із загрозою вилучення з пласту' from 'Перестороги' column is spelled starting from the small letter

### ISSUE THREAD

**Issue by khurska** [ita-social-projects/EPlast#926]
**Environment:** Mac OS 10.14 Google Chrome Version 88.0.4324.192
**Reproducible:** always
**Build found:** 6bf189b
**Priority** Very low
**Severity** Trivial

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com and log in as Regional administrator 

**Steps to reproduce**

1. Tap the menu icon on the left upper
2. Expand the 'Довідник' menu
3. Tap 'Перестороги'
4. Click 'Додати пересторогу' 
5. Tap 'Перестороги' dropdown  in the form to make a choice
6. Pay attention to the 'догана із загрозою вилучення з пласту' value option spelling
7. Close the 'Додати пересторогу' form
8. Take a look at 'Перестороги' column
9. Pay attention to the 'догана із загрозою вилучення з пласту' value option spelling

**Actual result**
The value 'догана із загрозою вилучення з пласту' from 'Перестороги' column is spelled starting from the small letter

**Expected result**
The value 'догана із загрозою вилучення з пласту' from 'Перестороги' column is spelled starting from the capital letter

**User story and test case links**
E.g.: "User story #811 #815 
![spelling mistake small letter](https://user-images.githubusercontent.com/79639668/109715354-304ee400-7bac-11eb-84af-6ef9ef32460f.png)
![spelling mistake small letter2](https://user-images.githubusercontent.com/79639668/109715557-760bac80-7bac-11eb-99be-283063042f97.png)

**Comment by veronika-kolosova** [comment]
Not a bug
