### ISSUE TITLE
[Contacts] Ability to send the question with the incorrect format of the entered phone number in text field ''Вкажіть Ваш номер телефону' on the 'Contacts' page.

### ISSUE THREAD

**Issue by DariaBochulya** [ita-social-projects/EPlast#931]
**Environment**: OS Windows 10 pro, Google Chrome 88.0.4324.190
**Reproducible**: always
**Priority**: Medium
**Severity**: Trivial

**Steps to reproduce:**
1. Go to 'https://eplast.westeurope.cloudapp.azure.com/signin' url
2. Press 'Контакти' button on the top right corner of the page
3. Opens new page with ability to write a question
4. Enter name into the 'Вкажіть Ваше ім'я' text field (e.g. Daria)
5. Enter email address into the 'Вкажіть Вашу електронну пошту' text field (e.g. test@gmail.com)
6. Enter incorrect phone number into the 'Вкажіть Ваш номер телефону' text field (**+380 00** 99 99 999)
7. Enter some text into the 'Опишіть Ваше звернення' text field (e.g. test)
8. Press 'Відправити' button

**Actual result:**
The question is sent with incorrect format +380 00, there are no such mobile operators. See attachments below.

**Expected result:** 
The question should not be sent. Should appear error message 'Ви ввели неправильний формат' 
![Знімок екрана 2021-03-03 001254](https://user-images.githubusercontent.com/79641018/109724796-c4bf4380-7bb8-11eb-972d-bc99feaca24b.jpg)
![Знімок екрана 2021-03-03 001306](https://user-images.githubusercontent.com/79641018/109724799-c7219d80-7bb8-11eb-8368-af75d886cb55.jpg)

**Comment by danylo-melnychuk** [comment]
No to fix

**Comment by danylo-melnychuk** [comment]
Not a bug
