### ISSUE TITLE
[Region (Округи)] No error message appears and 'Округа' with the 'Опис' field that contains link was created

### ISSUE THREAD

**Issue by OlhaLeskv** [ita-social-projects/EPlast#937]
**Environment:** Windows 10 Home, Googe Chrome 88.0.4324.190 (64-bit)
**Reproducible:** always.

**Preconditions**
Be logged into as Region admin

**Steps to reproduce**
1. Open “Інформація” option, which is located on the left side vertical menu there must be “Округи” option after “Таблиця користувачів” option
2. Hit the “Створити новий регіон” button then the system must open a page for creating new “Округ”
3. Enter data that contain link into 'Опис' field
4. Enter correct data into other fields
5. Click 'Підтвердити' button

**Actual result**
No error message appears, 'Округа' with the 'Опис' field that contains link was created.
See attachment.

**Expected result**
Error message “Опис округу не повинен містити лінки” appears, 'Округа' with the 'Опис' field that contains link is not created.

**User story and test case links**
E.g.: "User story #542 
[Test case]https://github.com/ita-social-projects/EPlast/issues/936

![Region (Округи)  No error message appears and 'Округа' with the 'Опис' field that contains link was created](https://user-images.githubusercontent.com/79641154/109774841-71291600-7c09-11eb-9eea-f2af291b70bc.PNG)

**Comment by Tali32** [comment]
Not a bug!
