### ISSUE TITLE
[Statistics page] Verify if drop list options can be selected using the keyboard arrows

### ISSUE THREAD

**Issue by YuraIvanochko** [ita-social-projects/EPlast#959]
Type: Functional
Priority: Medium

Preconditions
 Log in as administrator

 Steps
1. Go to https://eplast.westeurope.cloudapp.azure.com/statistics/regions  AND https://eplast.westeurope.cloudapp.azure.com/statistics/cities
2. Click on any mandatory field
3. Try to select an option from the list using the arrow keys and 'Enter'

 Expected result
List options are highlighted and you can easily select options from the list

User story #744 #745

**Comment by sysoyeva** [comment]
User can easily select options from the list using the arrow keys and 'Enter'.
