### ISSUE TITLE
[Округ] Region (округ) is not deleted from the system

### ISSUE THREAD

**Issue by OlhaLeskv** [ita-social-projects/EPlast#968]
**Environment:** Windows 10 Home, Googe Chrome  88.0.4324.190 (64-bit)
**Reproducible:** always

**Preconditions**
Be logged into as Region admin. To delete some “Округ” in the list with “Округи’ must be at least 1 item. That means previously created region.

**Steps to reproduce**
1.  Open “Інформація” option, which is located on the left side vertical menu there must be “Округи” option after “Таблиця користувачів” option
2. Open any region (e.g "Центральна")
3. Hit “Видалити округ” button
4. Click “Так, видалити” option
5. Verify that the region is properly deleted from the system

**Actual result**
The region is not deleted from the system

**Expected result**
The region is properly deleted from the system

**User story and test case links**
"User story https://github.com/ita-social-projects/EPlast/issues/546
[Test case] https://github.com/ita-social-projects/EPlast/issues/967

**Comment by solomiiatarnavska** [comment]
It's not a reproducible bug anymore. After Region archiving we can delete it. And it's deleted completely from the system.
