### ISSUE TITLE
[Statistics page] Misspelling in page header

### ISSUE THREAD

**Issue by YuraIvanochko** [ita-social-projects/EPlast#987]
Environment: Windows 10 / Google Chrome Version 89.0.4389.72
Reproducible: always
Priority: Low
Severity: Minor

Preconditions
Log in as administrator

Steps to reproduce

Go to https://eplast.westeurope.cloudapp.azure.com/statistics/regions

Actual result
"Статистика округ" header

Expected result
"Статистика округів"

User story #744

**Comment by veronika-kolosova** [comment]
Not a bug
