### ISSUE TITLE
['Редагувати профіль' page] 'Ім'я' and 'Прізвище' fields could contain and save forbidden symbols

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#992]
**Environment**: macOS version 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: medium
**Severity**: low
**Build found**:

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log into the system using your credentials 
3. By default you would be directed on 'Персональні дані' insert and your name and surname would be the same as you have entered during your registration session

**Steps to reproduce**
1. Click on 'Редагувати профіль' insert on the right upper corner on the page
2. Edit your 'Ім'я' and 'Прізвище' fields adding {`} and {.} to your name and surname respectively (see attached screen)
3. Click on 'Підтвердити' button 

**Actual result**
Your name and surname have successfully been updated (see attached screen)
You have been directed on 'Персональні дані' insert

**Expected result**
The error message appears 'Поле повинно містити тільки літери'

**User story and test case links**
"User story #699 
![Screenshot](https://user-images.githubusercontent.com/79641118/110380602-03de1080-8061-11eb-96ce-0c32388225dd.png)

![Screenshot at Mar 08 22-44-23](https://user-images.githubusercontent.com/79641118/110379805-f4aa9300-805f-11eb-9a8d-6e30cfadc70c.png)

**Comment by IvMariana** [comment]
The error message appears 'Поле повинно містити тільки літери'
