### ISSUE TITLE
['Редагувати профіль' page] 'Ім'я' and 'Прізвище' fields can not be edited and saved using {()} symbol

### ISSUE THREAD

**Issue by solomiiatarnavska** [ita-social-projects/EPlast#993]
**Environment**: macOS version 10.12.6 (16G2136), Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
**Reproducible**: always
**Priority**: medium
**Severity**: low
**Build found**:

**Preconditions**
1. Go to https://eplast.westeurope.cloudapp.azure.com
2. Log into the system using your credentials
3. By default you would be directed on 'Персональні дані' insert and your name and surname would be the same as you have entered during your registration session

**Steps to reproduce**
1. Click on 'Редагувати профіль' insert on the right upper corner on the page
2. Edit your 'Ім'я' and 'Прізвище' fields adding {()} symbol to your name and surname respectively (see attached screen)

**Actual result**
The error message appears 'Поле повинно містити тільки літери'

**Expected result**
As {()} symbol is allowed during editing 'Ім'я' and 'Прізвище' fields this message should not appear and user should be able to edit and save personal data using this symbol

**User story and test case links**
"User story #699 
![Screenshot at Mar 08 23-01-08](https://user-images.githubusercontent.com/79641118/110381861-c084a180-8062-11eb-9fed-f7d2451023c3.png)

**Comment by IvMariana** [comment]
The User could use {()} symbol during editing 'Ім'я' and 'Прізвище' fields
