### ISSUE TITLE
[Statistics table] Verify if Admin are able to choose the number of items on one table page

### ISSUE THREAD

**Issue by YuraIvanochko** [ita-social-projects/EPlast#994]
Type: Functional
Priority: Medium

Preconditions:
1. Log in as administrator 
2. Go to https://eplast.westeurope.cloudapp.azure.com/statistics/regions AND https://eplast.westeurope.cloudapp.azure.com/statistics/cities
3. Fill in all the mandatory fields with as many as possible values
4. Click 'Сформувати'

Test Steps | Expected result 
------------ | -------------
Select  "10 / сторінці" | Table displays 10 values per page, number of pages = number of displayed values divided by 10
Select  "20 / сторінці" | Table displays 20 values per page, number of pages = number of displayed values divided by 10
Select  "50 / сторінці" | Table displays 50 values per page, number of pages = number of displayed values divided by 10
Select  "100 / сторінці" | Table displays 100 values per page, number of pages = number of displayed values divided by 10
Try to change the table page by clicking on arrows or numbers | The pages are displayed correctly

User story #744 #745

**Comment by Svturinina** [comment]
Test case passed
